### ISSUE TITLE
Contact Page 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#10]
## I need a proper **CONTACT US** page.

I would like to have **input fields** for :   
- **First Name**
- **Last Name**
- **Phone Number**
- **Email ID**
- **Message**

Make sure to add a cool vector art to the left side and the contact us form on the right side.
The page must be **responsive** in **MOBILE , TAB , LAPTOP , DESKTOP**.

Use proper **Font Size** and **design**. 

Include proper Screenshot for the same.

**Comment by harshit4021** [comment]
"I want to work on this issue under JWOC"

**Comment by aditi-gosain** [comment]
I want to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
> "I want to work on this issue under JWOC"

Assigned to @harshit4021

**Comment by privateyash** [comment]
I want to work on this issue under JWOC
