### ISSUE TITLE
♾ API Integration - Club Login

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#100]
## I want to connect the club's login frontend to backend
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐

---

## FIXES 🛠
  
**This is the clubs login page ⤵**

![image](https://user-images.githubusercontent.com/72851613/154678174-6be127c9-b415-4875-bf22-2e1f359abcf2.png)

**I want it so the clubs can login**

**⭐ If they login sucessfully alert them with `Logged you in!!` and redirect them to HOME PAGE**
**⭐If they give invalid credentials alert them with `Please input valid credentials` and then CLEAR the forn**
**⭐You need to use axios to connect the backend and frontend.**
**⭐You can checkout the backend routes inside `server` folder !!**
 
## Integrating 🧠

**Go the `service` folder -> `Api.js` , there you'll need to make functions for calling the API**

**Here's an EXAMPLE OF API FUNCTION ⤵** 

![image](https://user-images.githubusercontent.com/72851613/154679867-1ccf66ee-16ff-4852-8251-4cd7d9962ec6.png)

**As you can see we literally passed the whole useState named `credentials` to the backend , and we got results from it**
**With the help of these results you'll need to do alerts as i mentioned earlier**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by KushalGhosh9899** [comment]
I want to work on this issue Under JWOC
