### ISSUE TITLE
♾ API Integration - Club Register

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#102]
## I want to connect the club's register to the backend
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐

---

## FIXES 🛠
  
**This is the clubs register page ⤵**

![image](https://user-images.githubusercontent.com/72851613/154680823-50e548c5-b296-4ca9-a127-6436f5d0bfd2.png)

**I want it so the clubs can register**

**⭐ If they register sucessfully alert them with `Registration sucessful , please login` and redirect them to LOGIN PAGE**
**⭐If they give invalid credentials alert them with `Please input valid credentials` and then CLEAR the forn**
**⭐If user already EXISTS , alert them with `User already present , please login` and redirect them to LOGIN PAGE**
**⭐You need to use axios to connect the backend and frontend.**
**⭐You can checkout the backend routes inside `server` folder !!**
 
## Integrating 🧠

**Go the `service` folder -> `Api.js` , there you'll need to make functions for calling the API**

**Here's an EXAMPLE OF API FUNCTION ⤵** 

![image](https://user-images.githubusercontent.com/72851613/154679867-1ccf66ee-16ff-4852-8251-4cd7d9962ec6.png)

**As you can see we literally passed the whole useState named `credentials` to the backend , and we got results from it**
**With the help of these results you'll need to do alerts as i mentioned earlier**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I want to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC.

Assigning to you , once done tag me in `#milan` and we can review it together !!
