### ISSUE TITLE
Login Page 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#11]
## I want to have a Login Page for the user.

I would like a nice login form with some vector art image to the left.
The form needs to have : 
- email ID
- Password

Make sure the page is responsive in **MOBILE , TAB . DESKTOP , LAPTOP**
Add screenshots for the same.

**Comment by maneet057** [comment]
Please assign this one to me. I would like to work on it

**Comment by aditi-gosain** [comment]
I want to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
> Please assign this one to me. I would like to work on it

Assigning this to you. @maneet057

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
@maneet057 great work on the issue, see you soon.
Cheers.

**Comment by maneet057** [comment]
> @maneet057 great work on the issue, see you soon. Cheers.
Thank you :)
