### ISSUE TITLE
🎨 UI/UX - Contact Us Layout

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#111]
## I want to fix the layout for contact us page
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔

**Commit message--> `fix: <commit message>`**
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Take a look at the Figma Design first : ⤵**

![image](https://user-images.githubusercontent.com/72851613/154796396-1550f3ca-97ce-40a3-831b-67bef993cb03.png)

**Now take a good look at the Coded version ⤵**

![image](https://user-images.githubusercontent.com/72851613/154796412-737f0619-73a2-4537-a752-bd9773ed10d7.png)

**⭐ I want the dropshadows, input field sizes, submit buttons to be fixed**
**⭐ Instead of using the PNG/JPEG image format , can you use the svg so the quality is much better**
**⭐ Make sure the design looks accurate in case of MOBILES/TABS too !!**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC
