### ISSUE TITLE
🎨 UI/UX - Footer Layout for Tablet

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#112]
## I want to fix the footer layout for tablets
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Let's look at how the footer looks currently ⤵**

![image](https://user-images.githubusercontent.com/72851613/154796562-28877f48-7125-477e-8c9c-62d01d8bd6f2.png)

**Currently it looks weird for tablets**
**Here are some changes that i would love to have ⤵**
  
**⭐ I want the footer content to be center aligned so it's the full width**

![image](https://user-images.githubusercontent.com/72851613/154796620-abad619b-02f3-400e-a465-f60e7511886d.png)

**⭐ Next i would like to have the report button below the social icons**

![image](https://user-images.githubusercontent.com/72851613/154796669-a99d92f0-d6dd-46fc-907d-75a2cdb6d9dc.png)

**⭐ Last but not the least i would like to have all these below contents nice and centered**

![image](https://user-images.githubusercontent.com/72851613/154796724-2eeb33d8-12f0-48cf-99e9-2904e201884c.png)

**⭐ Since you might have to write the footer's code totally again , i will give this a `medium` tag**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I would like to work for this issue under JWOC.

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
> I would like to work for this issue under JWOC.

Go for it !!
