### ISSUE TITLE
Home page cards fonts 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#12]
### The cards in home page looks weird. 
Why not fix it ?

- I want titles like ( "What we do") to be a bit bolder.
- I want sub titles like (" We conjugate ") to have a greater font size

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

Assigned to you  @whiteHatpro

**Comment by whiteHatpro** [comment]
![screenshot-127 0 0 1_5500-2022 02 01-01_12_23](https://user-images.githubusercontent.com/77486870/151861575-fe8674a9-9430-46df-abae-094fbe41ac04.png)
@IAmTamal i have made the desired changes and attached the respective screenshot 
should i create the pull request?

**Comment by IAmTamal** [comment]
This looks awesome , can i get the heading text (what we do . ..) to be a bit bigger , so that it stands out.
And also change it's color to blue , preferebly  : #339a9c

**Comment by whiteHatpro** [comment]
sure!!

**Comment by whiteHatpro** [comment]
@IAmTamal i have done the changes as u asked
should i create pull request?

**Comment by IAmTamal** [comment]
Go ahead.

**Comment by IAmTamal** [comment]
Thanks @whiteHatpro for taking up on this issue.
See you soon !!
