### ISSUE TITLE
The Banner text

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#14]
![image](https://user-images.githubusercontent.com/72851613/151858296-4cf6f121-3c55-40f4-a1a2-1ec1bde0ac25.png)

I need some UI changes here. 
- The text needs to `UpperCase`
- The keywords like **Help , Need** needs to be in a much more bolder format
- The font size needs to a bit bigger. 
- The font styling needs to be improved  , use google fonts (as you wish)

**Comment by Rohan-Hazari** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

assigned to you @Rohan-Hazari

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC
