### ISSUE TITLE
Hard-coded credentials

### ISSUE THREAD

**Issue by sas0922** [IAmTamal/Milan#142]
Use of hard coded credentials in User.js file line # 54 and in Clubs.js line # 62
https://github.com/IAmTamal/Milan/blob/main/server/routes/User.js 
https://github.com/IAmTamal/Milan/blob/main/server/routes/Clubs.js

The hard-coded value "HELLOSECRET123" is used as a key

Hard-coded credentials, such as usernames, passwords, and certificates, should be removed from source code, in my opinion. Instead, if required, save them in configuration files, environment variables, or other data repositories. Store configuration files, including credential data, apart from source code in a safe area with limited access if at all practicable

**Comment by IAmTamal** [comment]
Thanks a lot for mentioning the issues !!
