### ISSUE TITLE
👨‍💻 Feature - Report Modal

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#144]
## I want to make a Report Modal , connected to the report button, also integrate to backend
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
  
Commit message / PR title--> **`feat: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**I need a report modal to appear whenever the user clicks the report button⤵**

![image](https://user-images.githubusercontent.com/72851613/154877630-6830369c-47d0-4c62-aa5b-70daa901a7d1.png)

![image](https://user-images.githubusercontent.com/72851613/154877833-863943ce-ecb4-4435-accd-94eaf2dd6dae.png)

![image](https://user-images.githubusercontent.com/72851613/154877886-20da88c7-b9a6-4b76-b421-f1860e244487.png)

## Extras ⭐

**This is the modal can look , you can delete the "Issue type"**

**Make sure the user is NOT ABLE to submit empty reports**
**Make sure it's reponsive, has good UI**
**The report modal should close after the report is submitted**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by dakshgupta2002** [comment]
Will we need to setup backend routes and controllers too?

**Comment by IAmTamal** [comment]
> Will we need to setup backend routes and controllers too? Can you brief upon the integration part please

The backend is present already. This is how it looks !! ⤵

![image](https://user-images.githubusercontent.com/72851613/154880348-17e32d8b-4c4e-4099-afdd-b5453d12b602.png)


![image](https://user-images.githubusercontent.com/72851613/154880371-02b63344-aa43-4d68-bc15-cc765d83e46b.png)

**You will need to make the UI , work with AXIOS to send the data to backend**
**You might need to test the backend too (incase of bugs)**
**The API calls are made in `src>service>MilanApi.js`**

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWoC

Assigning to you ,
