### ISSUE TITLE
👨‍💻 Feature - Clubs Page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#145]
## I want to display the clubs directly from the database
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
**Commit message / PR title-->** **`feat: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**This is how the clubs are being shown now ⤵**

![image](https://user-images.githubusercontent.com/72851613/154881109-8697dd92-ec5a-43b1-8f2c-f01478c903eb.png)

**I want to make it so these clubs are shown directly from the backend in this format ⤵**

![image](https://user-images.githubusercontent.com/72851613/154881228-a10d1ad4-a2a7-4483-a174-7447697e511e.png)

### **Here is the acess to the figma file --> [Figma FIle](https://www.figma.com/file/yYtpK47xyq30F06TZyEZqv/Untitled?node-id=0%3A1)**

**The backend is already present to get all the cards, you might need to check the `Display.js` in the `server` folder**
**You might also face bugs , that's the reason the tag is `Medium` here**
**In case of any difficulties ping me in `#Milan` channel, instead of DM**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I want to work for this under JWOC.

**Comment by IAmTamal** [comment]
> I want to work for this under JWOC.

Assigning to you
