### ISSUE TITLE
🎨 UI/UX - New Banner upon auth

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#146]
## I want to hide the Banner when the user/club has logged in !! 
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠

**This is how the page looks like even after you haved logged in ⤵**

![image](https://user-images.githubusercontent.com/72851613/154883770-010f9f4a-6d2b-44a2-a984-11d89d858886.png)

**I want it so the `authtoken` is saved in the `session storage` and then i also want to hide the banner and show another banner ⤵**
  
![image](https://user-images.githubusercontent.com/72851613/154883691-ed01816d-3461-48b2-8bca-7115dec2ad26.png)

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Aniket-508** [comment]
I want to work on this under JWoC.

**Comment by IAmTamal** [comment]
> I want to work on this under JWoC.

Assigning to you , make sure your commits/PR title is `fix: give your commit message here` , this is VERY IMPORTANT !!

**Comment by Aniket-508** [comment]
@IAmTamal Is the new banner already made or do I have to make it?

**Comment by IAmTamal** [comment]
> @IAmTamal Is the new banner already made or do I have to make it?

@Aniket-508  , here is the figma file --> https://www.figma.com/file/TuDWqG3vI0e73lBbEjPXue/banner?node-id=0%3A1

You need to make it !!

**Comment by Aniket-508** [comment]
@IAmTamal Then can you please assign medium to it because I thought it was just the bug resolve?

**Comment by IAmTamal** [comment]
> @IAmTamal Then can you please assign medium to it because I thought it was just the bug resolve?

Yeah sure !!

**Comment by Aniket-508** [comment]
@IAmTamal Btw the illustrations are very cool. Where did you get them?

**Comment by IAmTamal** [comment]
> @IAmTamal Btw the illustrations are very cool. Where did you get them?

You can import it from the FIGMA DESIGN itself , i used a plugin named Storyset.

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this under JWOC

Assigned to you
