### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#15]
### I need a brand new footer.

I want you to implement your **amazing UI skills** and make a brand new responsive **footer** !! 
The footer must be of dark color (not too dark) 
Add the footer **ONLY** to the homepage

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
Assigned to you @KushalGhosh9899

**Comment by privateyash** [comment]
I want to work on this issue under JWOC
