### ISSUE TITLE
🎨UI/UX - Report Modal glitches out

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#151]
## I want to fix the report modal for mobile screens
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠

**This is how the report modal appears on mobile , can you fix it ?**
  
![2](https://user-images.githubusercontent.com/72851613/155325555-5d21a701-8c29-45e6-85ff-7b9001bff3b0.jpeg)

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I want to work for this issue under JWOC.

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️

**Comment by IAmTamal** [comment]
> I would like to work on this issue under JWOC ✌️

Assigning it to you
