### ISSUE TITLE
👨‍💻 Feature - Loading circle

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#161]
## I want to add Loading circle to **Clubs Page**
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
![image](https://user-images.githubusercontent.com/72851613/155866985-08c11d7b-34a6-4e99-b7dd-d3a37d166097.png)

**As you can see the clubs takes time to load , you can add a loading icon when it's loading.**

**This should be applicable for mobiles as well as desktops**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Srijita-Mandal** [comment]
Can I work on this issue under jwoc?

**Comment by IAmTamal** [comment]
> Can I work on this issue under jwoc?

Assigned
