### ISSUE TITLE
🎨 UI/UX - LoginBanner

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#162]
## I want to fix the look of Login Banner for mobiles.
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**As you can see currently the text looks huge on mobiles , can you fix it please ?**

![image](https://user-images.githubusercontent.com/72851613/155867140-cc48098d-84fc-4c3a-8f1d-8544b22507bf.png)

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Tess-Vanta** [comment]
I would like to take this up under JWOC

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by KushalGhosh9899** [comment]
I want to work on this under JWOC
