### ISSUE TITLE
🗄 Backend - Events modal

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#169]
## I want to make a events Schema for MongoDb
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
![image](https://user-images.githubusercontent.com/72851613/156089127-047d92aa-0b81-48c7-822f-56371aaee1fc.png)

**Inside here, create a file named `EventsSchema.js`**
**This file will have events schema for Events**

**Here are the things that needs to be in there `Eventname` , `Eventdate` , `Eventlocation`, `Eventdescription`**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by yeshwanth235** [comment]
I would like work on this issue, pls assign it to me.

**Comment by IAmTamal** [comment]
> I would like to work on this issue, pls assign it to me.

Assigned @yeshwanth235
