### ISSUE TITLE
👨‍💻 Feature - Create Events Page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#170]
## I want to make a Events Addition Page
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
![image](https://user-images.githubusercontent.com/72851613/156089520-8c7456e3-25e7-481f-8431-6427223e0621.png)

**⭐In the `App.jsx` , you need to mention the route for the page as `/clubs/createevent`**

**⭐The design is available here --> [Figma File](https://www.figma.com/file/YsqEyFyWTXvkFoM4aPdhOD/Events)**

**⭐The design must be responsive for mobiles as well**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC

**Comment by dakshgupta2002** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

Assigned @dakshgupta2002
