### ISSUE TITLE
👨‍💻 Feature - Dynamic Events Banner

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#171]
## I want to change the Events Banner whenever a "Club" logs in
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠

**⭐This is the default Events Banner for the site⤵**
  
![image](https://user-images.githubusercontent.com/72851613/156090070-213cedb6-5da1-4f4e-b258-28432bd44f7d.png)

**⭐ I want this Banner to change whenever a CLUB logs in.**
**⭐ Here is the style for the new Banner --> [Figma File](https://www.figma.com/file/vZ5FMonJFsZXnmb34Q2US1/Create-Event-banner)**

**⭐Donot change the Banner when a USER logs in**
**⭐The banner must be reverted back to default again whenever the club logs out**

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

Assigned @KushalGhosh9899

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC
