### ISSUE TITLE
🎨 UI/UX - User Register Page 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#172]
## I want to make some changes to the clubs and user's Login page
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Currently this is how the page looks⤵**

![image](https://user-images.githubusercontent.com/72851613/156090613-7453accb-7fa3-43ae-83f7-94b77555338c.png)

**⭐ I want the placeholders to be removed from the red dash marked input fields**
**⭐ I want  the `Firstname` and `Lastname` to be side by side instead of how they are now**
**⭐ Firstname and Lastname should have their place holder**
**⭐ I want a label for them `Enter your name`**
**⭐ Also reduce spaces between the Labels and the Input fields !!**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by Aniket-508** [comment]
I want to work on this under JWoC.

**Comment by IAmTamal** [comment]
Assigned to you @Aniket-508

**Comment by Aniket-508** [comment]
@IAmTamal Please have a look at this!

**Comment by maneet057** [comment]
I would like to work on it under jwoc
