### ISSUE TITLE
🎨 UI/UX - Clubs Login Page

### ISSUE THREAD

**Issue by tamalCodes** [IAmTamal/Milan#173]
## I want to make some changes for the clubs page in the mobiles
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
You will make PRs only to **`tamal-milan`** branch. 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Here's how they currently looks in the mobiles⤵**

![image](https://user-images.githubusercontent.com/72851613/156091538-91be85ae-67fe-4c82-a72f-e29ac3f94213.png)

**⭐As you can see the image looks awfully huge, i want it to be reduced a bit**
**⭐ Remove the `Remember me` from the mobiles**
**⭐ Remove the placeholders from the mobiles**
**⭐ Make sure the Login button is of increased size**

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by yeshwanth235** [comment]
I would like work in this issue, assign it to me pls.

**Comment by mridul4101** [comment]
I would like to work for this under JWOC.

**Comment by IAmTamal** [comment]
Assigned @mridul4101

**Comment by Ankit62042** [comment]
I want to work on this issue
