### ISSUE TITLE
🎨 UI/UX - Club Register

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#174]
## I want to make some changes in the Club Register
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
Commit message / PR title--> **`fix: bla bla bla`**
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Here's how it looks now for mobiles⤵**

![image](https://user-images.githubusercontent.com/72851613/156092022-a303732a-1376-4af3-a802-bf2ebb7a0b97.png)

**⭐The size of text is different for `Description` , fix that**
**⭐Change the title of the Page from `Club Register` to `Register your club`**
**⭐ For desktop reduce the size of the Image, it's huge**
**⭐ Can you add a loading icon when we click register , before showing alert ?**
**⭐ Also do remove the placeholders for the Desktop , they look bad**
**⭐ Reduce the size of the Register button for Desktop**

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC

**Comment by IAmTamal** [comment]
Assigned @Tess-Vanta
