### ISSUE TITLE
🗄 Backend - Events API

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#181]
## I want to make a backend API for events addition
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
In **`Server` --> `routes` --> `Clubs.js` i want to make a new route called `/createevent` which takes**

**⭐ Event Name**
**⭐ Event  Location**
**⭐ Event Date**
**⭐ Event Description**

**from the body and stores this in the Database.**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by yeshwanth235** [comment]
I would like to work on this issue, assign it to me pls.
