### ISSUE TITLE
🗄 Backend schema + route - Contact Us

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#182]
## I want to make API for contact us
 
---
 
### I will follow the [Code of Conduct](https://github.com/IAmTamal/Milan/blob/main/CODE_OF_CONDUCT.md)
 
 ---

## Notice ⛔
 
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**I want to make the MongoDB schema for contact us , here is what it will include**

**⭐ First Name**
**⭐ Last Name**
**⭐ Email ID**
**⭐ Message**

**Once the schema is ready make a route for it in `server` --> `routes` --> `User.js` and name it as `/contactus`**

**The data will be stored in the MongoDB**  

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by r3yc0n1c** [comment]
I want to work on this issue under JWoC 2022

**Comment by yeshwanth235** [comment]
I am interested in working on this issue, can you assign it for me.
