### ISSUE TITLE
Navbar profile logo breaks on user's register page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#190]
### Description

In the Navbar, we have a profile Logo. 

The image breaks here, i need a work around for this. 
Also **CHECK** for all the other screens

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/172828747-aba10b51-fbce-4c05-9239-fdb48add44fc.png)

**Comment by yung-coder** [comment]
I would like to try fix it

**Comment by IAmTamal** [comment]
Sure, go ahead 🚀
