### ISSUE TITLE
Contact Page looks bad 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#191]
### If you take a look properly the contact form looks bad on the right hand side with that square thing and black drop shadow I want you to design a minimal impressive design for the contact page and also make it responsive enough for mobiles and tablets.

**ALSO** try and change the picture to more high quality SVG from Storyset if possible.

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/172829868-e915c53a-39a8-4770-898d-db726188f70f.png)

**Comment by PratishShrivastava** [comment]
@IAmTamal ,can I work on this issue.

**Comment by Hat52** [comment]
I would like to work on this issue.

**Comment by IAmTamal** [comment]
> I would like to work on this issue.

Go for it !!
