### ISSUE TITLE
Home page fixes 🍕

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#199]
### The home page background !!

**I need to have fullscreen background of the hands , currently if you zoom out it shrinks too.
I would like to have it made in such a way that it doesn't shrinks out !!** 

**And stay fullscreen at all times.**

**This should be applicable for mobiles as well**

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/176348649-fa5f53f6-fc65-4512-a987-4c2460ce4e01.png)

**Comment by Hat52** [comment]
I would like to take up this issue

**Comment by IAmTamal** [comment]
Go for it !! 

> I would like to take up this issue
