### ISSUE TITLE
UI/UX - Contact Page 🎨

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#201]
### The contact page looks kind of empty.

**I want to have a minimal yet high quality SVG on the left of the contact page ,it will greatly improve the aesthetics.**

**You can definetly make it responsive SUCH THAT the image is not visible for smaller devices like Mobile Phone and so on , you can create your own minimal image or have one from the references below ⤵**

**[Contact Me Designs 1](https://storyset.com/Contact)**
**[Contact Me Designs 2](https://undraw.co/search)**

**Also fix the fonts such that the HEADING and the FORM TEXTS should have the same fonts.**

### Additional information

![image](https://user-images.githubusercontent.com/72851613/176711368-0e23197c-c9a5-4a03-87c6-c8a5e093636b.png)

**Comment by prabhpreet-code** [comment]
If not assigned, it would be great to work on!!

**Comment by Siddhant422** [comment]
Can you assign this project to me.

**Comment by IAmTamal** [comment]
@Siddhant422 what's the status of the work ?

**Comment by IAmTamal** [comment]
@prabhpreet-code  , if you want to work on it you can ! 
I'm removing @Siddhant422 as it has been 6 days !

**Comment by prabhpreet-code** [comment]
No issues... I'll be reverting back to you with the work !!

**Comment by prabhpreet-code** [comment]
@IAmTamal One thing I would like to know that on mobile and tablets should the image and form be present side by side or wrapped in one after one?

**Comment by IAmTamal** [comment]
Hmm i believe side by side on such a small space would not look good , so you can hide the image in mobiles and only the form would  be there  !

For tablet you can make it side by side OR you can make the form in the center !

**Comment by prabhpreet-code** [comment]
Hey @IAmTamal can you please check once font combination and side image for the desktop version?? 
![Screenshot (2257)](https://user-images.githubusercontent.com/66708921/177786110-d5e7c7c5-8c92-47d7-a402-4475a9c95f26.png)

**Comment by IAmTamal** [comment]
The image can be slight smaller !

**Comment by prabhpreet-code** [comment]
What about this @IAmTamal ?
![Screenshot (2259)](https://user-images.githubusercontent.com/66708921/178103723-f273d1fb-b1a6-4957-8883-0d912bb6cef1.png)

**Comment by IAmTamal** [comment]
Looks good !
