### ISSUE TITLE
UI/UX - Footer 🎨

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#208]
## The footer can definetly have some improvements ! 

**If you take a look below the footer its says `MILAN RIGHT RESERVED . .. `  i want that removed , also there's some white space under it which needs to be removed as well!**

 - The footer must be at the bottom of the screen , and there should be **NOTHING** below it
 - Make sure this works for MOBILES, TABLETS as well 

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/177706054-8494e001-5b9d-458a-8bd0-3b41762834f3.png)

**Comment by deepak-sourcecode** [comment]
@IAmTamal I can help out with this. Could you assign this to me?
