### ISSUE TITLE
Footer needs changes  - Mobiles ⚒

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#214]
### Description

The footer needs some improvements. 
This is  valid for only **Mobile devices**

The texts i preferred to be centered  !
Also the report button is bugged out , that needs to be fixed too ! 

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/178275263-80c9c97f-25d7-4900-a786-fd7d2d82903d.png)

**Comment by Rinshin-Jalal** [comment]
I can do that?

**Comment by IAmTamal** [comment]
> Can I do that?

Go for it  !

**Comment by Rinshin-Jalal** [comment]
Oops Sorry 

I am good at bootstrap 

Sorry for wasting your time...

**Comment by IAmTamal** [comment]
> Oops Sorry
> 
> I am good at bootstrap
> 
> Sorry for wasting your time...



Hi , i didnot understand what you meant to say !

**Comment by Rinshin-Jalal** [comment]
> Hi , i didnot understand what you meant to say !



I mean I don't know much about the bootstrap..

missed `not` 😑

**Comment by rohitroy-github** [comment]
Hey @IAmTamal > I tried fixing this issue. Here's a screenshot from my local file. I made a pull-request regarding the same. 

![check](https://user-images.githubusercontent.com/68563695/178588816-84ae407a-410f-4b18-bc7e-80b5d0141cce.PNG)

**Comment by rohitroy-github** [comment]
Please have a check.
