### ISSUE TITLE
Difference between the pages 🎨

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#216]
### There's  a difference between the pages that i would love to get fixed

The **Clubs Login page** from **image 1**, as you can see this is the design i love, and it looks awesome and minimal.

The **User Login page** on the other hand from **image 2**, has a slight different font, some extra texts. 

**Exlcuding** the colors, i want all to be same ! 

### Image 1

![image](https://user-images.githubusercontent.com/72851613/178402780-cadbd40e-e659-44f9-b549-559c42805aca.png)

### Image 2

![image](https://user-images.githubusercontent.com/72851613/178402810-f9e76395-92f6-4898-a041-8532898a7c5c.png)

**Comment by rohitroy-github** [comment]
Hey @IAmTamal, I was checking this issue out. Do you want the [left-hand-side] images also to be the same or just the font styles ?

**Comment by IAmTamal** [comment]
Hi there sorry for the late replies ! 
Yes it looks perfect to me, thankyou for your contributions !
