### ISSUE TITLE
Login Button 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#223]
### Description

I would like to fix the **Login Button** in **Club Login page**
It gets large and changes colors a bit in **Hover**

---

I want to make all these go away
Stay normal when hovered ! 

### Normal

![image](https://user-images.githubusercontent.com/72851613/179265520-426141a9-0c7c-414a-885f-2d6dfeb6fd3e.png)

### Hover

![image](https://user-images.githubusercontent.com/72851613/179265560-14e25d48-e870-482a-b1d2-c1eb47035066.png)

### Additional information

Location -> `/clubs/login`

**Comment by rohitroy-github** [comment]
Hey @IAmTamal > I tried to fix this issue. Here's a screenshot of the updated 'LOGIN' button. 

![image](https://user-images.githubusercontent.com/68563695/179282151-8dfe00d5-452b-49cc-855b-86b0a9b20614.png)

I didn't remove the bug-CSS classes but commented it out for future reference. Please have a check.

**Comment by rohitroy-github** [comment]
Hey @IAmTamal > I tried to fix this issue. Here's a screenshot of the updated 'LOGIN' button. 

![image](https://user-images.githubusercontent.com/68563695/179282151-8dfe00d5-452b-49cc-855b-86b0a9b20614.png)

I didn't remove the bug-CSS classes but commented it out for future reference. I made a PR, please have a check.
