### ISSUE TITLE
Welcome page fix 🛠

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#224]
### Description

When you login as an **User** in our site, it takes you to **Welcome Page**
As you can see the welcome page is not full screen in the **screenshot**

---

- I need to make it so that it is fullscreen for desktop
- Make sure it looks on Mobile and doesnot breaks ! 

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/179266117-b823c850-a1aa-4bd6-85d7-92f6a21ff26a.png)

**Comment by PratishShrivastava** [comment]
@IAmTamal I would like to work on this.

**Comment by rohitroy-github** [comment]
Hey @IAmTamal, I tried to fix the page dimentions. Its looks like this now. It looks like the way you wanted I guess. 

![image](https://user-images.githubusercontent.com/68563695/179371069-7cc58a33-0daa-44f7-9969-88898c41c21d.png)

I made a PR, please have  a check !

**Comment by rohitroy-github** [comment]
Hey @IAmTamal > I have fixed the page according to the said requirements and made a PR.
