### ISSUE TITLE
Code Enhancements and Minor fixes

### ISSUE THREAD

**Issue by warmachine028** [IAmTamal/Milan#227]
### Description

- Errors from servers previously responded with `success: false`, `exists: true`, `doesNotExists`
- These were then again conditionally checked inside `MilanAPI.js`.
- If we directly send the error message with status code from the server, then there will be no need to conditionally check the status before alerting in client side, reducing code size and help understand the code easily.
- All the backend API routes are written each time repeatedly. This can led to typos in future and long debugging hours.

- This can be reduced by adding a base url and using it in all the routes using formatted string.

- This can also help in easing working with local server and heroku server by just cahanging 1 to 0.

### Screenshots

- ### Previously every response was validated inside `MilanAPI.js`

![bug](https://user-images.githubusercontent.com/75939390/179556848-7d6d2b6d-7912-40b0-9fe9-e85cd66c1b47.png)

- ### Proposed Changes Inside `MilanAPI.js`

![feature](https://user-images.githubusercontent.com/75939390/179556855-32956c5c-075e-41c4-afe1-131ef1172faf.png)

- ### Proposed Changes Inside `User.js`

![feature2](https://user-images.githubusercontent.com/75939390/179558846-1a4360f4-a2b9-4f6b-9abc-54dc1371ae1f.png)

- ### Proposed Addition of Base URLs inside `MilanAPI.js`

![feature](https://user-images.githubusercontent.com/75939390/179560071-4548d9c2-f8ac-4df6-bc4f-34308f402564.png)

### Additional information

- The **register here** link takes user to club register instead of user Register, fixed it.

![invalid link](https://user-images.githubusercontent.com/75939390/179561308-4fe1252c-b659-48c9-8fa2-e57176e745b3.png)

**Comment by IAmTamal** [comment]
Awesome , go for it. 
Since there are alot of changes make sure you avoid any delays in the code !
