### ISSUE TITLE
Implementation of Contact Page - FrontEnd to BackEnd Logic 

### ISSUE THREAD

**Issue by warmachine028** [IAmTamal/Milan#230]
### Description

- Right ContactUs Page is non operational right now in Milan.
- Server side routes are clear but API requests can not be made yet from client side.
- Also server throws error when multiple contact requests are made from same email-id.
- We can solve the error by checking if any previous contact item exist from the email-id.
  - If yes we can replace the details
  - else we can create a new contact item
- The form validation of ContactUs page can be done using a warning toast message.
- The messages received from the server side can be displayed using toast messages instead of basic alert boxes, which will add a more professional look to the UI

### Screenshots

- ### Proposed Changes Inside `User.js` to check if previous contact requests were made from same email address
![User js](https://user-images.githubusercontent.com/75939390/180007270-ce0071e9-2483-456b-acda-1c999f32d500.png)

- ### Proposed Changes in `MilanApi.js`
![milanAPI js](https://user-images.githubusercontent.com/75939390/180010682-eff2f73d-2dd9-40d9-95d6-3b3398bd3547.png)

- ### Toast messages instead of basic alert boxes for better User experience.
![contactUs](https://user-images.githubusercontent.com/75939390/180009050-e8015c8e-70c2-4fa5-8471-fd7117b955b8.gif)

### Additional information

- The toast message feature can be implemented to replace other necessary alert boxes in future. This would enhance the UX.
- This feature can let users can make multiple requests from same email-id without causing errors.

**Comment by IAmTamal** [comment]
Awesome ! 

You can make a PR when done
