### ISSUE TITLE
Toasts - No more alerts !

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#235]
### Using alerts are boring :) 

Currently when we register the alerts from `windows.alert()` looks pretty weird on the go, i would love to change the way it works. 
I would like to use toasts instead of alerts.

- They looks cool
- They makes the alerts much more managable !

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/180629550-dd380e93-b283-47e3-8e49-4404571e97d0.png)

### Something i want ⤵
![image](https://user-images.githubusercontent.com/72851613/180629624-6630ce8c-95d4-4017-8486-6f93207a68e4.png)

### Additional information

I need these changes for all : 

- User Registration
- User Login
- Club Registration
- Clubs Login
- Events Creation

**Comment by yashwanthSRIVAT** [comment]
Hello! I'd like to work on this addition! Please tell which position you want the toasts to pop-up at(Bottom or top? Left middle centre?)

**Comment by warmachine028** [comment]
This would be a great addition. And will improve the UI ❤️

**Comment by IAmTamal** [comment]
> Hello! I'd like to work on this addition! Please tell which position you want the toasts to pop-up at(Bottom or top? Left middle centre?)

I would prefer top-right for the toasts !

**Comment by mohit1607** [comment]
yeah we can use react-toastify library for the toasts. I am ready If you allow me to contribute.

**Comment by IAmTamal** [comment]
@yashwanthSRIVAT  I need this done by tommorow morning. I have some sponser presentations. 
This is a `high` priority.

**Comment by yashwanthSRIVAT** [comment]
@IAmTamal yup. It's almost done😄
