### ISSUE TITLE
UI/UX - Footer for mobile 🎨

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#236]
### Take a look at the footer in mobile screens

The footer looks bad specially because it is cramped up.
- The width of the text can be increased so that it spreads
- The fontsize can be decreased by maybe 1/2 pixels ? 
- Also refer to **Image2**, i want them side by side for **mobiles**

### Image 1

![image](https://user-images.githubusercontent.com/72851613/180631344-9f9c93be-0396-470e-9267-a76837c8f3f4.png)

### Image 2

![image](https://user-images.githubusercontent.com/72851613/180631372-d2127060-0566-43c6-ab3d-b9f60ca34038.png)

**Comment by kristiingco** [comment]
hello! i am interested in this issue :) for image 2, may i clarify which elements you want side by side?

**Comment by IAmTamal** [comment]
> hello! i am interested in this issue :) for image 2, may i clarify which elements you want side by side?

Take the red marker as the line. 

 - The **top** of the red marker ( only social media icons ) will be on the left.
 - The **bottom** of the red marker (only JoinUs, Login, register) will be on the right.

**Comment by kristiingco** [comment]
sorry, i got preoccupied with moving places the last few days! going to get this done within the week! 🙏
