### ISSUE TITLE
UI/UX - Events page breaks 🎨

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#237]
### The event page breaks in mobiles. 

- I need it's responsiveness to be fixed
- keep the image on top, the text on bottom.
- Also make sure it works for tablets

### Image 1

![image](https://user-images.githubusercontent.com/72851613/180631693-ae66f7b6-b0b1-44b1-bea2-7a744fc584df.png)

### Additional information

The route is : `/display/events`

**Comment by kristiingco** [comment]
hello! this is my first time contributing to an open source project and i had forgotten to comment before submitting a PR 😅 my apologies. if it's still all right, feel free to check it out at #239 ! i will be more mindful next time waiting for an assignment.

**Comment by IAmTamal** [comment]
Hi, it's okay ! 
I will look into the PR shortly and will let you know about changes (if any)
