### ISSUE TITLE
Club Login Banner and Navbar Event Link 🔗⚠️

### ISSUE THREAD

**Issue by warmachine028** [IAmTamal/Milan#243]
### Description

- **BUG 1**: After Club login Banner is still visible instead of Login Banner. This issue leads to clubs not being able to see navbar even when logged in.
- **BUG 2**: Events Component crashes the page on clicking. This bug is caused due to anchor tag. Can be fixed by replacing anchor tag by Link component.

![bug](https://user-images.githubusercontent.com/75939390/180752283-e1de200c-f6c8-4a3f-aa01-b60536f9d942.png)
---
- **SOLUTION 1**: Can be fixed by replacing anchor tag by Link component.
- **SOLUTION 2**: Can be fixed by adding check for clubs along with users in sessionStorage in `AuthState` function

### Screenshots

- Proposed Changes in `NavBar.jsx` to fix Page Crash.

![fix 2](https://user-images.githubusercontent.com/75939390/180747966-87641324-830b-4964-9348-e4b3e625898b.png)

- Proposed Changes made in `Home.jsx` to fix banner after club login

![fix 1](https://user-images.githubusercontent.com/75939390/180748413-5b18ed0c-860e-4500-991d-07f76edb5358.png)

### Additional information

- Proposed fix for NavBar UserProfile Icon by Center Aligning in CSS for mobile devices.

![Screenshot 2022-07-25 153121](https://user-images.githubusercontent.com/75939390/180751610-0b189f28-1aee-4e80-b797-5e0f3f336d59.png)

**Comment by IAmTamal** [comment]
The First Bug , `After Club login Banner is still visible instead of Login Banner` is not actually a bug. We had a design for `CLUB LOGIN BANNER` as well, but i lost those files. As a result we just have only one `Login Banner` which shows up after `USER` logs in.

Anyways for now you can use the `LOGIN BANNER` after the clubs log in !
