### ISSUE TITLE
UI/UX - Contact Page 🎨

### ISSUE THREAD

**Issue by tamalCodes** [IAmTamal/Milan#246]
### The contact page looks kind of empty.

**I want to have a minimal yet high quality SVG on the left of the contact page ,it will greatly improve the aesthetics.**

**You can definetly make it responsive SUCH THAT the image is not visible for smaller devices like Mobile Phone and so on , you can create your own minimal image or have one from the references below ⤵**

**[Contact Me Designs 1](https://storyset.com/Contact)**
**[Contact Me Designs 2](https://undraw.co/search)**

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/176711368-0e23197c-c9a5-4a03-87c6-c8a5e093636b.png)

### Additional information

**As i already mentioned , " I want to have a minimal yet high quality SVG on the left of the contact page "** 

![image](https://user-images.githubusercontent.com/72851613/176743028-a5c493f9-22b4-49f5-abe5-61c7acb0dc18.png)

**Take a look at the picture , i want an svg on the left. The references to those picture are there in links.**

### Incase you donot understand how " LEFT " means : 
![image](https://user-images.githubusercontent.com/72851613/176743658-95578abe-3ab6-41e2-a7e5-1237583def5d.png)

**Comment by warmachine028** [comment]
Would like to work on this. Will start working after SDP exam is over.

**Comment by warmachine028** [comment]
![preference](https://user-images.githubusercontent.com/75939390/180859624-bb84ab8e-109c-4420-9553-26c11fdd0675.png)

### Among the above, which one should be preferred for mobile devices?
---

![button size](https://user-images.githubusercontent.com/75939390/180861190-e44368f6-d194-405b-abfd-f059a3e9cd36.png)


![size confirmation](https://user-images.githubusercontent.com/75939390/180860521-a2826f3c-1dad-40ea-b6b7-95e99385d929.png)

### Is this image size and acceptable for desktop devices? 
### Should the **Submit button** be **full width or 30%** ?

**Comment by IAmTamal** [comment]
For mobiles the **RIGHT SIDE** image looks clean and a good fit.

and for desktop, the button with **FULL WIDTH** would look more complete
