### ISSUE TITLE
🚀 Add a banner for clubs ! 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#253]
### We need a banner

If you look at the **Donate Us** page, you will see a banner --> `Image 1`
But the **Clubs** page has none.  --> `Image 2`

**Donate Us Page** : https://milaan.vercel.app/donateus
**Clubs Page** :  https://milaan.vercel.app/display/clubs

Can we have a banner where the clubs page has a similar one too ? 
You can use a good image from internet. 

**Heading**

Clubs and communities ! 

**Sub-heading**

Here are some clubs you can follow, you can attend club events and even get notified about it once you subscribe !

## Image 1 

![image](https://user-images.githubusercontent.com/72851613/184502960-fb6e0013-2dc6-4c9d-8c5e-30db7b2ca556.png)

## Image 2 

![image](https://user-images.githubusercontent.com/72851613/184502974-74956885-01e1-4878-9189-383c7d10d9df.png)

### Additional information

The Design is upto your skills. 

**Image resources :** 

 - https://undraw.co/illustrations
 - https://storyset.com/

**Comment by roei111** [comment]
Hey @IAmTamal, I would like to work on this issue! Can you assign it to me? :)

**Comment by IAmTamal** [comment]
Yes sure, go ahead !
