### ISSUE TITLE
Banner differences 🤔

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#254]
### Different banners looks bad

If you look at the banner in **Donate us Page** you would notice a different font, style as well as color for it.
But if you then look at our **Events Page** you will see it has a different style to it.

I want the **Events** to be same as the **Donate page Banner**

## Links 
 - Donate Page ( https://milaan.vercel.app/donateus)
 - Events Page (https://milaan.vercel.app/display/events)

### Additional information

# Donate Banner 

![image](https://user-images.githubusercontent.com/72851613/184503351-fe2f27d3-6d49-4025-96c7-64457af8d216.png)

# Events Banner

![image](https://user-images.githubusercontent.com/72851613/184503372-c15c4a39-1861-445e-8f4f-17da6b0ad355.png)

**Comment by rohitroy-github** [comment]
Hey @IAmTamal , I tried fixing this issue. Here's how it looks > 

Donate Page > 

![Screenshot (51)](https://user-images.githubusercontent.com/68563695/184531862-b103c054-bd5f-491d-8d79-f4383e3d7f84.png)

Evant Page > 

![Screenshot (52)](https://user-images.githubusercontent.com/68563695/184531868-419d1593-9dcf-46e0-b291-56dc93d2f381.png)

I have made a PR !

**Comment by IAmTamal** [comment]
Awesome, the Banners looks similar !
