### ISSUE TITLE
Contact Page - Mobiles

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#255]
## The contact page needs minor improvements

Take a look at `Image 1`  ,  the mobile version of the page looks a little bit off.
**Improvements**

 - Centered Labels
 - Reduce width for inputs

## Image 1

![image](https://user-images.githubusercontent.com/72851613/184503653-0cc751fe-c5a7-4adf-8c5c-7c3eaa956c94.png)

**Comment by warmachine028** [comment]
Would like to work in it

**Comment by warmachine028** [comment]
![Screenshot_2022-08-14-09-53-41-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75939390/184522416-8b4600b1-59b1-4b09-9a0b-f4332dec2549.jpg)

Would this input width be acceptable?

**Comment by IAmTamal** [comment]
Yes the input width looks perfect !

**Comment by Lydia02** [comment]
Hello, what would you like to change about the contact page, I would like to solve it.

**Comment by IAmTamal** [comment]
> Hello, what would you like to change about the contact page, I would like to solve it.

Another person is already working on the issue, i would request you to wait.

**Comment by warmachine028** [comment]
### 1. I have prepared 3 previews for the Contact page in Mobile view. Which one would be most preferred? 
### 2. Does the input width look as desired or it must be decreased any further (-5px)?  

![info](https://user-images.githubusercontent.com/75939390/184593065-09067aff-f8a0-496a-ad97-0c43f6e805f4.png)

**Comment by IAmTamal** [comment]
I love the 1st one, can we have the placeholders in center ? 
The input looks good.

**Also**, can we remove `Contact us` and say `Reach out to us !`

**Comment by warmachine028** [comment]
Sure! Why not
