### ISSUE TITLE
Reduce width for Footer

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#266]
## Some changes in Footer

 - The footer seems too much wide (in height) for desktops, it would be much more subtle with little bit of reduced height !

 - Also the `report button` could have a slightly red text, blue doesnot looks proper on a black background

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/185749709-865af093-1f88-43a7-8c1e-260f958b4568.png)

**Comment by roei111** [comment]
Hey @IAmTamal, I can work on it.  
About the `report button`, do you want to change only the text color to red? or change both text and border color to red?
