### ISSUE TITLE
Club Registration + Login Page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#269]
### Description

# The club registration + Login  page has bugs
 - When you take a look at `Image1`, you will notice that we donot have placeholder for the form in mobile
 - Make sure there are appropriate placeholders **only** for the mobile ! 
 - Make sure the **marked part** in `Image 2 ` is side by side for the mobiles too ! 

### Screenshots

# Image 1

![image](https://user-images.githubusercontent.com/72851613/186324220-a0059359-aa21-4805-bacd-e2afc3353c57.png)

# Image 2

![image](https://user-images.githubusercontent.com/72851613/186324452-f26a23ec-d13f-4e2a-b5f8-5967f22a44f4.png)

### Additional information

Link : https://milaan.vercel.app/clubs/register
Link : https://milaan.vercel.app/clubs/login

**Comment by Dun-sin** [comment]
Hi, can I work on this?

Also for the register section, do you want it as a label or a placeholder since in desktop mode it's a label and not a placeholder

**Comment by IAmTamal** [comment]
> Hi, can I work on this?
> 
> Also for the register section, do you want it as a label or a placeholder since in desktop mode it's a label and not a placeholder

Hi, sure go ahead ! 
I would love to have **placeholders** for both the Login, registrations in mobile-view ! 

That way it would look clean too
