### ISSUE TITLE
Necessity > [Forgot Password] Link > [Register] Page

### ISSUE THREAD

**Issue by rohitroy-github** [IAmTamal/Milan#273]
### Description

Is the [Forgot Password] link necessary on the [Register] page {https://milaan.vercel.app/user/register} ? 
Is not, it should be removed and kept only on the [Login Page] ! 

### Screenshots

![issue1](https://user-images.githubusercontent.com/68563695/186579953-5670a01d-7598-4e52-9890-bd4e591944d8.PNG)

**Comment by IAmTamal** [comment]
Good call ! 
it should have been only in the Login !

**Comment by IAmTamal** [comment]
> @IAmTamal, the issue is being addressed by @roei111 and the PR looks fine to me. You can merge his PR and unassign me </>

Great !
