### ISSUE TITLE
🛑🛑 HEROKU STOPS WORKING 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#275]
## Suggest a repalcement for Heroku

 - Currently, our project has it's server hosted on **HEROKU** - which has become paid now. No more free services
 - I want to transfer to something else, what can be a good  **FREE** alternative ?

**Comment by roei111** [comment]
On this site there are good free alternatives:  
[https://alternativeto.net/software/heroku/?license=free](url)

**Comment by fk00750** [comment]
Vercel and firebare are one the great option... If you want I will be delighted to help you out 😊

**Comment by IAmTamal** [comment]
Awesome ✅
Gonna check out both !

**Comment by 4k5h1t** [comment]
Elastic beanstalk might be a good fit as well

**Comment by IAmTamal** [comment]
> Elastic beanstalk

Does this have a free tier ? 
For emergency, i moved the server to `vercel` !
