### ISSUE TITLE
🎨 FrontEnd - Enhancing website user experience

### ISSUE THREAD

**Issue by VasuDevrani** [IAmTamal/Milan#278]
### What would you like to share?

Hey there!!
There are a few things that I want to add to improve the UI of the website
- Dark Mode
- Coloring of the footer
- The animations on the Home page keep occurring whenever we scroll through the page as it seems that you've used aos library. They are supposed to happen only once. This needs to be changed

![image](https://user-images.githubusercontent.com/101383635/187079044-1f663dd8-17dd-4f85-bb9d-5f76ae32d1ac.png)

**Comment by IAmTamal** [comment]
These seems a very good call ! 

#### I would recommend a few things : 
 -  Leave the animations as it is.
 - Make sure the fonts and pictures matches with night-mode

**Comment by VasuDevrani** [comment]
Thanks for assigning it to me. Will consider your recommendations. Starting right away

**Comment by IAmTamal** [comment]
Yeah great !

**Comment by IAmTamal** [comment]
Hi @VasuDevrani ,  any updates ?

**Comment by VasuDevrani** [comment]
Oops!! Really sorry.
I got occupied with a couple of hackathons and forgot about this, will complete it by tomorrow if it hasn't been done yet

**Comment by VasuDevrani** [comment]
Hey!!
Why have you added these unused class names like d-flex, text-white, etc?
I don't find them being used.
Should I remove them?

![image](https://user-images.githubusercontent.com/101383635/189480542-a3db0945-4f9b-435a-8d4c-1e62db35dd7a.png)

**Comment by VasuDevrani** [comment]
Hey!
Here, I don't think there's any need of hiding the navbar if the user is unauthenticated.
If you want you can hide some of its fields.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/101383635/189480842-3ad27888-06f4-4b85-bdf3-fc28d19a490c.png">

**Comment by VasuDevrani** [comment]
Sneak peek of dark mode...Alright?


![image](https://user-images.githubusercontent.com/101383635/189482735-44062ae8-aab6-44ca-b6f9-cb56ab66778c.png)

**Comment by IAmTamal** [comment]
> Hey! Here, I don't think there's any need of hiding the navbar if the user is unauthenticated. If you want you can hide some of its fields.
> 
> <img alt="image" width="281" src="https://user-images.githubusercontent.com/101383635/189480842-3ad27888-06f4-4b85-bdf3-fc28d19a490c.png">

The reason why it was made like that is because, we are having an image background in the home page.
So having a navabar on the home page made it look weird

**Comment by VasuDevrani** [comment]
I kept it over the banner image, I guess it looks alright now (ignore the blue color of the links)


<img width="945" alt="image" src="https://user-images.githubusercontent.com/101383635/189483178-5faa22ba-65c9-4b93-af2d-2ad24cc4e214.png">

**Comment by IAmTamal** [comment]
Awesome !

**Comment by 4k5h1t** [comment]
Anything more to be done here ?

**Comment by IAmTamal** [comment]
> Anything more to be done here ?

The thing is they have not made a PR. So if not done by 30th, i'll close the issue as not done.
