### ISSUE TITLE
[DOCS] Tech stack + Broken link

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#280]
### Some changes needed in the README 

- The `Technologies used` section looks  like it lacks several of the tech stacks we use, please update them.
- There's a weird and bad-looking gap too between those horizontal lines, do remove those
- Fixes needed for the wrong broken link in the `Useful Links` section

### Image 1 

![image](https://user-images.githubusercontent.com/72851613/187356614-ed9a58b6-eee9-41aa-9920-70c86416829d.png)

**Comment by Dun-sin** [comment]
hi, can i work on this?

**Comment by IAmTamal** [comment]
> hi, can i work on this?

Sure, go for it !
