### ISSUE TITLE
Optimize the website 🏮

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#282]
### Unused contents slows down the website !

 - Remove all unused `imports` specially in the `.jsx` files.
 - Remove all unused CSS from the `.css` files.
 - Make sure **nothing breaks** in the process !
 - If some `comments` seems important, leave it there.

### Increase optimization in mobiles 

- The website has FCP issues specially for mobile
- You can use tools like : https://pagespeed.web.dev/  for more info
- Make sure **nothing breaks** while fixing

#### Performance in mobile devices 

![image](https://user-images.githubusercontent.com/72851613/187713348-ef303398-299f-4cac-bb8b-8af311ec1f1b.png)

![image](https://user-images.githubusercontent.com/72851613/187714084-7575387b-07d0-4f70-9241-795c57854128.png)

**Comment by SincerelyBrittany** [comment]
Hi, I am interested in picking this issue up. I can:

Remove all unused imports specially in the .jsx files.
Remove all unused CSS from the .css files.
Make sure nothing breaks in the process !
If some comments seems important, leave it there.

However, I dont have much experience in optimization in mobile or  FCP but I can try my best. Is it possible to split this ticket if I am unable to provide optimization in mobile?

**Comment by IAmTamal** [comment]
I'll keep this issue Open, you can work on it, make PR and contribute !

**Comment by SincerelyBrittany** [comment]
Thank you @IAmTamal !
