### ISSUE TITLE
Acessibility - Report Modal 🚀

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#289]
### Report modal changes

 - i would like to make it so that we can easily close the report modal in **Desktop/laptops** with the help of `escape` button from the keyboard
 - Donot remove the **X** from the right side either.

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/188305657-17d06bf0-6422-452e-a18f-6096e2e10d3b.png)

**Comment by roei111** [comment]
Hey @IAmTamal, I would like to work on this issue! Can you assign it to me? :)
