### ISSUE TITLE
User Login Component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#29]
### For proper design : refer to this -> https://github.com/IAmTamal/Milan/pull/18
  Store the code here :  
![image](https://user-images.githubusercontent.com/72851613/152096560-de5015fb-4072-44dd-9166-1aefd6fe697f.png)

Import the page inside `App.jsx` too.

## Design changes : 
- As you can see in here in the mobile version  , i want the input fields to have less width , and be in the center 
![image](https://user-images.githubusercontent.com/72851613/152096947-b3fbdf59-f30e-4759-952a-e5290008ae04.png)

- You can use the same image that is used previously  ,  The image is currently in : 
![image](https://user-images.githubusercontent.com/72851613/152096880-eb68a94b-3f77-4be8-baa5-554842753707.png)

**Comment by soumali28** [comment]
I want to work on this issue under JWOC

**Comment by vivekpatel17** [comment]
I want to work under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

Assigning to @soumali28  , 
Make sure you do follow the **Folder structure** , go through the **Setup guidelines**
Check responsiveness , styles. 
In case of any issue tag me in `#milan` channel.

**Comment by IAmTamal** [comment]
> I want to work under JWOC

check out the other issues !!
