### ISSUE TITLE
[DOCS] Setup guidelines for Backend

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#294]
### Description

As of now there is no **setup guidelines for backend**

- Please add a new file called `BackendSetup.md` in the **rules** directory
- Link it to `Readme.md` too
- Change the `Setup.md` to `FrontendSetup.md` in the **rules** directory

**Comment by vaishnav-sh** [comment]
Hey @IAmTamal, I can take this up. Please assign this issue to me
