### ISSUE TITLE
🎨 FRONTEND - User Registration page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#299]
### Description

 - Take a look at the page, we have alot of placeholders. 
 - Remove the placeholders **only for desktop**
 - Let the `first name` and `last name` stay as it is 
 

## This is what i was talking about 

![image](https://user-images.githubusercontent.com/72851613/190573055-55d97bec-5376-4cce-b3a4-0ca46668de42.png)

**Comment by roei111** [comment]
Hi @IAmTamal, can you assign me?

**Comment by IAmTamal** [comment]
Sure, go ahead !
