### ISSUE TITLE
User Register component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#30]
# I want to have a react **User Registration** component for the user. 
### For proper design : refer to this -> https://github.com/IAmTamal/Milan/pull/18
As you can see the desgin above is for Login page , but i would like to have the same design for **register page**.
- First name
- Last name
- Email
- Password
- Location Pincode

### Store the code here :  
![image](https://user-images.githubusercontent.com/72851613/152097384-edafeb26-cf99-4387-aed8-dcd29499132d.png)

---

## Design changes : 
- As you can see in here in the mobile version  , i want the input fields to have less width , and be in the center 
![image](https://user-images.githubusercontent.com/72851613/152096947-b3fbdf59-f30e-4759-952a-e5290008ae04.png)

- You can use the same image that is used previously  ,  The image is currently in : 
![image](https://user-images.githubusercontent.com/72851613/152096880-eb68a94b-3f77-4be8-baa5-554842753707.png)

**Comment by mridul4101** [comment]
I would like to contribute to this. So if it is available will you please assign it?

**Comment by IAmTamal** [comment]
> I would like to contribute to this. So if it is available will you please assign it?

Assiging to you , 
Make sure you read the **Setup guidelines , maintain proper folder structure.**
Make sure the page is responsive enough.
For any issues please tag me in **#milan** channel
