### ISSUE TITLE
🎨 FRONTEND - The Navbar Logo

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#300]
### Description

 - The navbar logo has an `alt-text` which reads `lol`, you'd  need to change it
 - This is a great issue for beginners ! 

## This is the logo : 

![image](https://user-images.githubusercontent.com/72851613/190573795-3b3f7278-7d01-412a-8014-6ef83597adad.png)

**Comment by Kevin11-code** [comment]
What should the 'alt-text' be changed to?

**Comment by IAmTamal** [comment]
> What should the 'alt-text' be changed to?

It needs to be changed to like : `Milan-logo`
