### ISSUE TITLE
🎨 FRONTEND - 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#301]
### Description

 - Curently the Club register page has all placeholders for desktop 
 -  Make sure for **DESKTOPS** - we have just the labels and no placeholders
 - You can follow the design at [User registration Page](https://milaan.vercel.app/user/register)
 - Make sure the styles are similar ! 

## This is what i was talking about 

![image](https://user-images.githubusercontent.com/72851613/190574672-ab04bc38-d8ba-4362-8cfa-7169d406e52a.png)

**Comment by ishaanbedi** [comment]
Hey! Would love to contribute. Can you please assign this to me>

**Comment by developer-irfan** [comment]
@IAmTamal i would like to work on this.

**Comment by IAmTamal** [comment]
> Hey! Would love to contribute. Can you please assign this to me>

Sure, go ahead !

**Comment by ishaanbedi** [comment]
Hi! I've raised a pr for the same!
Please have a look.
