### ISSUE TITLE
Clubs Register Component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#31]
### Read [Setup Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md) for proper **folder structure**

---

## Design changes 
- You need to use a different image than the one that is used for the **TEMPORARY** Login page.
-  You need to have **Club Name , Club ID ,Password,  Club Location , Club Description , Club Logo**
- Make sure the page is fully responsive and has **IMPRESSIVE UI**
- Use this File 
![image](https://user-images.githubusercontent.com/72851613/152098945-5fb35614-526e-4ae5-8aad-51403a1833c3.png)
- Import the file with **`/clubs/register`** route in `App.jsx` 
![image](https://user-images.githubusercontent.com/72851613/152099102-a141e621-a435-474e-8696-4c1cfecc4df7.png)

**Comment by Priiyaa** [comment]
I would like to work on this issue!

**Comment by IAmTamal** [comment]
> I would like to work on this issue!

Are you a participant of JWOC ?

**Comment by Priiyaa** [comment]
yes

**Comment by IAmTamal** [comment]
> yes

Okay assigning this to you, @Priiyaa
