### ISSUE TITLE
Test issue 1

### ISSUE THREAD

**Issue by Noelle-San** [IAmTamal/Milan#310]

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: :rocket:<p>If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Discord</a> chat and our <a href="http://github.eddiehub.org">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.</p>
