### ISSUE TITLE
Home Page Jumbotron Grammar Correction

### ISSUE THREAD

**Issue by Scriptkidd98** [IAmTamal/Milan#313]
### What would you like to share?

I changed "Continue as an User", which is not grammatically correct, to "Continue as a User", which is
<img width="516" alt="Screenshot 2022-09-20 at 11 07 55" src="https://user-images.githubusercontent.com/43118340/191230935-dce01a53-9fef-4b27-869f-f631685223de.png">

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>
