### ISSUE TITLE
🎨 Frontend - Issue in report Modal in footer

### ISSUE THREAD

**Issue by vivekrawat** [IAmTamal/Milan#315]
### Description

when modal is closed or report is submitted the data inside the modal is not cleared.

### Screenshots

![Screenshot from 2022-09-21 14-31-54](https://user-images.githubusercontent.com/42130066/191467891-7548b2d8-3e0a-4dba-8665-fece04452a19.png)
this the screenshot of modal after submission.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>
