### ISSUE TITLE
Clubs Login Component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#32]
### Read [Setup Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md) for proper **folder structure**

---

## Design changes 
- You need to use a different image than the one that is used for the **TEMPORARY** Login page.
-  You need to have **Club ID , Password** in the page
- Make sure the page is fully responsive and has **IMPRESSIVE UI**
- Use this File 
![image](https://user-images.githubusercontent.com/72851613/152100044-0783b567-de44-4436-b4b0-1d39f08b9f4f.png)
- Import the file with **`/clubs/login`** route in `App.jsx` 
![image](https://user-images.githubusercontent.com/72851613/152100127-c81c72b0-2816-49fe-a773-885ed3df04d5.png)

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
Assigning this to @KushalGhosh9899  , make sure you follow the **GUIDELINES** for proper **FOLDER STRUCTURE**
If you have any queries ask in #milan channel. Tag me.
