### ISSUE TITLE
[DOCS] Readme + License changes 🛠

### ISSUE THREAD

**Issue by krupalitrivedi** [IAmTamal/Milan#320]
### Description

Hello! 

I would like to help with the ReadMe documentation for the Milan project by making changes in the ReadMe for grammar and sentence formation as well as would like to brainstorm for anything that can be added that can make the project better along with linking the License in the file as well!

Would enjoy if you can assign this issue to me for hacktoberfest!

Thank you!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
@krupalitrivedi , go ahead !
