### ISSUE TITLE
[FEATURE] <description>Continue Buttons Style Improvement

### ISSUE THREAD

**Issue by Shivyoddha** [IAmTamal/Milan#321]
### Description

The Continue buttons on the home page of Milan webpage is not styled yet and kept primary so CSS features may be added to it.
`good first issue` 

### Screenshots

![image](https://user-images.githubusercontent.com/97729353/193262491-1d09c7ce-51b4-4bc8-a17a-8474892022a9.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by Shivyoddha** [comment]
Hi @IAmTamal ,
Could you please assign me this issue ?

**Comment by IAmTamal** [comment]
Hi there, the issue won't add any real value/changes. We 'd prefer the button as it is !
