### ISSUE TITLE
Navlinks doesn't change on mouse hover

### ISSUE THREAD

**Issue by imyoungsparda** [IAmTamal/Milan#322]
### Description

A slight colour in change on hovering the nav links would make it more appealing and attractive.

### Screenshots

![image](https://user-images.githubusercontent.com/112796825/193328882-ff2b9c0d-175b-44bd-8177-e2859ce5606c.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
This looks like a good addition, go ahead @imyoungsparda  !

**Comment by ManavMalhotra** [comment]
I can do this you can assign this task to me

**Comment by IAmTamal** [comment]
> I can do this you can assign this task to me

Someone else is already working on the task as you can see.
