### ISSUE TITLE
Future event button

### ISSUE THREAD

**Issue by AbhishekTiwari23** [IAmTamal/Milan#328]
### Description

I want to add a button on the event page. Whenever a user clicks on that, A film will open up and ask for the email and name of the user so that he gets notified for the next upcoming event.

I also like to add a CSS effect on the event card. Whenever a user hovers over, the card gets flipped, and a short description of the event is available, which will become more attractive.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by AbhishekTiwari23** [comment]
If u find it relevant, please add it to hacktober fest

**Comment by IAmTamal** [comment]
Hello @AbhishekTiwari23 , the feature you talked about is useful - but i want it to be more customized. 
Here's something that you can do : 

- We already have `Attend Event` button on each card
- Whenever a user clicks on it, Open a new page

### How to build a new page ? 

- Make a new folder in the `pages` folder
- Name the folder as `events`
- Make a new file called `AttendEvent.jsx` which opens as `display/events/attendevent`

### What to show in the page ?

- You can use react-context api / props / Links to pass the club's data to the page.
- Inside the page to the left side display the picture we have used in those cards.
- On the right side, we can have all the details of the event.
- Below that we can have an input field for the `emailID` of the user and an `attend` button.
- After filling the input and clicking on the button, the page should be closed !

### Note 

- It will awesome if you could do it.
- If not i will be assiging this to someone else

Regards,
Tamal

**Comment by AbhishekTiwari23** [comment]
> Hello @AbhishekTiwari23 , the feature you talked about is useful - but i want it to be more customized. Here's something that you can do :
> 
> * We already have `Attend Event` button on each card
> * Whenever a user clicks on it, Open a new page
> 
> ### How to build a new page ?
> * Make a new folder in the `pages` folder
> * Name the folder as `events`
> * Make a new file called `AttendEvent.jsx` which opens as `display/events/attendevent`
> 
> ### What to show in the page ?
> * You can use react-context api / props / Links to pass the club's data to the page.
> * Inside the page to the left side display the picture we have used in those cards.
> * On the right side, we can have all the details of the event.
> * Below that we can have an input field for the `emailID` of the user and an `attend` button.
> * After filling the input and clicking on the button, the page should be closed !
> 
> ### Note
> * It will awesome if you could do it.
> * If not i will be assiging this to someone else
> 
> Regards, Tamal

I am eager to contribute and will give my best definitely. But I just want to know whether you have any time bonding issues or not because it will take a little time, But I can make sure that I will do my best for this. Hope u don't mind @IAmTamal. What about hacktoberfest tag (just kidding)

**Comment by AbhishekTiwari23** [comment]
Please assign me. I am ready with my tools

**Comment by IAmTamal** [comment]
> Please assign me. I am ready with my tools

There's no time-bonding as such but try and do it within 3-4 days ! 

- Make sure the fonts are similar to what we have used
- Make sure the styles are minimal
- Make separate `.css` files and use proper names.

**Comment by AbhishekTiwari23** [comment]
This is more than enough. Thanks alot

**Comment by AbhishekTiwari23** [comment]
Hello @IAmTamal, I started working on the issue, but I found that Hacktoberfesttag is missing in this issue. I request you to please put it there.

**Comment by IAmTamal** [comment]
> Hello @IAmTamal, I started working on the issue, but I found that Hacktoberfesttag is missing in this issue. I request you to please put it there.

Hello @AbhishekTiwari23 , you donot need `Hacktoberfest` tag in issues. You need it only in PR / Repo topics. 
Anyways just for the sake of putting it, i'll add it.

**Comment by IAmTamal** [comment]
@AbhishekTiwari23 Any updates ? 
It's been a long time.

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 Any updates? It's been a long time.

Hello @IAmTamal, Actually, before jumping over your project, I started learning to react, I am thankful for this project which makes my understanding of react.js clear. 
Current status - made the "attend event" button responsive (means now whenever a user clicks on it , he will be landed to a new page). 
              - Added Attendevent page in the page folder, 
              - Added header of this page as same as the other pages.

Currently working on the page.

I apologise for being late and not full filling my words, actually I was working on Layer5.io PR, and thankfully it got merged. As I am a new bee in open source, I wasted my lot of time in searching good reo and learning the new things that are required for that particular project, similarly like in your project I am making my rect understanding clear.

I f you want a confirmation screen recording or a pr then please let me know. Thanks for you support.

**Comment by IAmTamal** [comment]
Yeah just wanted a head's up - since this is a feature we wouldn't wait too long ! 
Take your time but please try and do the mentioned stuffs within the next 2-3 days 🚀
