### ISSUE TITLE
Accessibility : Highlighting errors in contact form 

### ISSUE THREAD

**Issue by MANUSRAO** [IAmTamal/Milan#329]
### Description

- [x] I have read the contributors guidelines .
- [x] I have read the code of conduct.
<hr>
In the contact us page, the toastify notification just mentions "Resolve Errors in the Form", but it doesn't highlight what are the errors in the form.  It would be helpful to the user if we can notify what are the errors in the form.
My approach to the problem:
* We can highlight the form entries which have incorrect type of information along with a single toastify notification.

### Screenshots

![Screenshot 2022-10-01 144438](https://user-images.githubusercontent.com/67941652/193402328-c9de77dd-cfb2-4cc4-ad4a-3d9dbf97866c.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by MANUSRAO** [comment]
If you feel the issue to be worth pursuing, can you please assign me the issue ? Also if possible can you add the hacktoberfest tag?

**Comment by IAmTamal** [comment]
Go for it !

**Comment by MANUSRAO** [comment]
Hi @IAmTamal thanks for assigning !! I have fixed the issue with three approaches:
1. Adding a toastify notification for each incorrect input.
2. Adding a  `<p>` element describing the issue in the form. with default toastify warn notification.
3.  Adding both the above effects for the user.
<hr>

## Screenshots:
1. Using first approach:
<img src="https://user-images.githubusercontent.com/67941652/193439592-c4fad279-c1a3-42d0-aa3c-c98f80e3408d.png" width="400" height="400" />
2. Using second approach:
<img src="https://user-images.githubusercontent.com/67941652/193440336-13470b59-f69e-47c6-8190-3e9943231428.png" width="400" height="400" />
3. Using Third Approcah:
<img src="https://user-images.githubusercontent.com/67941652/193440197-c6c6597d-6b1b-40ff-b3ed-0d2eac89e8e2.png" width="400" height="400" />
I like the second approcah beacuse it notifies the user what errors he made in the form along with one effective notification. Please tell me which approach should I implement while making PR.

**Comment by IAmTamal** [comment]
Hello there 👋 

I liked the way stuffs works out, however i would recommend something : 

## Case 1 : 

**If someone fills half/none of the form, then just display `Fill out all the fields before sending`**
![image](https://user-images.githubusercontent.com/72851613/193440518-6925fc92-4fce-421e-be63-31955cba0d52.png)

## Case 2 : 

**If someone fills in all the field yet gives an invalid email, tell them to `Please provide a correct email`**
![image](https://user-images.githubusercontent.com/72851613/193440583-4942c542-9557-42e1-af15-b7fba89d9e30.png)

**Comment by MANUSRAO** [comment]
Thanks for the speedy reply!! I have few doubts. So we don't need any instructions to be displayed on the page but only through toastify notification?  And also the notification should be condition based on the errors?

**Comment by IAmTamal** [comment]
> Thanks for the speedy reply!! I have few doubts. So we don't need any instructions to be displayed on the page but only through toastify notification? And also the notification should be condition based on the errors?

Hmm i think providing too much details is not of use, like if i have everything filled, but missed the `last name`  - it'll be still okay to say the user to `Please fill out all the fields`

So we have only 2 conditions  : 

- If any field is empty say `Please fill out all the fields` via toast !
- If all fields are filled but email is invalid say `Please provide a correct email`

**Comment by MANUSRAO** [comment]
So I have implemented your suggestion. If any detail is missing except the email, then user gets `Please fill out all the fields` warn via toast and if the user fills all details correctly except the email then he gets `Please provide a correct email` warn via toast. So, I have not added any extra code in the page.
<hr>

## Screenshots:
1. User has not entered one or more detail:
![Screenshot 2022-10-02 132424](https://user-images.githubusercontent.com/67941652/193443974-c3ae6fd2-fa32-4d17-8d85-e52d7d575bd1.png)
2. User has entered everything correctly except the email:
![Screenshot 2022-10-02 132529](https://user-images.githubusercontent.com/67941652/193443972-bbfaebb6-226f-48f3-822c-f6ff65ddc405.png)

**Comment by IAmTamal** [comment]
Looks good, do make a PR once ready !

**Comment by MANUSRAO** [comment]
Cool! Will Make a PR soon!

**Comment by MANUSRAO** [comment]
Hi @IAmTamal what extra changes do I need to make in my PR?
