### ISSUE TITLE
Clubs Page component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#33]
###  Read [Setup Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md) for proper **folder structure** ⚠

---

## FIles and Folder 
- Inside of the `src>components` folder make a new file : `SingleClub.jsx`
![image](https://user-images.githubusercontent.com/72851613/152109317-3498eaab-e6de-41bb-9e81-c8721bf63c94.png)

- The `SingleClub.jsx` will have just  1 card , with Image,  Title , description
- These data will be passed as `props` to the component inside `ClubPage.jsx`
- This `SingleClub.jsx` will be called in `display > ClubsPage.jsx`
![image](https://user-images.githubusercontent.com/72851613/152110474-579f8601-7b1f-4405-93b5-ff792be4d926.png)

- The data is present in `CLUB_DATA.json`
![image](https://user-images.githubusercontent.com/72851613/152110588-039ebaf8-5670-4c22-9d53-578f268fceda.png)

 - You need to **store this data in a useState** and then **MAP the SingleClub** component , so that the **`SingleClub.jsx`** is displayed multiple times. 

Once done , uncomment the route in `App.jsx`
![image](https://user-images.githubusercontent.com/72851613/152111013-a9f7b46a-7aa9-49a3-9d89-6744afd8f08a.png)

**Comment by dakshgupta2002** [comment]
Interested to work on this under JWoC!

**Comment by IAmTamal** [comment]
Assigning this to you , make sure you take a proper look at the guidelines and communicate with me on the Dc server for any issues.
