### ISSUE TITLE
Making a Contact US section at Footer [OTHER]

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [IAmTamal/Milan#330]
### What would you like to share?

![image](https://user-images.githubusercontent.com/96011814/193405206-b66a1a10-246f-4b0b-8436-c7ec83f166d3.png)
This looks a little weird, should give them a better look

By Taking inspiration from this
![image](https://user-images.githubusercontent.com/96011814/193405473-fc38268d-08a8-40eb-87e0-c49159757d07.png)
Replacing location details with social icons

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hello there, a good spot !
But i'd like some more customization 

- Instead of what you thought of adding, make a small button in the footer, beside the socials
- On clicking the buttons re-direct them to the `/contact` path
- Remove the `contact` option from the navbar !

**Comment by MANUSRAO** [comment]
Hi @IAmTamal since @Aman-Singh-Kushwaha has not replied in 3 days, can you assign this issue to me, I can work on it.

**Comment by Aman-Singh-Kushwaha** [comment]
Go for it @MANUSRAO

**Comment by omagr** [comment]
@Aman-Singh-Kushwaha can i work on it as well? ig you assign it to mansurao?

**Comment by MANUSRAO** [comment]
@omagr I have already started working on this issue.

**Comment by MANUSRAO** [comment]
@IAmTamal I have added a button at the footer for contact. I have attached the screenshot please mention any changes required.
![Screenshot 2022-10-05 114529](https://user-images.githubusercontent.com/67941652/193993788-ae466439-01ac-4276-b9d2-64b5a303e386.png)

**Comment by IAmTamal** [comment]
Let's make a PR that way i can visit the site and cheeck out the changes !

**Comment by MANUSRAO** [comment]
Hi @IAmTamal I have made a PR, please review and give any feedback if changes are required.
