### ISSUE TITLE
Two repeated input elements for First Name in the contact us mobile version.

### ISSUE THREAD

**Issue by MANUSRAO** [IAmTamal/Milan#333]
### Description

![WhatsApp Image 2022-10-02 at 11 35 46 AM](https://user-images.githubusercontent.com/67941652/193440461-05aaa289-bbde-405e-8420-e7fe0d42e0fb.jpeg)
You can verify the same by visiting https://milaan.vercel.app/contact from your mobile phone. I can work on this issue.
Can you please assign this issue to me? If you find this relevant can you add hacktoberfest tag?

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
A great spot ! 
Feel free to get started with the work. 

Also `hacktoberfest` tag doesnot matter on the issue/pr. The repo only needs it 😉

**Comment by MANUSRAO** [comment]
Hi @IAmTamal I checked around the codebase and found out the `<input>` element is assigned a `class` of `userreg_mob_firstname`  it is used in `UserRegister.jsx` and `ContactUs.jsx` pages. For `UserRegister.jsx` we have given the `<input>` element a styling using the same class `userreg_mob_firstname`. It is hidden in Deskop-width displays and only made visible in Mobile-width displays. But we have not made the same provisions for `ContactUs.jsx`. 
So now do you want me to add styling to hid one `<input>` in desktop and display the other in mobile? Or do you want me to remove the extra element from the code itself?

**Comment by IAmTamal** [comment]
@MANUSRAO 

Here's the thing, in desktop we actually want auto-focus for the first name
![image](https://user-images.githubusercontent.com/72851613/193461701-7ef1b46e-27cf-4e75-b6b9-4231f97ef300.png)

But in mobiles we donot want the auto focus, however there's still auto-focus
![image](https://user-images.githubusercontent.com/72851613/193461785-d9aeb983-7ca2-4fa7-8d40-99e5af170532.png)


You can do whatever you want, but just make sure you : 
 - Save the input in the useState
 - Use the same styles as there is in the deployed site
 - You can also make a new class in the `Contact.css` !

**Comment by MANUSRAO** [comment]
Thanks for the input! I will get back to you soon.
