### ISSUE TITLE
[Backend] A tagline for clubs 🛠

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#334]
### Description

So we will be needing a brand new clubs tagline !

## Here's how you can do it 

- We already have fields for ` email,
            password,
            name,
            address,
            pincode,
            description` in the backend
- Add a new field **before description** called **tagline** in the `ClubsSchema.js` file
- Make sure we are able to write a sentence during club registration and store it to the database !

## Important ⚠ 

You just need to make the backend for it !

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by warmachine028** [comment]
I would like to work on this issue

**Comment by IAmTamal** [comment]
> I would like to work on this issue

Sure, go ahead !
