### ISSUE TITLE
Donate us - auth 🛠

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#335]
## Authentication issue

- Make sure if we are not logged in we shouldnot be able to donate
- When we try to visit the `/donateus` it should say to login first 
- You can brainstrom your own design !

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/193443475-c26d7783-2927-4e7e-8a1c-3e20567a1d55.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by en1gm479** [comment]
I would like to conttribute to this issue.
Please assign this to me @IAmTamal

**Comment by IAmTamal** [comment]
@en1gm479 , go for it !

**Comment by IAmTamal** [comment]
@en1gm479 Any updates ? 
Make sure you do it within next 1-2 days **at max**

**Comment by en1gm479** [comment]
Sorry @IAmTamal I'm not able to contribute as I'm stuck somewhere else. Please re-assign it to someone.

**Comment by rohitroy-github** [comment]
Hey @IAmTamal | I wanna try this out. Can it be assigned to me ?

**Comment by rohitroy-github** [comment]
@IAmTamal | I have made a PR. Have a check at your end once.
