### ISSUE TITLE
[DOCS] Enhance Docs & fix the broken links

### ISSUE THREAD

**Issue by arpitv970** [IAmTamal/Milan#337]
### Description

There is room for improving docs, by including some points such as:
- Make sure docs are precise enough for non-coders
- Fix the broken link for Setup Guide at `CONTRIBUTING.md`

I would like to contribute to improving the docs that would help new contributors. It would be great if the maintainer(s) can assign this issue to me for **hacktoberfest**.

Thank you!!

### Screenshots

- The broken link at [CONTRIBUTING](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
> ![Setup-guideline-link-failed](https://user-images.githubusercontent.com/73063553/193454619-52ba3f20-8de1-4a91-9c98-e2b1081f4ffa.png)
- Here is the output of click over it
> ![S](https://user-images.githubusercontent.com/73063553/193454779-00f3a0ed-d15b-443b-a711-2b7d49445f58.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>
