### ISSUE TITLE
[FEATURE] Dockerize the project

### ISSUE THREAD

**Issue by harshit0571** [IAmTamal/Milan#343]
### Description

Hey!
it would be great if the repo is containerized using docker.
this would make the project easier to setup.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hello @harshit0571 , you think you can make it ? 

If yes, go for it. In the PR make sure provide screenshots that you are able to set it up with Docker

**Comment by IAmTamal** [comment]
> Hello @harshit0571 , you think you can make it ?
> 
> If yes, let me know , i will assign this to you. 
In the PR make sure provide screenshots that you are able to set it up with Docker

**Comment by harshit0571** [comment]
yes i can do it

**Comment by harshit0571** [comment]
please tell me node version you are using 
use `node -v`

**Comment by IAmTamal** [comment]
> please tell me node version you are using use `node -v`

v16.17.0
