### ISSUE TITLE
Not Added Copyright notice at the bottom of the website

### ISSUE THREAD

**Issue by RishitaGangwal** [IAmTamal/Milan#344]
### Description

A website — graphics, content, visual elements — is copyrighted at the time of development. So putting the copyright notice on the bottom of a site states that the material displayed is not to be used without permission of the owner. I would like to add copyright notice at the bottom of a site.

Hey, @IAmTamal Please assign me with this issue.

Thanks!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>
