### ISSUE TITLE
Feature: Adding Text Area Instead Of Text Fields In Address Section

### ISSUE THREAD

**Issue by RishitaGangwal** [IAmTamal/Milan#345]
### Description

![address](https://user-images.githubusercontent.com/88449534/193520078-2b6438e0-5e98-469c-8add-cc5b54b02d00.jpeg)

The Address section must be a "text area" instead of a text field. And also its a tradition of mentioning Address in Text Area so that users can specify their address more accurately.

Hey, @IAmTamal Please assign me with this issue.

Thanks!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by RishitaGangwal** [comment]
Thankyou!

**Comment by RishitaGangwal** [comment]
Thankyou so much ❤️
