### ISSUE TITLE
Links not Working

### ISSUE THREAD

**Issue by DhruvRathi2001** [IAmTamal/Milan#346]
### Description

Here the links to Twitter and Facebook are not Working and are redirecting us to the same page.

![links](https://user-images.githubusercontent.com/94394117/193532367-8422f8b2-c9d3-4fe9-9697-2e64a9732e60.png)

Hey @IAmTamal  can you please assign this issue to me, I would love to fix it for HACKTOBERFEST.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
A good issue , i want you do the following changes in that case  : 

 - Link Twitter to https://twitter.com/mrTamall
 - Remove Facebook and GitHub which links to this repo
 - Change their colors to `#9ac2fe`

**Comment by Himanshi2511** [comment]
Hey @IAmTamal  can you assign to me also?

**Comment by DhruvRathi2001** [comment]
> Hey @IAmTamal can you assign to me also?

@Himanshi2511 can u please find some other issues  I have already made corrections and sent PR
