### ISSUE TITLE
Dates are not Mentioned

### ISSUE THREAD

**Issue by DhruvRathi2001** [IAmTamal/Milan#350]
### Description

In the Event Section , the Time for 'HOLA PETS' event is not mentioned which can confuse users is to when to attend event since there is one more event at same place like - one is at 11a.m

### Screenshots

Time is not mentioned for 'HOLA PETS' event : 

![milan_time](https://user-images.githubusercontent.com/94394117/193582266-49e5c0fb-870a-46b6-af7f-b9713f1884ca.png)

Hey @IAmTamal  can you please assign this issue to me, I would love to fix this for HACKTOBERFEST

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by DhruvRathi2001** [comment]
@IAmTamal  The one who have registered can create his/her own event and mention the time, date etc.
So actually it is not in my hands to  fix it.

**Comment by IAmTamal** [comment]
> @IAmTamal The one who have registered can create his/her own event and mention the time, date etc. So actually it is not in my hands to fix it.

Hmm so what we can do is , after logging in as a club we visit `/clubs/createevent` and in there we have a field which says `When will the event take place`

- Let us remove that field and add 2 other fields instead !
- One which says `Date of the event`
- Another which says `Time of the event (24 Hours format, IST)`
- Make sure the values are getting stored in Usestate and are ready to go to Backend.
- You **donot need to work on the backend**

![image](https://user-images.githubusercontent.com/72851613/193647693-e87a29da-ea10-496a-8ee2-23ea996c7d61.png)
