### ISSUE TITLE
[DOCS] Add Docker setup instruction in the readme file

### ISSUE THREAD

**Issue by harshit0571** [IAmTamal/Milan#351]
### Description

i think we can can add both setup with docker in it.

**Comment by IAmTamal** [comment]
Looks like a good point. 

 - Make a new file inside the `rules` folder
 - Make sure you Write about it in **extreme details**
 - Make sure you add link to that file in the readme as `🛠 SETTING UP THE APP WITH DOCKER`

**Comment by harshit0571** [comment]
sure
