### ISSUE TITLE
[Frontend] A tagline for clubs 🏷️

### ISSUE THREAD

**Issue by warmachine028** [IAmTamal/Milan#352]
### Description

- As you mentioned in #334 that there must be a tagLine field for Clubs
- That was successfully implemented in backend but it must also be implemented in the frontEnd.
- There must be an input field along with other input fields to input the tagLine for Clubs.
- I would like to take up this issue under hacktoberfest

### Screenshots

![club input](https://user-images.githubusercontent.com/75939390/193600097-3d385a56-68b7-4c11-bd83-865cdc9bd3e0.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by warmachine028** [comment]
> Go for it @warmachine028
> 
> * Make sure it's not large, have a limit like maybe 180 characters

Great Idea! Will keep that in mind

**Comment by warmachine028** [comment]
- Shold the input field be a text Area or just a normal 1 Line input, confused because of the word TagLine, but also 180 characters is 4 Lines.

![club input](https://user-images.githubusercontent.com/75939390/193616343-1983d1ff-95b2-4ad5-81b1-0394085da533.png)

**Comment by IAmTamal** [comment]
Hmm, we can make it like 50 characters then, like someone would say " A Club where gaming unites people"

- The placement is correct
- Add brackets beside the label which says ( Limit : 50 characters)
