### ISSUE TITLE
Add footer to every page, also there is a bug in contact page

### ISSUE THREAD

**Issue by snehafarkya** [IAmTamal/Milan#354]
Hey! I would like to add footer on every page for better user experience. Also, there is a bug in contact us page where **first name** field is repeated. 

Here is the screenshot 👇
![Screenshot_20221003-224831~2](https://user-images.githubusercontent.com/63949465/193640109-ee35cdc0-5471-41cd-b1b5-b7155f051eaa.png)

Assign this issue to me @IAmTamal  under hactobesfest

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by Himanshi2511** [comment]
Hey @IAmTamal can you assign this to me?

**Comment by IAmTamal** [comment]
@snehafarkya No  need to fix the bug for contact page, someone else is already working on that.
