### ISSUE TITLE
Hover Feature to Report Button

### ISSUE THREAD

**Issue by DhruvRathi2001** [IAmTamal/Milan#360]
### Description

Report Button does not have any hover feature which actually makes it quite simple.
And since its a 'REPORT BUTTON' , it should definitely have some good hover feature which makes USER INTERFACE more Standard and Attractive.

### Screenshots

This Report Button does not have any Hover Feature : 

![milan_hover](https://user-images.githubusercontent.com/94394117/193736769-1c1d660d-d747-4ba6-8abb-872f5b0dac83.png)

Hey @IAmTamal  please review this issue , I would love to fix it.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Go for it @DhruvRathi2001 

 - Remove the red border from the report button and color the button with `#9ac2fe`
 - Make sure the hover looks good !
 - Further changes would be suggested after PR !
