### ISSUE TITLE
Adding Sample Event in Display Events Page

### ISSUE THREAD

**Issue by MANUSRAO** [IAmTamal/Milan#361]
### Description

At present the Event's page does not have a sample card showing correct details, instead sample events have random text. We can instead showcase a sample card with correct formatting.

### Screenshots

![Screenshot 2022-10-04 113613](https://user-images.githubusercontent.com/67941652/193746420-5b18520e-8306-4ed1-8b30-f9a05889ad53.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hello @MANUSRAO  - The events card are fetched from the Database directly. 
There is no purpose of showing a sample event, because only the real events will be shown and users can then attend !

**We will moderate the Database so that events with bad data are not shown !**
