### ISSUE TITLE
Footer Links don't work in certain pages.

### ISSUE THREAD

**Issue by MANUSRAO** [IAmTamal/Milan#362]
### Description

When we are in [Club Page](https://milaan.vercel.app/display/clubs) , [Events Page](https://milaan.vercel.app/display/events), [About Us Page](https://milaan.vercel.app/about-us) and [Contact Page](https://milaan.vercel.app/contact), the footer links to Login and Register do not work. It's due to `href` being assigned wrong relative paths. And also both `login` and `register` point to same `register` links.

### Screenshots

![Screenshot 2022-10-04 114617](https://user-images.githubusercontent.com/67941652/193747847-e8af7741-9c02-46ee-9f5f-d04722ae9b97.png)
![Screenshot 2022-10-04 114743](https://user-images.githubusercontent.com/67941652/193748057-dd789f77-e6a2-4bfd-9b0f-1ba5e9000b85.png)
![Screenshot 2022-10-04 114728](https://user-images.githubusercontent.com/67941652/193748061-0993b6fa-fe74-43db-aa6d-bdb605f821ab.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
@MANUSRAO go for it 

- Change it so that both of the Login and Register points to User Login and Register
