### ISSUE TITLE
[FEATURE] Improvement in Footer

### ISSUE THREAD

**Issue by arpitv970** [IAmTamal/Milan#366]
### Description

There is much room for improvement in Footer but I found some of the following:
- Improve the `Report` button CSS
- Need to increase the size of social link icons for better visibility

### Screenshots

![improve-footer](https://user-images.githubusercontent.com/73063553/193796756-cd2ad65d-6908-4b46-bb1b-efded4f3633e.png)

### Additional information

It would be great if there is an improvement in the color scheme of the Footer.

Thank you!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
A great spot, however we already have a new Report button looks. 
Social link size will be increased in another issue where we are adding contact link ! 

Thanks for raising the issue, but closing it since someone else is already working on it !
