### ISSUE TITLE
Adding Navbar on home page

### ISSUE THREAD

**Issue by snehafarkya** [IAmTamal/Milan#368]
Hey! I think there must be a navigation bar on home page so that user will get an idea of other components of your website. It will enhance the User experience. 

Kindly assign this issue to me @IAmTamal  under the `Hactobesfest` label

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hi @snehafarkya , go for it ! 

- Make sure the navbar is transparent for the homepage and lies **on top of the image** not **above it**
- Make sure it looks good on mobiles as well
- You donot need `Hacktoberfest` Label on issues. But just for the sake of mental peace i'll give you one
