### ISSUE TITLE
Hover Feature on Explore & Share Buttons

### ISSUE THREAD

**Issue by aakashraj01** [IAmTamal/Milan#369]
### Description

While going through the UI of website , I found that few buttons like 'Explore' and 'Share you Love' is lacking with hover effect.
I want to work on this bug and want to fix it under Hacktoberfest'2022 label. 

Please assign me this issue !!

### Screenshots

![image](https://user-images.githubusercontent.com/79682170/193835968-040c990b-c348-440e-8396-74f62acd797d.png)
![image](https://user-images.githubusercontent.com/79682170/193836255-7672480a-d193-4cad-b6a1-2a18ce172463.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by aakashraj01** [comment]
@IAmTamal Please assign me this issue :)

**Comment by IAmTamal** [comment]
A good spot, 

- Take a look at `/contact` page, and the hover we have in the `Just send` button
- Apply the same type of hover in the other buttons too !

**Comment by aakashraj01** [comment]
Hey @IAmTamal . I have added my work i.e the hover feature on Share and Explore buttons on the home page. I also saw more buttons where hover effect is not added and found that most of the other button is looking correct.
Please merge my work in the project under hacktoberfest-accepted label :)
