### ISSUE TITLE
Registration page , name input accepts empty spaces (" ")

### ISSUE THREAD

**Issue by AdarshBajpai67** [IAmTamal/Milan#370]
### Description

The registration page is accepting empty spaces as input, and logging us in with empty name, address etc.

### Screenshots

<img width="960" alt="image" src="https://user-images.githubusercontent.com/95476086/193891164-b14be5e6-ee0c-4fa1-ac5f-8d73b9a76362.png">

### Additional information

I would like to work on this issue, please assign this to me

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
A good spot , make sure the following changes are occuring ! 
- If any field is empty and you click on register the toast should say `Please fill all the fields`

**Comment by AdarshBajpai67** [comment]
Yeah sure, I will look into it ,

Thanks

**Comment by AdarshBajpai67** [comment]
Hey @IAmTamal, now the conflicts are resolved.

Thanks 👍
