### ISSUE TITLE
Add Navbar on Home page

### ISSUE THREAD

**Issue by snehafarkya** [IAmTamal/Milan#372]
### Description

Hey! I think it would be much easier to navigate if you have a navbar on the home page. I would like to do this. Kindly assign me this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/63949465/193989993-709639a7-9324-45b5-9cc2-f80e954fa981.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Go ahead @snehafarkya 
 - Make sure the navbar is transparent and sits on **top of the image** not **above it**
 - Make sure the navbar works and looks good in mobiles

**Comment by kirtanchandak** [comment]
hey @snehafarkya are you working on this ?

**Comment by snehafarkya** [comment]
Hii @kirtanchandak ! Yeah I'm working on it.

**Comment by IAmTamal** [comment]
Hi @snehafarkya , any updates on the issue ? 
Please make PR within the next one day if possible.

**Comment by Ayushbajpai19** [comment]
Hello, can i work on this issue please?

**Comment by yung-coder** [comment]
Hey @IAmTamal  i would like to work on this issue if  possible...?
