### ISSUE TITLE
[Adding minimal Contact form] 

### ISSUE THREAD

**Issue by Chinmay-03** [IAmTamal/Milan#375]
### description

- I would like to add a minimalist design contact form at the footer of the home page
- although the contact form is there in the header menu a small at footer may be useful

@IAmTamal 

I would like to work on this 
please assign it to me

### current 
![image](https://user-images.githubusercontent.com/102941004/194048766-6cd337d4-947a-46c5-b76a-f95e87ad39a2.png)

### expected
![image](https://user-images.githubusercontent.com/102941004/194049084-7ce9781f-475a-4ab7-bc4a-566997b9bfb4.png)

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hi @Chinmay-03 , we already have someone working on a contact us button which takes us to a new page. The button is accessible via footer plus we already have stuffs in the navbar. 

Thanks for raising the issue, however this is not us much use. 
Thanks a tonn !

**Comment by Chinmay-03** [comment]
@IAmTamal assign me another task which i can contribute to
