### ISSUE TITLE
Improving footer of the website

### ISSUE THREAD

**Issue by sumitkr2000** [IAmTamal/Milan#376]
### Description

Hey @IAmTamal , The footer of website is not matching with the theme, I want to improve its styling and add some hover effect on buttons so that it matches the theme of the whole website. Can you please assign me this issue so that I can work on it. Thank you!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hi @sumitkr2000 , the footer has a perfect color contrast + it already has hover effect for the report button. 
What else do you want to change ?

**Comment by IAmTamal** [comment]
It's not about trust haha. I don't want to waste your time working on something which might not be good. Anyways yes, make a PR, we can always close the PR later if not good.
