### ISSUE TITLE
Some Minor changes in 'LoggedIn' Toast.

### ISSUE THREAD

**Issue by DhruvRathi2001** [IAmTamal/Milan#378]
### Description

Here are few changes that I think can be made : 

- First of all the time it takes to log in is a bit more, which can be reduced by few milliseconds.
- Instead of 'Logged In' , It should show 'Logging In'.
- There is a feature that is just by clicking on that toast we are able to LogIn , that should be removed and so the user should wait untill the bar ends  which makes it more Authentic.

### Screenshots

Toast at Top-Right : 

![toast](https://user-images.githubusercontent.com/94394117/194092728-3e30951f-1797-4796-8687-af82f02a6b05.png)

Hey @IAmTamal  Please review it , I would love to Fix it.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by DhruvRathi2001** [comment]
@IAmTamal  Sure, I will make above 2 points changes and about your third point,  currently the feature is yes you will be loggedIn  even if you click on Home.
So what you want me to do about third point?

**Comment by IAmTamal** [comment]
> @IAmTamal Sure, I will make above 2 points changes and about your third point, currently the feature is yes you will be loggedIn even if you click on Home. So what you want me to do about third point?

Yeah let the third point stay - no one would want to get their login cancelled if they just clicked another page (by mistake) 
Rest all looks fine !

**Comment by DhruvRathi2001** [comment]
@IAmTamal  and what about the 2nd and 3rd points which I mentioned should I consider them or just 2 points which you told?

**Comment by DhruvRathi2001** [comment]
Sure
