### ISSUE TITLE
bug: labels and placeholder missing in update user page

### ISSUE THREAD

**Issue by adi-uchiha** [IAmTamal/Milan#380]
### Description

The update user page is bland. User can't understand what they are actually updating. I don't know update profile feature works or not. But I can work on it. And apply relevant labels to inputs

### Screenshots

![Screenshot_2022-10-05-22-16-58-245_com android chrome](https://user-images.githubusercontent.com/103348863/194116785-b554bd70-5c67-44f6-ada5-06f81987de05.jpg)

**Comment by IAmTamal** [comment]
A good spot - work on it ! 
Make sure you add placeholders only for mobiles !

**Comment by tanishk-23** [comment]
@IAmTamal Can you please assign this issue to me?

**Comment by adi-uchiha** [comment]
@IAmTamal I am bit busy these days. You can assign him

**Comment by IAmTamal** [comment]
> @IAmTamal Can you please assign this issue to me?

Go for it !
