### ISSUE TITLE
Forgot password page design

### ISSUE THREAD

**Issue by nishtha53** [IAmTamal/Milan#396]
### Description

I can design forgot password page please assignment currently on clicking nothing its working.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Hi @nishtha53 , what is the design that you have in mind ?

**Comment by nishtha53** [comment]
Hi,

Layout will be same there will be one good illustration related to forgot password in left side.
In right side, Heading of forgot password,there will be one input field asking for mail and one forgot password button.

**Comment by chankruze** [comment]
@nishtha53 next time someone ask you about what's on your mind, please try to present them at least a sketch with pen and paper. It will be even better if you can link some Figma/AdobeXD designs.

**Comment by nishtha53** [comment]
@chankruze okay sure thankyou for advice.

**Comment by IAmTamal** [comment]
> Layout will be same there will be one good illustration related to forgot password in left side.

Exactly. 
Anyways @nishtha53 , feel free to come up with your design and make a PR - we will refactor them then !

**Comment by nishtha53** [comment]
@IAmTamal PR Raised. Please let me know if need any layout changes.
