### ISSUE TITLE
Login page design different

### ISSUE THREAD

**Issue by nishtha53** [IAmTamal/Milan#397]
### Description

- While continue as login as club, Login page design is different to register page.
- In login page purple color is used but blue color should be used.

### Screenshots

![image](https://user-images.githubusercontent.com/68805896/194381867-8e85fffc-efce-4f71-a8a4-d991e5a4fcea.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
A good spot , make the following changes too : 

- Change the text `Log in` to `Log in with your club`
- Make the color of Register button, purple (as in Login)

**Comment by nishtha53** [comment]
okay sure will solve by EOD.

**Comment by nishtha53** [comment]
@IAmTamal I have raised PR. Please check

**Comment by nishtha53** [comment]
![image](https://user-images.githubusercontent.com/68805896/194613557-c5672dd8-afd9-4051-925f-1c8ce7dee4cf.png)
![image](https://user-images.githubusercontent.com/68805896/194613651-519616fa-eb69-451e-b06e-4a465084a3d6.png)
![image](https://user-images.githubusercontent.com/68805896/194613732-8cda52a6-da06-4576-809a-c3ae32fdda7c.png)
![image](https://user-images.githubusercontent.com/68805896/194613806-a3c7d94d-207f-4879-97f4-f527480f062d.png)


Also, changes are fixed.
