### ISSUE TITLE
Misalignment of Social Icons 

### ISSUE THREAD

**Issue by arpitv970** [IAmTamal/Milan#398]
### Description

- On inspecting the CSS of `social-btn` I found that icons are being tried to keep at the center by using some hardcoded values
-  This would lead to an issue when clients with different screen dimensions may get to see the misaligned icons

### Screenshots

The above problem I mentioned, occurred with my system
>![misalignment-social-icons](https://user-images.githubusercontent.com/73063553/194415702-e8a5d1be-d9f8-4067-b24b-2b8628db4b09.png)

### Additional information

Instead of simply hardcoding the positional values, one can use the power of creating it into `flex`

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
A good spot, do fix the bug !
