### ISSUE TITLE
Login Input verification

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#40]
## I want to have frontend authentication for Login page

![image](https://user-images.githubusercontent.com/72851613/152494569-6b6d5e12-9cdd-4cd9-8d50-f041d419470e.png)
<br/>
**I want to make sure that the user is NOT ABLE TO SUBMIT the Login form until and unless   :**
- The email and password fields have values
- Make sure the size of password is **GREATER** than 5 characters
- Make sure the **EMAIL** is proper 
- Finally **LINK** the "Register Here" text to the **USER REGISTER PAGE**

## Make sure you have read **SETUP and  CONTRIBUTION GUIDELINES** before you work.
Incase of any doubt do tag me in **DISCORD** in the `#milan` channel
Cheers 🥂

**Comment by Amit91848** [comment]
Can I work on this?

**Comment by IAmTamal** [comment]
> Amit91848

Are you in JWOC ?

**Comment by Amit91848** [comment]
Nope

**Comment by IAmTamal** [comment]
Well sorry then , this si only for `JWOC` participants. 
Your comments will be deleted soon.

**Comment by mridul4101** [comment]
I would to contribute to this under JWOC.

**Comment by IAmTamal** [comment]
> I would to contribute to this under JWOC.

Assigned to you @mridul4101
