### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by wickedwisdom0911** [IAmTamal/Milan#404]
### Description

There's a typo in README.md file under "Why the name Milan?" section, "It is often seen that people get scammed when their intentions are *in liue they* were just trying to do good for other people"
Could be a great typo bug for me to get stated with Hacktoberfest '22, happy coding.

### Screenshots

![image](https://user-images.githubusercontent.com/78411069/194548074-3e983662-5c32-4463-889f-3a7570c9a20b.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
Go ahead ! 
Make sure you fix all the typo bugs you come across in the file !

**Comment by wickedwisdom0911** [comment]
Thank you for your response. Will get to it
