### ISSUE TITLE
Toast after registering.

### ISSUE THREAD

**Issue by adithgit** [IAmTamal/Milan#405]
### Description

A toast appears after creating a new account  with "Logging you in'" as the text inside. The text inside should be somewhat like "Registering" or the user should be navigated to the home page instead of login page.

### Screenshots

![login-bug](https://user-images.githubusercontent.com/88667329/194565389-7b40254b-b7d6-49b9-8b38-856d13449d59.png)

### Additional information

Two solutions 
-> Change the text inside toast.
-> Navigate to the Home page instead of login page. 

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by IAmTamal** [comment]
I was just about to raise this issue and i saw yours haha. 

- Make sure it says `Registered your account !` 
- After that navigate to login page as usual
- Make sure it is applicable for both clubs and users
