### ISSUE TITLE
Join us part still shown  after logging in.

### ISSUE THREAD

**Issue by adithgit** [IAmTamal/Milan#406]
### Description

The join us part with login and register option is still shown to user which is already logged in. This should not happen,

### Screenshots

![Screenshot from 2022-10-07 19-12-43](https://user-images.githubusercontent.com/88667329/194568518-691ecb21-5b2a-4205-985c-740f3462406f.png)

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by adithgit** [comment]
> Okay, instead of hiding it - what is  it that you wanna show ? 

What's the purpose of showing it when the user's already logged in? My suggestion is to hide it.

**Comment by IAmTamal** [comment]
> > Okay, instead of hiding it - what is  it that you wanna show ?
> 
> What's the purpose of showing it when the user's already logged in? My suggestion is to hide it.

We would not want an empty space in our footer right ? 

- So why not utilize the space we have ! 
- Instead of **Join us** make it **Explore !**
- Login, Register can be changed with **Events, Shop**

**Comment by adithgit** [comment]
> > > Okay, instead of hiding it - what is  it that you wanna show ?
> > 
> > What's the purpose of showing it when the user's already logged in? My suggestion is to hide it.
> 
> We would not want an empty space in our footer right ? 
> 
> - So why not utilize the space we have ! 
> - Instead of **Join us** make it **Explore !**
> - Login, Register can be changed with **Events, Shop**

That's a good idea. Let's go ahead with it.
