### ISSUE TITLE
Home Page buttons are not responsive 

### ISSUE THREAD

**Issue by yung-coder** [IAmTamal/Milan#407]
### Description

Home page buttons are not responsive 

### Screenshots

![Screenshot from 2022-10-07 21-00-59](https://user-images.githubusercontent.com/94097778/194592166-ffbbe532-9d98-4a6c-af0a-f0cd9c1f2a4e.png)

### Additional information

Text in buttons is getting wrapped  i think it can be repaired by giving some padding 

I would like to work on this 

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by utkarsh2709** [comment]
Hello @IAmTamal, Pls assign this issue to me. I have worked extensively on responsiveness.

**Comment by IAmTamal** [comment]
Hello @utkarsh2709 , there might be alot of changes related to responsiveness - please go through the website and create another issue !

@yung-coder A good spot, this should not been happening. 
We checked last time, for mobiles it looks like this, even for the smallest size 
![image](https://user-images.githubusercontent.com/72851613/194602838-5281d5ce-91a9-42e6-94d4-35fe19f4bc8f.png)


Make sure you fix it , assigning you !
