### ISSUE TITLE
Making front page buttons more attractive

### ISSUE THREAD

**Issue by kalashvasaniya** [IAmTamal/Milan#413]
### Description

Make button more attractive!

### 🥦 Browser

Safari

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by najeebkp** [comment]
Hi @kalashvasaniya  please assign this to me

**Comment by JatinSingh08** [comment]
Hey @kalashvasaniya , Can you please assign this to me

**Comment by rohitroy-github** [comment]
I can apply some gradients onto it. If that's okay, assign it to me.

**Comment by IAmTamal** [comment]
@kalashvasaniya  - you need to tell more about what design changhes you'd like to do

**Comment by SiddhiKhade** [comment]
Hi, i would really appreciate it if you assigned this issue to me, thanks!

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya - you need to tell more about what design changhes you'd like to do

Making button more attractive & improving hover effect & many more small changes

**Comment by Satakshijain** [comment]
Hi , I would like to contribute to this . Please assign this issue to me

**Comment by IAmTamal** [comment]
> > @kalashvasaniya - you need to tell more about what design changhes you'd like to do
> 
> Making button more attractive & improving hover effect & many more small changes

Hmm - do make a PR with the changes, we can always Close/edit the PR
