### ISSUE TITLE
"Remember Me" Check Label Font Family does not Match with the entire design

### ISSUE THREAD

**Issue by stereogon** [IAmTamal/Milan#415]
### Description

Looks Like the Remember Me Check Label's font family does not match with that of the entire project. The Font Family got overwritten by another font family called "Alike Angular". If this was the intended styling then its all good and this isn't even an issue then. Otherwise, I have made the required changes and i am willing to make a PR.

I am attaching a Screenshot of for your reference.

### Screenshots

![image](https://user-images.githubusercontent.com/64136587/194698154-837f2e8d-3eac-46cf-b362-61001a3b615d.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by kirtanchandak** [comment]
Can I work on this issue ?

**Comment by stereogon** [comment]
I have Taken care of this issue in a new UI Improvement, that is why i am closing this issue.
