### ISSUE TITLE
Shops page lacks responsiveness 

### ISSUE THREAD

**Issue by yung-coder** [IAmTamal/Milan#418]
### Description

Shop page  lacks responsiveness  it overflows on mobile devices.

### Screenshots

![Milan-2](https://user-images.githubusercontent.com/94097778/194700214-ce3d0aa8-1ac8-4f13-a2a7-f2d8a91591b6.png)

### Additional information

I would like to make it responsive by making some changes in css.

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Chaitanya-087** [comment]
hi! can i work on this

**Comment by Satakshijain** [comment]
Hi , I would like to contribute to this . Please assign this issue to me

**Comment by IAmTamal** [comment]
@yung-coder Go for it ! 
Make sure it looks good on mobiles 🚀
