### ISSUE TITLE
[FEATURE] Add shadow transition effect to cards on hovering

### ISSUE THREAD

**Issue by arpitv970** [IAmTamal/Milan#419]
### Description

The `clubCard` already has box shadow, but it would be great to add a shadow transition effect by hovering over it to make it more interactive

### Screenshots

No interaction while hovering on it
> ![cards-shadow](https://user-images.githubusercontent.com/73063553/194702519-e91a8a1d-b077-4c87-9c65-2440a9fe7b9e.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by SiddhiKhade** [comment]
Hi, i would really appreciate it if you assigned this issue to me, thanks!

**Comment by IAmTamal** [comment]
@arpitv970 will you be working on it or someone else ?

**Comment by IAmTamal** [comment]
> @arpitv970 will you be working on it or someone else ?

- Let us  remove the box shadow from club cards and have a very thin border.
- On hover we can have a box shadow

**Comment by arpitv970** [comment]
> ![feature-cards-shadow](https://user-images.githubusercontent.com/73063553/194714895-ae223a33-d2de-4402-8be7-b8176122f5ed.png)

**Comment by arpitv970** [comment]
- I was thinking of adding something similar to the color scheme already present there, instead of removing the gray shadow as it seems more to be standing-out
- Also using transition property would make it smooth

This is what I am trying to say 🔽
> ![feature-cards-shadow](https://user-images.githubusercontent.com/73063553/194714948-4bb0b5e1-c2ce-444f-a651-2adc7f13685e.png)
