### ISSUE TITLE
Clubs Page Responsiveness

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#42]
## Make sure you have read the **CONTRIBUTIONS AND SETUP** guidelines before working on this issue.
---

## Fix 1:
![image](https://user-images.githubusercontent.com/72851613/152500568-88dc95ac-bd74-435b-8776-614a7ddb74fc.png)
![image](https://user-images.githubusercontent.com/72851613/152500872-1fa3e18b-210f-4d98-b79e-ca5260ceecda.png)

<br/>

For **TABLET and MOBILE** view i want to have the cards size smaller than what it is now.

---

## Fix 2 : 
![image](https://user-images.githubusercontent.com/72851613/152501146-e46b3bb2-7410-47fc-8cc6-539e701cd507.png)

For **DESKTOP** view i want to have a much more gap between the **NAVBAR** and the Cards.
---
**In case of any issues do tag me in `#milan` channel there and we can talk about it !!**

**Comment by mridul4101** [comment]
I would like to contribute to this under JWOC.

**Comment by IAmTamal** [comment]
> I would like to contribute to this under JWOC.

Go ahead.
After done , tag me in DISCORD's `#milan` channel before making a Pull Request.
Assigning this to  you.
