### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by smrkarkii** [IAmTamal/Milan#422]
### Description

Following changes seem to be done. Please assign it to me under hacktober fest. Thank you.
UI changes
1. While we are in Shop section, it doesn't show a line under it like in other sections. I have attatched screenshots.
2. No navbar or any buttons to move to another sections in home page before logging in.
3. Forgot Password link doesn't work.
4. When we switch between sections, or click on the link in navbar, there is not smooth scroling
Authentication
1. There is no password validation for weak and strong password while registering.

### Screenshots

![shop](https://user-images.githubusercontent.com/58778838/194704305-ce3f0dc6-055e-4c5c-ad4c-1054de71314d.png)
![about us](https://user-images.githubusercontent.com/58778838/194704328-167ed794-0793-4148-b9f5-e568768016aa.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Satakshijain** [comment]
Hi , I would like to contribute to this . Please assign this issue to me

**Comment by smrkarkii** [comment]
@IAmTamal , Please assign it to me.

**Comment by IAmTamal** [comment]
Hmm the issue sounds intresting

 - Make a PR once done
 - We'll review and edit changes on the PR !

**Comment by smrkarkii** [comment]
Sure.

**Comment by smrkarkii** [comment]
Thanks

**Comment by PS-11** [comment]
@IAmTamal Hey! I'd like to work on this issue. Please assign this to me.
