### ISSUE TITLE
A button to navigate to the Top of the page

### ISSUE THREAD

**Issue by Rohan-Hazari** [IAmTamal/Milan#423]
### Description

The Home page can use a back to the top button to navigate back to the top
Extra : The button only appears when u scroll down to a certain point of the page and not at the start of the page itself so as to keep the image part clean
Please assign me this issue

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IRSHIT033** [comment]
can I work on this

**Comment by JatinSingh08** [comment]
Hey @Rohan-Hazari , Please assign this issue to me.

**Comment by Rohan-Hazari** [comment]
I cant assign an issue as I am a contributor as well

**Comment by IAmTamal** [comment]
@Rohan-Hazari go for it  

- Make it clean and minimal
- Make sure you make it only for the Landing page.
