### ISSUE TITLE
Add loader when data is being fetched from server

### ISSUE THREAD

**Issue by JulianaSau** [IAmTamal/Milan#425]
### Description

When Opening the events and clubs page, the data take a bit of time to display. Within this time, there is no indication of whether the data is loading or not. I'd like to implement a loader to show that the data is fetching and will be available in a short while

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Akashbag2001** [comment]
I want to contribute please assign me this.

**Comment by nalin-programmer** [comment]
I have fixed this issue, please merge the pull request.
Preview:
![image](https://user-images.githubusercontent.com/54065357/194716359-db009e49-96d6-4641-8250-9971ce08a8f2.png)
