### ISSUE TITLE
SECRET key revealed in User.js

### ISSUE THREAD

**Issue by SteveSayantan** [IAmTamal/Milan#427]
### What would you like to share?

The secret key used to sign JWT has been revealed [here](https://github.com/IAmTamal/Milan/blob/main/server/routes/User.js). It should be moved in .env.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by Rounak-28** [comment]
Can I work on this?

**Comment by Chaitanya-087** [comment]
i would like to work on this issue

**Comment by IAmTamal** [comment]
Hmm we need to  Just change the value to `process.env.JWT_SECRET` wherever we are using the SECRET
And also Delete the line which has the secret value.

@SteveSayantan Will you be working, or should i give this to someone else ?

**Comment by SteveSayantan** [comment]
I would love to!!
