### ISSUE TITLE
🔴 [Automations] - Configure a Github actions for Cypress Test 🛠

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#431]
## Test files : 

 - The test files are located [here](https://github.com/IAmTamal/Milan/tree/main/cypress/e2e)

## Actions ? 

- Write a GitHub action so that whenever a push /PR is made to the GitHub repo the github workflow is triggered
- And all the tests are performmed and checked
- This is a high priority issue !

**Comment by JulianaSau** [comment]
Hi @IAmTamal I'd like to work on this issue

**Comment by IAmTamal** [comment]
Go ahead @JulianaSau  ! 

- Make sure the action works on the fork (like test it out somewhere)
- I tested it previously but got this error :  `The process '/usr/local/bin/npm' failed with exit code 1`
- I made the following `.yml` file which gave the ABOVE ERROR 

```
name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"

**Comment by JulianaSau** [comment]
Noted. I'll make sure to test it out and ensure it works before making a pr
