### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by dev-32** [IAmTamal/Milan#435]
### Description

There are some grammar mistakes as well as some improvements in the CONTRIBUTING.md file. This thing can be fixed to make file more interactive and as well as more readable.

### Screenshots

<img width="717" alt="Screenshot 2022-10-09 at 6 57 32 AM" src="https://user-images.githubusercontent.com/99115141/194733278-2646f340-782a-419c-aa1e-4e324112e110.png">

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
@dev-32 Here are some more changes i would suggest 

- Remove this line : `Each issue needs to be completed within a specific time limit according to its difficulty level ( Easy: 1 day, Medium: 2-3 days and Hard: 4 days ).`
- Change the word **mentee -> contributor** and **mentor-> maintainer/owner** in `If a mentee is unable to solve the allotted issue within the given period, the issue needs to be passed to other contenders on the discretion of the mentor.` 
- Remove this line : `You will be performing changes to tamal-milan branch ONLY.`
