### ISSUE TITLE
[OTHER] Landing Page Background attachment (Minor UI improvment)

### ISSUE THREAD

**Issue by belphegor-s** [IAmTamal/Milan#438]
### What would you like to share?

The background image on the landing page can be fixed by creating a parallax effect that will improve the UI and aesthetics.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Akashbag2001** [comment]
I want to contibute

**Comment by IAmTamal** [comment]
The issue sounds intresting, do make a PR @belphegor-s , we can always make changes to it 🎉

**Comment by Akashbag2001** [comment]
I could not open it on the live server from my local machine. are there any methods? please tell me 
Thank you

**Comment by belphegor-s** [comment]
> The issue sounds intresting, do make a PR @belphegor-s , we can always make changes to it 🎉

on it
