### ISSUE TITLE
React App Footer component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#44]
## I would like to have a **REACT FOOTER COMPONENT** , before contributing read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Contributing.md) as well as the [Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)

<br/>

- The UI/UX part is left for you to do , it shows your skills as a frontend dev , so make sure it looks good.
- It must be responsive for all the devices
- Store the `Footer.jsx` here. 
![image](https://user-images.githubusercontent.com/72851613/152541116-fbfaba1b-92c1-49e0-9809-6c70009dff95.png)
- Store the `Footer.css` here
![image](https://user-images.githubusercontent.com/72851613/152541295-c38e9613-9776-41ac-91e6-d8ed7f77d524.png)
- Once done making the component , import the component in `Home.jsx` 
![image](https://user-images.githubusercontent.com/72851613/152541469-ec5066c0-08ad-4829-89e8-6ac714625e67.png)

--- 

**In case of any doubts / after completing do tag me in `#milan` so that we can talk about the design , review it.**

**Comment by soumali28** [comment]
I want to work on this issue under Jwoc

**Comment by IAmTamal** [comment]
Assigned to you  , 
After done  , contact me in the `#milan` channel before PR
