### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Satakshijain** [IAmTamal/Milan#440]
### What would you like to share?

I want to change the thumbnail of the website so that it looks good 

### Additional information

![Screenshot_2022-10-09-14-11-04-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/79740405/194746968-ba8d6365-fb87-4a19-b5d0-418aba201912.jpg)

Want to Change this 

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Hello @Satakshijain , that is something we wouldnot change. 
That is not thumbnail, rather just a readme banner made by the UI team for Hacktoberfest promotions !
