### ISSUE TITLE
Responsive Banner On Home Page

### ISSUE THREAD

**Issue by Volley-Freak** [IAmTamal/Milan#442]
### Description

The height of banner in mobile view is too large it looks weird on small devices.

### Screenshots

![Screenshot at Oct 09 17-09-27](https://user-images.githubusercontent.com/85556562/194754960-8fea7993-cd64-4bea-a256-37ed35fa3c1e.png)

### Additional information

Height should be reduced on smaller devices.

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Volley-Freak** [comment]
> # Hello contributor, thank you for opening an Issue 🎉.
> Soon the maintainers/owner will review it and provide you with feedback/suggestions.If you think it's something urgent, feel free to reach out [Tamal Das](https://twitter.com/mrTamall) on Twitter.Star ⭐ this repo to show us support.Happy, Open Source!

Okay assign this to me you need to fix that.

**Comment by IAmTamal** [comment]
How do you intend to reduce the height  ? 

- I'd prefer the banner to be fullscreen for mobiles !

**Comment by Volley-Freak** [comment]
> How do you intend to reduce the height ?
> 
> * I'd prefer the banner to be fullscreen for mobiles !

Generally banner size in mobile screen are not full screen. Once visit some professional websites you'll get an idea about the height.
However if you still want it to be full scree that's okay.

**Comment by iharshka** [comment]
Hello @IAmTamal,
Hope you are doing great!
I want to contribute to this project. I will do it by flex model. Also if you want I can integrate APIs like Unsplash into it. Can you please assign this issue to me?

**Comment by iharshka** [comment]
> > Hello @IAmTamal, Hope you are doing great! I want to contribute to this project. I will do it by flex model. Also if you want I can integrate APIs like Unsplash into it. Can you please assign this issue to me?
> 
> ![image](https://user-images.githubusercontent.com/72851613/194903039-24348378-5e72-4b88-9d27-b8c0269d98a5.png)
> 
> * if someone has opted-in please donot ask in the questions.
> * You can always make your own issue !

Yes I am willing to work on it. Please assign it to me.

**Comment by IAmTamal** [comment]
> > How do you intend to reduce the height ?
> > 
> > * I'd prefer the banner to be fullscreen for mobiles !
> 
> Generally banner size in mobile screen are not full screen. Once visit some professional websites you'll get an idea about the height. However if you still want it to be full scree that's okay.

Since this is not so professional website, i'd prefer the way it is. 
Closing the issue, since i don't think we will be reducing the size !

**Comment by IAmTamal** [comment]
@iharshka 
I think you DIDNOT UNDERSTAND what i said. 

If someone else has opted in for a issue, don't go their and ask such questions like `Can you please assign this issue to me?`
I cannot simply snatch their issue, and assign you.

The person who made the issue OPTED IN TO WORK ! 
![image](https://user-images.githubusercontent.com/72851613/194904204-8c4c9193-fe12-4b6b-ba79-8469edb3dfce.png)

**Comment by iharshka** [comment]
> @iharshka I think you DIDNOT UNDERSTAND what i said.
> 
> If someone else has opted in for a issue, don't go their and ask such questions like `Can you please assign this issue to me?` I cannot simply snatch their issue, and assign you.
> 
> The person who made the issue OPTED IN TO WORK ! ![image](https://user-images.githubusercontent.com/72851613/194904204-8c4c9193-fe12-4b6b-ba79-8469edb3dfce.png)

Ohh sry!
Didn't mean that!
Misunderstood the messages!
