### ISSUE TITLE
Design of a card in the events page is different from others.

### ISSUE THREAD

**Issue by nihshesh** [IAmTamal/Milan#446]
### Description

Design for third card or "Hello" event is different and it also contains some random words.

### Screenshots

![image](https://user-images.githubusercontent.com/61341935/194794647-107154e2-d60c-4836-8700-6926fa295262.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
The cards are dynamic - meaning we are getting the info from DB

- We will make changes to the DB shortly, however changes in the Frontend can be done so that they are of the same length
