### ISSUE TITLE
Zooming on hovering on the products

### ISSUE THREAD

**Issue by wickedwisdom0911** [IAmTamal/Milan#447]
### Description

In the shop section, when we hover over the products we can apply the zooming animation to make it look more interactive.

### Screenshots

![image](https://user-images.githubusercontent.com/78411069/194807473-798074db-2b9a-462b-9025-5a6adb5aa047.png)

### Additional information

The above screenshot attached is what it will look like if we hover over the images.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by mo-renike** [comment]
Please assign me to this issue, I am willing to submit a PR!

**Comment by iharshka** [comment]
Hello @IAmTamal ,
Hope you are doing great!
I want to contribute to this project. Can you please assign this issue to me?

**Comment by IAmTamal** [comment]
@wickedwisdom0911 - Don't zoom in, instead have a box shadow that appears on all the 4-side on hover

we can have `#297f75` color and a pointer cursor !

**Comment by wickedwisdom0911** [comment]
Sure would get on it.  Once I am done, I will attach some demo Screenshots
to see does it match what you are looking for. You can assign me. Thanks.
