### ISSUE TITLE
Regestration And Login Email Validation 

### ISSUE THREAD

**Issue by Tineshnehete** [IAmTamal/Milan#449]
### Description

Email validation on both login and regestration pages are allowing email input like `user@gmail` where it should be not allow email withoouth tld. 

### Screenshots

![image](https://user-images.githubusercontent.com/74779225/194816194-79c88bd6-9470-4770-9c5c-327b8feabad7.png)

### Additional information

We can improve the validation function

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Barkty** [comment]
@Tineshnehete, please assign this to me. 

I would create a validation check on the inputs' onchange which would validate users inputs before the form details are submitted

**Comment by IAmTamal** [comment]
@Tineshnehete Go for it 
Make sure it works the way you intended !
