### ISSUE TITLE
Placeholders missing on user register page

### ISSUE THREAD

**Issue by tanishk-23** [IAmTamal/Milan#451]
### Description

Placeholders are added to some fields of user registration form and some placeholders are missing.

### Screenshots

![Issue](https://user-images.githubusercontent.com/72482878/194824254-0650a4e0-c5ac-4065-926f-4023dd1cb3d0.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by nalin-programmer** [comment]
Assign me this

**Comment by harshhh11** [comment]
Can you please assign me this ?

**Comment by Dnyanesh-Bachhav** [comment]
Hey can you assign this to me...

**Comment by Barkty** [comment]
Please can you assign this to me?

**Comment by iharshka** [comment]
Hello there,
Hope you are doing great!
I want to contribute to this project. Can you please assign this issue (@tanishk-23 has opened) to me?
