### ISSUE TITLE
The Scroll back to top button is not scrolling to the top completely

### ISSUE THREAD

**Issue by belphegor-s** [IAmTamal/Milan#454]
### Description

The scroll back to top button is not completely scrolling back to top, it leaves some space on the top.

### Screenshots

![screenshot](https://lh3.googleusercontent.com/fife/AAbDypBJ35UaL-VNKA--AMBFG1MIozk18dUU767tuYcuDpWxRDma0Rqq9N5g3-x-7xfGf47mo2cLh8qF9zMDiJ8-BgWFued2q3EUe59BkMkGDY2pSEEYo_DFAbQYO2q19Wxen6oVK27XUMTGCrbYRSEdoBYGqWYDCyOB1hw3Xxut64ZuY2Qz1FqSbO0MY-44ZQ1AYUFFMYdmoeCecVkj38flRP0LtnCwdDQSo_R1cB-q3pRxK-qcCrGt3JI9H87JckknwemrQ3rQXcb_dyrD9WSeBXk21rCxCG_nEI8f73NEGe09JX9WzKEZl4rO3vb2HwzgWy3zmJPZzFBKZFdOQZnD9zjNJHuRvn6fOLkc2L-E4kIppXe1sagqmkpsokUws_xVF0erxMTiboPBv2D7P4Tw9gjqpX7VtLD_UmuJpHYpUMyA2JVr1FOUs8pqTnQeZjj3BWbVsT69vEwzcHFZy84ERVKxUBS0bwxAoQ3yC0LBCZPxb_gbiyzpJOtUkWMOS8nLBgjg5VcKZcVEA46EV9U1pz2kapPzrpOkW0mIgaLVrZsDr63oXzxlVVBpVWh8e8FDX0WXMWjPbbx88b8hHjT_L7mjVu0S7s1LB7fRcH9dSstwWzvcSI8RJpvt6Da5yoZOKiXsG_s07WG2ZY4E497RLLTuILr7q7AXnxU4UtKLbfH_0Y6pcBk997XR_n06G7v6ClN48mma-Y3PA7uNW53t7p212bgf7_WiwXnB6ZWLVXs5mj3lVzx5t4jY7KeqVr8oxY_t_XjomPTkZb_L7PkCrSxtQMEOON7mBXTDrHpYk4BJYd1oqC1tsf_-E4kdus2FyzJvADWQy687pr8YQB4CREB97dijI40rDhIPXd_LdXO-2HvrXpE5GAKtYFED2W7Hasx3YuSlofqZU--gZsYhLKf6Pk-PMJXEhveSRhWIosYEYbaAbRGOgrCp1zxruCDxuF5FkZ1Pj5KiLQn6flRuliwGl0PH4Ba6-__4bNsancqexk5S9PFloN6MWpk-72RhTPABIbA6jJ0isThujmneLLupHOGOMwu0hMn_qJSsVqNqC-Pua_3wYQ3hHrq1jMl_aN9kpokNmq6l3j3A5b6q5Qro2wJIVb2e_49y1QqDfS1ogRFSN-GIRRjKWSWP6Zse3H7JU_zTshx15SfYlenuN1rFIbG_PuTYKoDHr-cNagCU-VASm3V0rmHlDhqfdBviwejn_rCdr8i2DGXdm6louhtsEtkl_9aVDTJ_1WuzKM363efHctrAK1I1M13j8mmabQB3j7ZbaYbRG5G7bHFFLbK2X5yiVp8tCvWgBKy6LESoWIq5FEOfqB_C_GjX5yDgMFTcl7Drm5edWWK4Qau8q9QTwQzam3YKprdmQHx3cRJAbxFMedcsf2r_Wx8I0lxLSWFznUWgnd6Cc4zTnzYKcKnHeHT7-moQj7-z7dc7MFeWuvuo8JOa7DCJRWHgbphYziW_Y2v5G5SOyxITCSzTbqS2x88r1bl2RIGeh4UcjwWL-qhRR5oCIVnInXqBJS8aV2tdvF2u2pz6IBhJaMaD8NMehjodmLxHIb-GMDaA7KaqDOvrxD07DNOjjHg=w1366-h649)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Go for it
Make sure it works both for mobile and desktop
