### ISSUE TITLE
On the sign up page, users should know why the button is not active after they input their data.

### ISSUE THREAD

**Issue by iceddrop** [IAmTamal/Milan#460]
### Description

The number of characters a user might want to use as password can not be predicted and so might be less than 5(what it takes to get the 'register' button active). Telling them what is wrong will improve user experience ''**password should be more than 4 characters**". I will like to work on this.

### Screenshots

![image_2022-10-10_210631728](https://user-images.githubusercontent.com/93996532/194944113-1f24e5d4-bc5b-4c2b-af00-71217b2ce82d.png)

### 🥦 Browser

Opera

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
A good spot - go for it !

**Comment by iceddrop** [comment]
Hi my merge was successful, it's working perfectly now.  I noticed some changes in the codebase though.

**Comment by IAmTamal** [comment]
> Hi my merge was successful, it's working perfectly now. I noticed some changes in the codebase though.

Which merge are you talking about ?

**Comment by iceddrop** [comment]
![Screenshot_20221013-094109_Chrome](https://user-images.githubusercontent.com/93996532/195547540-9d4aaef9-60aa-4eac-be06-61e109a65300.jpg)
That one , I thought it had already merged automatically.  Thank you for allowing me to contribute,  I enjoyed it.
