### ISSUE TITLE
Create a dashboard

### ISSUE THREAD

**Issue by HeisRoy33** [IAmTamal/Milan#461]
### Description

Create a dashboard to showcase events registered, amount paid, 

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by NnajiChimuanya** [comment]
Is there a dashboard please assign me?
