### ISSUE TITLE
Active state CSS for Shop is not working in the Navbar Links followed by the display routes 

### ISSUE THREAD

**Issue by belphegor-s** [IAmTamal/Milan#464]
### Description

The `Shop` Navbar link active state CSS is not working, for other nav links there's a small line that shows whether the link is active or not, but for the `Shop` Navlink, it's not working.

You can see in the screenshots attached here.

### Screenshots

![screenshot](https://lh3.googleusercontent.com/fife/AAbDypDZUKB1eFXtuYRBdQcwCrNql8pwxGc2j8NnTHtvYfKkuNZqDI8TMDghTFxVZMC6yEICV3mg5nZ5M3dMZhRs12akqxtaPoIxEw6zM1vOl06iWoppMrGFFTkedcKeXmHmohnKt6xYF2pczrv_GE7jgdf7S9y7YD8qMrNt-naaGzfYStHbMXC_vsD9mR-kFieoZTFIVMaq1VHHjFrt54BS4bK3gjhaexEdAXYfIJpCee_bHDaM0qFBR60P5Gk2MleFWGwM_eSkxcMED8ZhwoWn6-rqR0J_x7jQH3lrmslbth3GMcI8Bts2IHZHlXfNhcUj5GZKNOzMJZwo5uJ4pEowPlZ3Fr7tpx17O-kpvcG67_tLvwQP-lJzg0k41CJCKGq8AT1KQSUaSTLbDAg6NO1sh1tDxMB2WbK8yoQnWWX8tFH4iTOVq8hwcIa2Jl7u47qZkJsgvJ_1RqGNCTU7kGtyOrgUimAOfGrCsxC_IXvVsnbYunM1nVbM8nin-DdVg8FS7-soTASlrIjI8N-9iYNDQ6FA8bqVBwtIEHk0-xwvLZHi2BmH9sfSB02vWUkNky0wmfsQU0x1Nm3tf9bp_YR0WSkebx7a1FsiAyneKaNM7Q6AsyPkHVRX15dCJOCje04Xux5J8-zTDMplX36OgWe2EWZA2nk3w0ZcLPTBgEgVbQoA1yhCugZlbFVHC35Kwcs330g8klIzOb3mFk5FFdGOU4cvz2gN1aekObtW0YG4BZv6NrSXc8w54lgGVOe088ys6kEs1lH1t1PkHpcY8DldTOS4n4utFVSkF48Vu4ruv5TWkfhkOMf8Vr1JuckwNUjYvDUozBQQazO-0Sv8ZrT9rS2e7_lqyPvTthIVLUpROjKylbnZPcxulp7AfVRxTZJhx0eTurj4dgq_u5s2oL2thxdsqtCazJcp65aQ46lYSUvkj8wCJu1idDkcCfqGhkfASnPD_ePrF_j5eb0h2VsPYSx9jpE0O0rKsaSuOYmP9OMyKCqwwnnjDLfqQ3OYW0Ae_jf6belNMiqc_z0Knx0bHOsdNSZAMEIBZS75DucgjHsyxDIWAx-xWfEPPUlNpbAt0tRFB6WP4m-uD88WpuI4s7T5n6goQAh4pMsFpFKzZ2cZH-DCXsfQSWWi6zpRiQSbO7_TVEna306DCBOWW3eIjfmK11SmFLvIAkxsFP_WmLVnjJ-QS1cnxbTXN6LZPX1U40CjKfrcbFNDm1p9C4Lm2n904BnaC9W9FCDu5qyS9cHNwZ55aQGLS_-6ObucDIsUxrUKw5v9hkAh3YzuvNAiQS5AhYAZscTB7EuOeRUvUQYNpVuoSehloHX6DbPzGpq710Ncxe13EGblHFuFmM8FNdNgYI0mg4K_TglRFJfxnWHCNI3KEzK0PR_fqJVIvsdHtXk9S5ueOSl_yM6L_VOKC44fqChypRUYQkTNHG8a7zlDiHmX5hiV5-bPvnzhFL4WktugXCloeToisejuxySRBiFZd7H_EGv1MYGsE4DgVSp73YEKh3xanCGdRH1QxURH0Sl36Dfq4loWXk1DJ9XV9xGHkvlrtf56wWUndv44fMgdc2sqab7s7wJL2Q8=w1366-h649)

![screenshot](https://lh3.googleusercontent.com/fife/AAbDypDUVTADBPK-IsZ9b5lZ3EiLdPU45bjBv4agEx7kWvJhVlXHMJ-9UVRDOBV9PkBkPs-UdhzhU8lWGY42UgvmCs57AKaEw5TFGmHUc5DrhORd84D-qJbDDfRFDvgrUBJQWX9FaNfpaViR2ZA0qankg0pEdSkg1eqeC_8tnwTO1FoWJBnh2BteGpmse_ku5DSTa-50nKEnmpxO5kh5yW6A6qcEYO7M8nnK2zNWKgkLmeoaYHJhSLYL8O52yIvEjMnWTY6w2cbUyKxMvYZhvKX88diztBODiIPuPefUiSKuLvyhKv2xYawE4HcqimM_pzkkcCFIyTPjhdWVcu6vGoC71kClkwE4LGN-BzCThW3aRlG7m-o9hqz4vuQnXgrKtmuZ3TdnKj4ne9MbbPBR85QHVR3RgV1HsuRQIczXTzPmz4MKcw-YS8Lb4e3q3Knaap-aWJhMF8VFKQ-Re2C5MbydvatjjwYgIdyOPuLl2blzsqkmMkLzftXXUL_FvZOKvb0hkc5QQZ2Q7_KTSaq_TJDf-S22ORCEOlGny5TNpo9zrin2SS3E-vthflk4Cd4OBZpWqlSonHXlPFMuawffB8ZAqnss9rq63ws4MHq6bneKXPd54o92plbou4u-v9kLd2ZVFVdDCrSlFo1DW665nfBMMUpqOJ3095D5KczoFcMe6Huq5BpfZ8esEuRfx7RksBpqu2tml8gBKiY5ypl15CmJL0at--rSHfPyBa_0O5mXp1MEY9pPdIL0T3XnbuO-cZ_dpINlB1d7yBidle5vvpxrjy1uc04gbfp5SOv3p-YoQL_KgYZEy_9N5T_H5P-t9VVYJwC1Wk9XWxHlcZrPLdRXHpOiNiNnh7caDekbjAeuhWjyeEMZ7DEJyzLMD_N_7j3dXv2X4aFtrjfa8BmXSWZhr4kQrbiJAV0H5M40OJRfM2BiSFTm4fntEO5lEmpyz0i_pko0x29XlVId_-ty4_unMFna1XVxfRYB4hWxrOXGs27D9hW-kAJhXIIecyopMQcglo6n_jhChzhsrXMm2zX_z6kaUszCiA7UoJwMiFrT_LnlLqJvVAcGMBRteFfGpx-VmvFl11UnlV4FS6h9iBL5rk5vPGf9kSwlFeW2J45Zc5Ns2iLXqgLxfO9n3RaHWmINLWXPrOTouF3_K4cF-TIR3QTLfDvz56w1jwUDK01GAJ8WzbX2hiYa8csb-7oQukLUqRiu76GMeWv17xEV0tQ8eCYZ8YZi2NBNEJtGPIZwdxUBzRMvfapugtSar5Fixw6Z2vNBmTlyyVpRXPVKR5rb83pxNrKINdgDQmABC0Foc7GvjtqoD3TUpvU6tfjEuf60XzFIdhbgRcoR4EgakuEGR9EnsPFc10f92ZnVoVS2Ts8bcHGtvcv2nqG06RASIfnoR1xulAWdZvcoZCeTol3XFu8Ykuiu81vNUk-ujJhxvIlzm05jticAB6T0e-qY2Sah_NPas84CRZVLzYwk92Os0RWi7V2y53EzTDhw1emxW7fBJWpuX3hBAYZB9fXdgFYfOyiAZRa21r_o6cH1mUg-wO1piMD6mdePdZzBUhJb_3SkyjEcoigjjJSpqhs=w789-h649)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Go for it @belphegor-s

**Comment by belphegor-s** [comment]
> Go for it @belphegor-s 

On it
