### ISSUE TITLE
[OTHER] Landing Page Improvements

### ISSUE THREAD

**Issue by stereogon** [IAmTamal/Milan#466]
### What would you like to share?

1. Adding the Milan Logo at the Landing page for both mobile view and large screen view.

![image](https://user-images.githubusercontent.com/64136587/195045825-3e4f8ec3-28de-4ff2-853d-ecc11435f77d.png)

2.  Fixing the Media Query trigger point for better Transitions.

![image](https://user-images.githubusercontent.com/64136587/195046386-10732a4a-38a4-4543-a510-ed35721c6bc1.png)

3. Some Buttons' font color is too dark. 
Also the text should have been Reset Password!

![image](https://user-images.githubusercontent.com/64136587/195046986-46dcf548-2d62-445f-9f9e-6a3dca6caec5.png)

4. What about this gradient overlay.

![image](https://user-images.githubusercontent.com/64136587/195048652-ea527360-8b9f-4c29-9535-05e2a879dc27.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Hello @stereogon  feel free to work on Point 2 and 3.
The rest of the points needs not to be added.
