### ISSUE TITLE
UI/UX - User Registration Component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#47]
## Guidelines 🔐

- [ ] I have read the **[Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Contributing.md)** 🔐
- [ ] I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

### Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage, **, then in the Css files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
- If you look at the Login component it looks like this : 
![image](https://user-images.githubusercontent.com/72851613/152650039-0ed75bb5-7d18-4ef0-9e88-9cfe4fa9fa60.png)

- **BUT** the user registration component looks like this : 
![image](https://user-images.githubusercontent.com/72851613/152650076-e0d49536-9493-436d-94d0-446ed64aa786.png)

### You can also use [this picture](https://www.vecteezy.com/vector-art/4652920-male-customer-support-phone-operator-with-headset-working-in-call-center-concept-illustrations) in **User Registration Page.** , but make sure the page looks similar to **User Login Page**

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.

**Comment by mridul4101** [comment]
I would like to opt for this under JWOC.

**Comment by IAmTamal** [comment]
Go ahead , mark the checkboxes once you are assigned. 
Also make it as accurate as possible. 
Assigning to @mridul4101
