### ISSUE TITLE
Club cards are above footer

### ISSUE THREAD

**Issue by Anuragwagh** [IAmTamal/Milan#472]
### Description

There was a small issue: on the club page, the cards were above the footer, and there was no space between the footer and cards; they were overlapping.

**I had fixed that issue** 

### Screenshots

![Screenshot 2022-10-12 014330](https://user-images.githubusercontent.com/56196363/195198595-b1db64cd-c0ae-440a-81c7-79bcf42651eb.png)

I had Fixed it.

![Screenshot 2022-10-12 022424](https://user-images.githubusercontent.com/56196363/195199375-d86a32c5-5b46-48b0-838f-8cee73973f13.png)

### Additional information

If you allow and accept this, I will pull my request for it.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by billy-le** [comment]
Can I work on this?

**Comment by Anuragwagh** [comment]
> Can I work on this?

I had fixed that issue.

**Comment by IAmTamal** [comment]
@Anuragwagh - from next time please provide a valid title for the issue. Instead of just `Firxed the issue`
You can make a PR !
