### ISSUE TITLE
Resolving Bug : Password error messages

### ISSUE THREAD

**Issue by iceddrop** [IAmTamal/Milan#473]
### Description

I raised an issue earlier concerning user experience(password error message). The code I wrote would display an error message if the number of password characters is less than five, but even when the characters were more than five, the message was still on display. Please assign me this as I have already corrected my code. Thank you.

### 🥦 Browser

Opera

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by IAmTamal** [comment]
Please close/ work on the existing PR first !

**Comment by iceddrop** [comment]
Hi, I just made the necessary corrections and closed the previous pull request.

**Comment by IAmTamal** [comment]
Sure , go ahead - make sure you test out everything !
