### ISSUE TITLE
The scroll back to top button shows up even if we are at the top of the Landing Page

### ISSUE THREAD

**Issue by belphegor-s** [IAmTamal/Milan#478]
### Description

When we visit the landing Page for the first time the scroll back to top button works perfectly (i.e. it's not visible if we are at the top of the page), when we scroll down and click on that button it works perfect but *ideally* the button should not be visible if we are already at the top of the Page.

### Screenshots

![screenshot](https://lh3.googleusercontent.com/fife/AAbDypBPQvlodvnfZM-iSl-TtvfPxQCwv-X1pCo5PUZ7R6u0weAEhkzT1e6jQ7FpiElu31s90_j4sMfhOJQwHF01FW203h4AlGfJDs6YYe4Dibr9FXpEifrEe8e7ccHepiUpXWrRfbbn2qGhRZNHVm3zlsDtNTwUi1jO97IR6wb3_oOkRbxvVV8q3ZfNXWNcdeNJhJv0O_mmKv0nxhKI92N6kQ5zqBnfEvVC0tHNAB_0314f_dRXZ5lJo83eGhsvwxC8KKy0kPFiPxI6mVGVbUrTgwfbaBvWc0RxSx6sI1pnvTMLhron_s3LLW28oxgdaDdvZ73FMCN0hBjvWKw2bh45JLE13lJq0e29KPd1X0M1PpVKBkSAazZuoypS76moe2DFRXVOo1YislrRues_DrmN0kJEaYZoh_X94t2_mQ3mCY-3PLCaTwkq89kZ-VQb0FkfWo9Twqn9l6Xb9qQsXbrekuONb0VmIEXEkrerq7it1X69ZjMNEr12eUyUdZSanX3Ia-BnxjYtBOhY6PEfI_1-OoWBhxYQCVZLvhqz_2RE3NK-_MLqQjOK5GaVvfC_vUvK7NDy_UCDzF6PdGCq4n3ZUgz_jnj84aV5N0MKBA-hzvPIa9yNtUgand_nr2cnYnOA2w5Y9mtKR5lIuUiPOu_qJCVnb6wu6OUZDbaipz_e7NlAwpnOV39awCyhus26K0rWsZ3Pg-q_fNbjGN9Zq6GxFhlpT8HINt2nk7dJnv5wvHxAAnFgKlRsX3_zm6BNmMKxEcVYAANy_K2Lw99X7_Q5zwG8PUQ73TTYqJ0pllh7u6NYFXqeLVWr3dfKQ_M8oA9twE1zQ-QoIPFYWV6QH0ZAyWu84xLxo0imm3bo-LD7B0YwBHD-tGyISYsyibA1uBnkSqHTTJux3ve4ovzu8PL8T_pPeQxzcBc6LRN16CHUbExPdAbwCbtQIEMron2rbQ-x5fvJREvgcfUemOfTk5nXLjHDlhZ5qCsQyr8TW-tljTSZMDNHfB6wO4fMDPQ9grjYw2PL4zzckWvWkonSa7TKgDEY6aJyIGFx7ELjY8zVb2Io1jI_cCrhzdPEg_0eHxqd9o3Bel9GiEo1qAJc0gQRH8mvUWhKndsSDCDIuqUxcVlLHt_tyo0UMKINVDzPz7d6xFDPpJ00w3eQGh7PtxrNlrKBmfZrW5CKxdJPWOAjfOG4Vs_uSX2N0kqvxTxeAr8Nf2S2m718h5dH9J9aTlbcJOnQx22gu4Sh_oWWHz_G_xf21dkNszJx9Sed0CV8SOrIf_jPsulkAcQZqcIwEXR33_lLJvNbFF8XM3Py75hx7a_srmCg_aE1ucsohjPRpz4XYRoZfDvdGOTugzZ8n2FTzz7lMf8Yw3ioEEHpIGBI0hJBoxLWBWtIfWfuA8rAtxnfpDQlQOX_38AFNX82vMPHWabsHCSIIhaxDB5Tsi9yC6aZFrivdg1EfHV4-acRlRmKoqm-r49k50S29aMd4i0CEv3tZ6WEl8HxgBe2lQ5lby6QzjhGqoXmBV8OviF-Q0j3ln34Mcox4TOqii2QpcLR2kwl3GqwJIt2hWi_bc_1xyOqalyulswy7YwFA3Y=w1366-h649)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by belphegor-s** [comment]
> Hey just wanted to let you know that it has something to do with the once:true part ![image](https://user-images.githubusercontent.com/91898040/195390533-5ed4aee1-1d20-4cc2-a486-50cd4475bce1.png)
> 
> I tried to do this too but couldn't do it without resetting the animation for all other elements Hope this helps you and you find the solution Good luck :)

Thanks for the help was able to do this while maintaining the Animation as well. @IAmTamal I had corrected this behavior although I'm not assigned yet, so should I make a PR or do it once someone assigns me??

**Comment by IAmTamal** [comment]
@belphegor-s 
- Sorry totally forgot about  assigning the issue
- Yes do make a PR we can review it !
