### ISSUE TITLE
UI/UX - Scroll Bar glitch

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#48]
## I want to <text here>

- [x] I have read the **[Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Contributing.md)** 🔐
- [x] I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

### Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage, **, then in the Css files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠

**Take a look at this video**

https://user-images.githubusercontent.com/72851613/152650591-1ad01039-d93f-4a91-aea8-5d147ba3e62f.mp4

**Notice how the scrollbar is getting stuck a bit while scrolling ?**

**I would want that to  be fixed**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.

**Comment by Devmindtk** [comment]
I would like to work on this issue.please assign it to me.

**Comment by IAmTamal** [comment]
> I would like to work on this issue.please assign it to me.

These are only for JWOC participants.

**Comment by IAmTamal** [comment]
Go ahead. 
Make sure you've read the guidelines. 
Incase of doubts do contact me. 
Assigning to @Devmindtk

**Comment by Devmindtk** [comment]
Do I have to join any discord channel to give the updates?

**Comment by IAmTamal** [comment]
> Do I have to join any discord channel to give the updates?

Umm yes , JWOC has a discord channel. Sent via email now.

**Comment by Devmindtk** [comment]
scrollbar is getting stuck only on clubs page right?

**Comment by Devmindtk** [comment]
https://user-images.githubusercontent.com/91221069/152932346-4a00b201-18be-456f-8521-120174fd4b94.mp4

@IAmTamal  check this one is it fine now?

**Comment by Devmindtk** [comment]
> @Devmindtk looks good to me. Is it totally smooth now in the club page ? (on scrolling thorugh the mouse wheel)

yeah its working smooth.

**Comment by IAmTamal** [comment]
> > @Devmindtk looks good to me. Is it totally smooth now in the club page ? (on scrolling thorugh the mouse wheel)
> 
> yeah its working smooth.

Great !!
You can make a PR

**Comment by Devmindtk** [comment]
> > > @Devmindtk looks good to me. Is it totally smooth now in the club page ? (on scrolling thorugh the mouse wheel)
> > 
> > 
> > yeah its working smooth.
> 
> Great !! You can make a PR

error: src refspec main does not match any 
facing this error in pushing my code to origin branch

**Comment by Devmindtk** [comment]
> 

@IAmTamal after writing command git pull it shows this how to fixed it?
  fatal: not a git repository (or any of the parent directories): .git

**Comment by IAmTamal** [comment]
Make sure you are in the right directory. 
![image](https://user-images.githubusercontent.com/72851613/152951713-ef52d5ae-adf3-48de-be9d-174c33e7e114.png)

**NOT HERE ⚠**
![image](https://user-images.githubusercontent.com/72851613/152951802-74b9d770-32a0-4969-af75-fc20538b69f9.png)
