### ISSUE TITLE
Multiple "Logging You In" pop-ups if Log In button is clicked more than once

### ISSUE THREAD

**Issue by SteveSayantan** [IAmTamal/Milan#483]
### Description

After providing the credentials, if the user clicks multiple times on 'Log In'  button, it generates a bunch of 'Logging You In' pop-ups.

### Screenshots

![Screenshot_20221013-140202](https://user-images.githubusercontent.com/92118155/195548558-2bc50ba9-aa96-450e-b216-d0feff9d7900.jpg)

### Possible Solution

After clicking on the 'Log In' button once, it should be disabled until receiving response from the server

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by curator69** [comment]
i am ready to work on this issue @IAmTamal

**Comment by IAmTamal** [comment]
Thankyou for raising the issue @SteveSayantan - this is definetly a problem.
@curator69 go for it ! 

- Make sure you implement functionality for both Users and Clubs login
- Do make a PR once done, we can always review it !

**Comment by curator69** [comment]
starting working on it as writing this message

**Comment by the-macson** [comment]
Can I work on this issue @IAmTamal

**Comment by IAmTamal** [comment]
@the-macson Never make PRs without getting assigned. 

Anyways idk if the assigned person is actively working, it's been like 12 days with no updates. 
Do wait for 12 more hours, if @curator69 gives no response, you'll be assigned

**Comment by the-macson** [comment]
@IAmTamal more than 12 hours done but he is not responded 
Please assign me and submit my PR 
Please Sir
