### ISSUE TITLE
card is overflowing

### ISSUE THREAD

**Issue by ShravaniAK** [IAmTamal/Milan#484]
### Description

the card is overflowing

### Screenshots

![Uploading Screenshot 2022-10-13 at 8.03.39 PM.png…]()

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by flying-solo** [comment]
@ShravaniAK  can i work on this issue ?

**Comment by IAmTamal** [comment]
@ShravaniAK 
- Please provide proper screenshot
- Please provide a proper description instead of just `the card is overflowing`

**Comment by IAmTamal** [comment]
Hello there @ShravaniAK it's been 7 days if there are no response from your side within the next 12 hours (starting now) i will be closing this.

**Comment by amit-ksh** [comment]
Hey @IAmTamal! I reckon this issue is the same as this one #502 and explained more appropriately with screenshots.

**Comment by IAmTamal** [comment]
> Hey @IAmTamal! I reckon this issue is the same as this one #502 and described more appropriately with screenshots.

This issue is going to be closed since the creator hasnot replied for like ht last 7-8 days. IDK if they are intrested or not
