### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by ShravaniAK** [IAmTamal/Milan#485]
### Description

add hover effect to the products

### Screenshots

<img width="1440" alt="Screenshot 2022-10-13 at 8 03 57 PM" src="https://user-images.githubusercontent.com/97099574/195626630-08a91b5a-d46e-423b-9331-aeb344cd9234.png">

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
@ShravaniAK  
- **This issue is already been worked out by someone else at #447** 
- Please always check before making a new issue
- Please always give proper issue title instead of  `[FEATURE] <description>`
