### ISSUE TITLE
React App Home Page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#49]
## I want to make the **HOME PAGE** for the react-app

- [x] I have read the **[Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Contributing.md)** 🔐
- [x] I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
**Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names**** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**This is how the homepage looks like for now , as you can see it's empty BELOW the banner**
![image](https://user-images.githubusercontent.com/72851613/152669147-49114655-8279-4962-a3cb-5303f30b9973.png)

**So i want to have something here , we call it the `HomeCardsContainer.jsx`**
![image](https://user-images.githubusercontent.com/72851613/152669220-d7dbd2d7-b2f2-4fe5-b28d-e3656cbc0d18.png)

**Inside `HomeCardsContainer.jsx` i want YOU to write the code so that we can have this design**
### **DESIGN : [Figma Design](https://www.figma.com/file/sPVLhYppzhCzYYbqSmlebm/Untitled?node-id=0%3A1)**

**Make your `css` file here , NAME the file `HomeCardsContainer.css` :**
![image](https://user-images.githubusercontent.com/72851613/152669439-0dad5ef2-a853-4fb6-82a2-cd7e2ad6ac95.png)

### Category --> HARD (4 Days)

  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.

**Comment by mridul4101** [comment]
I would like to work for this under JWOC.

**Comment by IAmTamal** [comment]
Go for it !! 
Do follow the figma design as **accurately as possible**
Tag me in `#milan` for queries.

Assigning to @mridul4101
