### ISSUE TITLE
Misplaced vector images,

### ISSUE THREAD

**Issue by pragatisaikia** [IAmTamal/Milan#490]
### Description

On the home page, the second div has 2 image vectors along with written content which is not aligned.

### Screenshots

![vector-images](https://user-images.githubusercontent.com/92122197/195902418-43e6d028-bbac-4e10-bd04-5a5c37a03521.PNG)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dheeraj0014** [comment]
I can do that .
!assign

**Comment by IAmTamal** [comment]
The design is like that, we donot want it to get aligned  !
