### ISSUE TITLE
Login Button adding a border of black colour on hover

### ISSUE THREAD

**Issue by exotic123567** [IAmTamal/Milan#491]
### Description

When the cursor hovers over the login button of the website, add a black (dark colour) colour border around it so that the user can know that they are about to click abutton.

### Screenshots

![Milan Login Button](https://user-images.githubusercontent.com/86504733/196020374-c5c1f707-2f66-434b-ac5f-5c5181701d6e.jpg)

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by kirtanchandak** [comment]
can I work on this issue ?

**Comment by sumit-022** [comment]
I can work on this. Please assign me this issue

**Comment by shashank-2310** [comment]
Please assign this issue to me.

**Comment by IAmTamal** [comment]
@exotic123567 Can you make something like this for all the register and Login buttons : 


https://user-images.githubusercontent.com/72851613/196376112-892e0ece-25ab-4a1b-ab53-44e575177e16.mp4

**Comment by exotic123567** [comment]
Yes. I just have to add this to the css file when the cursor is hovering over the buttons

**Comment by the-macson** [comment]
Can I work on this issue @IAmTamal

**Comment by IAmTamal** [comment]
@exotic123567 What's the update on the issue ? 
Are you working on it ? OR should i remove the assignment
