### ISSUE TITLE
Sumbit button lacks responsiveness 

### ISSUE THREAD

**Issue by yung-coder** [IAmTamal/Milan#492]
### Description

When we click on report button on footer for any bug it lacks   responsiveness in mobile devices 

### Screenshots

![milan-new](https://user-images.githubusercontent.com/94097778/196024971-9509f39a-fc46-4a8b-b49f-9fbc371dd3c7.png)

### Additional information

It should be responsive in every  device 
i would like to work on this !

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by SteveSayantan** [comment]
## Hints for Solving This 🦄:
- Setup your clone repo as per the [Setup Guidelines](https://github.com/IAmTamal/Milan/blob/5da6529674eea313910d8c647273223eccf37810/rules/FrontendSetup.md)
- Navigate to this [file](https://github.com/IAmTamal/Milan/blob/5da6529674eea313910d8c647273223eccf37810/src/styles/Footer.css)
- Inside the `.btn-hover` class, you have to remove two properties (Figure it out by yourself 😎) and add some `padding` to it.
- You are done !! 

 You got it right . Open Source is for everyone 🤗 .

**Comment by SteveSayantan** [comment]
I would request the maintainer to label this issue as a Good-First one!!

**Comment by shashank-2310** [comment]
Please assign me this issue.
