### ISSUE TITLE
Improper handling of the Promise returned by mongoose save() method

### ISSUE THREAD

**Issue by SteveSayantan** [IAmTamal/Milan#493]
### Description

In [User.js](https://github.com/IAmTamal/Milan/blob/5da6529674eea313910d8c647273223eccf37810/server/routes/User.js) , the promise retuned by the mongoose save() method is not taken care of at all.

Therefore, even if the promise gets rejected, the catch block is unable to notice it and the execution does not stop.

The same problem is there in [Clubs.js](https://github.com/IAmTamal/Milan/blob/5da6529674eea313910d8c647273223eccf37810/server/routes/Clubs.js)

Due to this bug, I was able to create an user with random info and missing fields using the API `https://milan-server.adaptable.app/user/register` ( As shown in the screenshot). 

### Screenshots

![Bug](https://user-images.githubusercontent.com/92118155/196054276-f63d244c-9a20-491c-bd1a-d4374b601817.JPG)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Awesome spot @SteveSayantan , thanks for making the project's backend better. You can work on the issue !

**Comment by SteveSayantan** [comment]
Thanks for the compliments @IAmTamal 😇
