### ISSUE TITLE
The links to the Guideline Files do not work properly

### ISSUE THREAD

**Issue by SteveSayantan** [IAmTamal/Milan#494]
### Description

The links in the `Guidelines to be followed` section in [README.md](../blob/main/README.md) do not navigate to the proper files.

### Additional information

This can be a good beginners-friendly issue.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by LeGrandMAG** [comment]
@SteveSayantan , I would like to work on this issue, would you mind assigning it to me ?

**Comment by SteveSayantan** [comment]
> @SteveSayantan , I would like to work on this issue, would you mind assigning it to me ?

I am not authorized to do that 😥

**Comment by IAmTamal** [comment]
@LeGrandMAG Go for it , make sure all the links are working fine !
