### ISSUE TITLE
No mention of the jwt secret key in BackendSetup.md 

### ISSUE THREAD

**Issue by SteveSayantan** [IAmTamal/Milan#495]
### Description

A `JWT_SECRET` key has to be set up in the .env file while running the server locally. But it is not mentioned [here](../blob/main/rules/BackendSetup.md) .

### Additional information

This can be a good Beginners-Friendly issue.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by amit-ksh** [comment]
Can I work on this issue?

**Comment by IAmTamal** [comment]
@amit-ksh go for it !
