### ISSUE TITLE
Creating club events failed due to bug in api 

### ISSUE THREAD

**Issue by Tineshnehete** [IAmTamal/Milan#499]
### Description

Hey there when we loging as club and try to add new event it fails to add new event. Its actually a bug from the api .  Api gets time out on making the api request to endpoint `/club/createevent`

### Screenshots

![Annotation 2022-10-18 230301](https://user-images.githubusercontent.com/74779225/196503555-a1dd2dda-c137-4e87-8ca2-b0ae05aafb47.png)

### Additional information

I Am Intrested to fix it . Please assign it to me :) 

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by SteveSayantan** [comment]
Hello @Tineshnehete , once you are assigned with this and start ,

**Comment by SteveSayantan** [comment]
I thought this was too trivial to be addressed by opening a separate issue. That's why I asked you as you will be working with backend.

**Comment by IAmTamal** [comment]
@Tineshnehete , we can work on #501 and this issue all together ! 

- You can start working on it , and make a single PR adressing the 2 issues.
