### ISSUE TITLE
React App Contact page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#50]
## I want to have a Contact page
 
---
 
## Guidelines 🔐

- [x] I have read the **[Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Contributing.md)** 🔐
- [x] I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**I want you to write the code so that we can have a CONTACT PAGE following the below provided design , it should be responsive too**

### **Design : [Figma Design](https://www.figma.com/file/xIKk4PMTp9VCMDekTct9cj/Contact-Page---Milan?node-id=0%3A1)**

**Make a `ContactUs.jsx` here :**
![image](https://user-images.githubusercontent.com/72851613/152670968-ce35d2b0-1e2b-4db8-af5d-943eb1e26f6f.png)

**Make a `ContactUs.css` here :**
![image](https://user-images.githubusercontent.com/72851613/152670986-beef6f03-32d6-4623-8a8c-7dbf8f915741.png)

**Make sure you follow all the GUIDELINES !!**

### **Category --> MEDIUM (3 Days)**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.

**Comment by Aniket-508** [comment]
@IAmTamal I wanted to work on this under JWOC.

**Comment by IAmTamal** [comment]
Go Ahead . make sure to follow the guidelines strictly.
Make the page as accurate as possible relative to Figma design
In case of doubts tag me in `#milan` channel.

Assigning  to you @Aniket-508

**Comment by Aniket-508** [comment]
![Milan](https://user-images.githubusercontent.com/71957423/152733678-f3decdb2-2ac0-42de-a54a-a3502fc8aa00.JPG)

You want to add a contact page here right? @IAmTamal

**Comment by IAmTamal** [comment]
> ![Milan](https://user-images.githubusercontent.com/71957423/152733678-f3decdb2-2ac0-42de-a54a-a3502fc8aa00.JPG)
> 
> You want to add a contact page here right? @IAmTamal

Yes , @Aniket-508
