### ISSUE TITLE
Dotenv config after accessing env variable 

### ISSUE THREAD

**Issue by Tineshnehete** [IAmTamal/Milan#501]
[this](https://github.com/IAmTamal/Milan/blob/5da6529674eea313910d8c647273223eccf37810/server/index.js) file . 

Clearly, the `dotenv.config()` method is called at line 12. However, the port variable uses `process.env.port` at line 8, which may result in some bug in production. It would be awesome if you can shift the `dotenv.config()` just after line 4 to eliminate any possible confusion. 

All the best for your contribution 😄 , Happy Coding!!

_Originally posted by @SteveSayantan in https://github.com/IAmTamal/Milan/issues/499#issuecomment-1284355891_

**Comment by amit-ksh** [comment]
Hey @Tineshnehete @IAmTamal! Can I fix this issue.

**Comment by Supratim30** [comment]
Hey, would like to work on this. Please assign it so I can proceed.
Thank you

**Comment by Tineshnehete** [comment]
Closed with #499
