### ISSUE TITLE
Club cards is overflowing ! 

### ISSUE THREAD

**Issue by rohitroy-github** [IAmTamal/Milan#502]
### Description

@IAmTamal in the screenshot I attached below, you'll find that the cards from the [Club] section/ page is overflowing over the footer. If the issue is relevant, then assign it to me, I'll try to fix it. 

### Screenshots

![image](https://user-images.githubusercontent.com/68563695/197040360-1311b377-314c-4cae-94f4-98453020245e.png)

![image](https://user-images.githubusercontent.com/68563695/197040837-471a1b65-c869-49e8-8fe0-11a801530804.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by rohitroy-github** [comment]
@IAmTamal, I just checked the issue and it's fixed. So if it's alright then you can close this issue. 
https://milaan.vercel.app/display/clubs

![image](https://user-images.githubusercontent.com/68563695/197332746-3937a0b3-3b21-4708-bb93-03cd39d7f3fc.png)

**Comment by IAmTamal** [comment]
@rohitroy-github , the issue is not fixed. 

i have deleted some cards which had some slangs in it. Now that there are less cards it is looking like it's fixed. 

If there are more cards again (you can get more cards by registering as a club with random details for testing) it will break again.

**Comment by rohitroy-github** [comment]
Cool, I'm looking into it.
