### ISSUE TITLE
React components and pages uses class attribute instead of className

### ISSUE THREAD

**Issue by amit-ksh** [IAmTamal/Milan#503]
### Description

Multiple components and pages of Milan frontend uses the `class` attribute instead of `className`  which raise warning in the browser console.

### Screenshots

![Desktop-screenshot (2)](https://user-images.githubusercontent.com/91947037/197152645-45bff316-24fc-42b8-8fc8-811f45cd6f6f.png)

![Desktop-screenshot (1)](https://user-images.githubusercontent.com/91947037/197152661-c75e5a1f-22df-41c5-8ae7-34d02ef2ad3b.png)

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Looks like a small bug, make sure you fix it for all the pages and **nothing must break** in the process.
