### ISSUE TITLE
Events page has internal error

### ISSUE THREAD

**Issue by RishikaKant** [IAmTamal/Milan#504]
### Description

The events page of the website has some errors and is not opening

### Screenshots

<img width="952" alt="image" src="https://user-images.githubusercontent.com/76899370/197164105-af3f4132-3d9b-424e-8fde-77707860418a.png">

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by udaykahar** [comment]
Hi , I can work on this, can you please assign me?

**Comment by IAmTamal** [comment]
Hello @RishikaKant The events page can only be accessed if someone is logged in ! 

For now it is showing Internal server error - can you make it so that if someone who is **not logged in** tries to log in we show them a toast saying `Please log in before viewing the events` and redirect them to the user's login page ?

**Comment by RishikaKant** [comment]
Yes, sure!

**Comment by Dojeto** [comment]
can I work on this issue?

**Comment by IAmTamal** [comment]
![image](https://user-images.githubusercontent.com/72851613/197375583-b04de564-41d4-4494-8e4f-7e54b8314bbb.png)
Please take a look at the assignees before asking to get assigned - i would like everyone to get a fair chance !

**Comment by Dojeto** [comment]
it's been more than 2 days that's why I asked, I don't have any wrong intentions sorry if I made any mistakes :)

**Comment by IAmTamal** [comment]
@RishikaKant Are you working on it ? 
Do reply to this message if yes, and do make a PR within the next 2 days please !

**Comment by RishikaKant** [comment]
Hey!
I tried doing it but I'm finding it a little hard as I'm not very familiar with the backend
You can assign it to someone else. Sorry.
