### ISSUE TITLE
Products card looks different

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#507]
### Description

- Make sure the products card are looking the same as the design that was provided by the UI/UX team.
- Acess the figma file [here](https://www.figma.com/file/SueBucEpihH1vPaU3iOUn1/Milan-Shop?node-id=0%3A1)

## How it should look : 

![image](https://user-images.githubusercontent.com/72851613/197348035-13d4c4d1-ac2c-4764-9d38-fb2b6d375c72.png)

## How it looks : 

![image](https://user-images.githubusercontent.com/72851613/197348060-89bf9b6a-8928-45e6-9336-b975260406dd.png)

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?

**Comment by IAmTamal** [comment]
Go for it @Kishore-abhimanyu !

**Comment by Aribaskar-jb** [comment]
Can you assign me this issue

**Comment by IAmTamal** [comment]
> Can you assign me this issue

![image](https://user-images.githubusercontent.com/72851613/197375530-7dad5a9a-fd33-4380-bd9f-82e3b4cb8b2d.png)

Always check this before asking for assignment.

**Comment by IAmTamal** [comment]
@Kishore-abhimanyu Are you working on this ?

**Comment by Kishore-abhimanyu** [comment]
Will create a new pr with PR details soon
