### ISSUE TITLE
[FEATURE] Footer changes for mobile

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#508]
### Description

- The footer currently has a text `With Milan we aim at bringing all the various .....` for mobiles and it looks weird.
- The socials icon are also not centered for mobile.

Here are some changes i want : 

- Hide the  `With Milan we aim at bringing all the various .....` for mobiles.
- Inplace of it give a centered header `Check out our socials` 
- And give the socials icons centred below it !

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/197348224-aa7eca2b-ecc2-4f6a-8d8e-eeb6638f3f44.png)

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by simonpankovski** [comment]
Hey, can I work on this issue?

**Comment by IAmTamal** [comment]
Sure, go ahead !
