### ISSUE TITLE
Updates to Bug issue templates

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#509]
### Description

- For docs, features we have a title by default of `[DOCS] <description>`
- I want the same for the bugs too. Make the title `[BUGS] <description>` for the bug issues.
- In the dropdown change `None` to `No, someone else can work on it`  **(Screenshot 3)**
- Replace `Have you checked if this issue has been raised before?` with `Have you checked for similar open issues ?` **(Screenshot 4)**

## Other issues : 
![image](https://user-images.githubusercontent.com/72851613/197348590-0e9ee5de-679b-45b1-bf39-a36f128cefe1.png)

## Bugs : 
![image](https://user-images.githubusercontent.com/72851613/197348607-7548c36d-e007-4e96-869c-1c0db391c193.png)

## Screenshot 3
![image](https://user-images.githubusercontent.com/72851613/197348695-aea46590-0100-4d9b-a0e3-7ecd68badbc4.png)

## Screenshot 4
![image](https://user-images.githubusercontent.com/72851613/197348756-4469fcba-6506-4930-87aa-0014a4e45961.png)

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by amit-ksh** [comment]
I want to work on this issue?

**Comment by IAmTamal** [comment]
Go for it @amit-ksh  !
