### ISSUE TITLE
Events page > Card issue ! 

### ISSUE THREAD

**Issue by rohitroy-github** [IAmTamal/Milan#513]
### Description

There is some issue with the card present on the Events page ! There might be some issue regarding overflowing as well. If it's relevant enough, assign it to me, I have a check and make it look better ! 

### Screenshots

![image](https://user-images.githubusercontent.com/68563695/197375044-d5c8d2ad-ed0e-4a4c-99c9-a27bc1220ed0.png)

![image](https://user-images.githubusercontent.com/68563695/197375053-c33bb99f-b593-4808-bc55-f7fccd129cde.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
@rohitroy-github , closing this issue and we can work on this + clubs card **all together** in #502

**Comment by rohitroy-github** [comment]
Got it, I'm working on it !

**Comment by rohitroy-github** [comment]
@IAmTamal > I made a PR, it's working all right now. Have a check & merge !
