### ISSUE TITLE
[FEATURE] Page of Data Visualization

### ISSUE THREAD

**Issue by Gaurav-jo1** [IAmTamal/Milan#515]
### Description

Depth of <b>NGOs</b> and the <b>Club's</b> <b>goal</b> for the user/donor, <b>Data Visualization</b> can help in many ways.

⚪ By showing the level of carbon emission, hunger, animal death, marine life, education etc, in the form of graphs, charts, and world maps.

![2019071010A](https://user-images.githubusercontent.com/93304640/197408645-7da92f96-7854-442a-9a4e-c3907ac2f5dc.png)

⚪ By utilizing the APIs for example carbon emission we can catch eyes by showing them <b>Before</b> and <b>After</b> Charts and let the user/donor know that a little amount can affect a lot

![sdgs-list-en](https://user-images.githubusercontent.com/93304640/197409062-37b691a2-68c0-42de-8254-8ae8b32757ff.jpg)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Hello @Gaurav-jo1 , i don't think we have any fields to show ` level of carbon emission, hunger, animal death, marine life, education etc,` nor even are those implemented via our project

**Comment by Gaurav-jo1** [comment]
Can I work on a prototype

**Comment by IAmTamal** [comment]
> @IAmTamal Can I work on a prototype

You can, but i don't need anything related to `level of carbon emission, hunger, animal death, marine life, education etc,` other than that, what are the things that you want to make ?

**Comment by Gaurav-jo1** [comment]
I am gonna try anyway, let's see how it goes.
There's always something new to learn
