### ISSUE TITLE
[BUGS] Donate page needs work

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#517]
## Change 1

Take a look at **Screenshot 1**, you will notice the UI difference between Clubs page and the Donate Page
- I want the Fonts, color of Fonts to be same
- I want them to look similar, but don't change the texts (contents) 

## Change 2

Take a look at **Screenshot 2**, you will notice a overflow of cards
I want them to fixed for the page

## Change 3

Take a look at the **Screenshot 3**, you will notice that if the cards are not loaded it's empty, can we add a spinner so that it shows that the cards are loading ? It will be a good UX*

## Change 4

- I want folks only to be able to see the page if they are logged in.
- You can check for cookies, if they are not logged in, the cards must be hidden
- a toast must come at the top right corner saying `Please log in before donating`
- The redirect them to the User login page.

## Screenshot 1

![image](https://user-images.githubusercontent.com/72851613/197461042-6e69dd23-be81-4059-a3f6-edac14d89585.png)

## Screenshot 2

![image](https://user-images.githubusercontent.com/72851613/197461326-1161b815-e954-4bab-b3d9-59841e372172.png)

## Screenshot 3

![image](https://user-images.githubusercontent.com/72851613/197462180-f334724a-fbe7-4940-810c-c445480055b8.png)

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by vancassa** [comment]
Hi, may I work on this?

**Comment by IAmTamal** [comment]
> Hi, may I work on this?

GO for it !

**Comment by vancassa** [comment]
@IAmTamal can you elaborate on Change 2? I don't understand what you mean by "overflow of cards".

**Comment by IAmTamal** [comment]
@vancassa It's like there is no gap between the cards and the footer and it looks like the cards might overflow into the footer 

![image](https://user-images.githubusercontent.com/72851613/197933080-92d3baef-32d1-4a36-b930-384b6b0757a1.png)

Also we'd need a little bit more gap here : 
![image](https://user-images.githubusercontent.com/72851613/197933132-bd99aa09-e7a2-4f71-a92f-0b1c2432d546.png)

**Comment by IAmTamal** [comment]
The reason i reverted was the toast was not working, and we were not re-directed properly
