### ISSUE TITLE
[BUG] Multiple "Logging You In" pop-ups if Log In button is clicked more than once

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#523]
### Description

After providing the credentials, if the user clicks multiple times on 'Log In'  button, it generates a bunch of 'Logging You In' pop-ups.

### Screenshots

![Screenshot_20221013-140202](https://user-images.githubusercontent.com/92118155/195548558-2bc50ba9-aa96-450e-b216-d0feff9d7900.jpg)

### Possible Solution

After clicking on the 'Log In' button once, it should be disabled until receiving response from the server

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by IAmTamal** [comment]
- Make sure you implement functionality for both Users and Clubs login
- Do make a PR once done, we can always review it ! 

@the-macson

**Comment by the-macson** [comment]
Okay
