### ISSUE TITLE
[BUGS] Shop page Mobile responsiveness

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#525]
### Description

- if you take a look at the screenshot 1 you will notice that there is an image, above the `Welcome to our store !`, remove that for mobiles
- The paragraph `We aim at selling.....` has a less width in mobiles, make it so that more amount of screen space is covered in terms of width !

## Screenshot

![image](https://user-images.githubusercontent.com/72851613/198191322-4bb6eb2c-1090-4455-99dc-d77f2b971ecc.png)

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by the-macson** [comment]
Can you assign me this issue @IAmTamal

**Comment by srijoy-paul** [comment]
Hey @IAmTamal I would love to work on this, Can you assign me this ?

**Comment by IAmTamal** [comment]
@srijoy-paul Go ahead !
