### ISSUE TITLE
[FEATURE] Add a Products Carousel

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#526]
### Description

- In the shop when you look at the home page we have some products card under the `PRODUCTS` section 
- I want that to be in a carousel format such that only 1 card is visible at a time for mobiles
- And 4 cards visible at a time for desktop
- I highly recommend any library you'd need, also you can take help of [ShopCoders](https://github.com/IAmTamal/ShopCoders)

## To be made : 

https://user-images.githubusercontent.com/72851613/198191969-b1256bf2-c3c6-447e-b85d-ec146ece46bb.mp4

## At present : 

![image](https://user-images.githubusercontent.com/72851613/198192034-3f72c353-f192-40d4-972d-dd635201a414.png)

### Additional information

⚠ Do complete this issue within 4-5 days of assignment !

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by senali-d** [comment]
@IAmTamal I would love to work on this featue.

**Comment by IAmTamal** [comment]
Go for it @senali-d  !

**Comment by Aadarsh805** [comment]
Is this task still assigned or can I work on this

**Comment by IAmTamal** [comment]
> Is this task still assigned or can I work on this

You can work on it !

**Comment by nkirukka** [comment]
@IAmTamal can I please know the app  you screen recorded with to show mobile screen like that? Thanks
