### ISSUE TITLE
[FEATURE] Taglines in Cards

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#528]
### Description

- Currently the cards has a description as a result, we have different height for different cards
- Make sure the description is not visible in the cards, just the **tagline** is visible
- Make sure all the cards has equal height, no cards must be greater than another

## Present change : 

![image](https://user-images.githubusercontent.com/72851613/198193027-214e0e59-9462-430e-8fba-ca86dba2c87b.png)

## What we need : 

![image](https://user-images.githubusercontent.com/72851613/198193098-eafa3f5b-d2a2-4191-be94-2dcc45a0967f.png)

### Additional information

- You might need to get the data from Backend, so maybe write server side codes too 
- You need to get this done by like 7days (MAX)

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by the-macson** [comment]
Can you assign me this issue @IAmTamal

**Comment by devwithsubhrajit2002** [comment]
Please assign me this task @IAmTamal I will do it right within one day.

**Comment by IAmTamal** [comment]
@the-macson , go for it !

**Comment by the-macson** [comment]
okay
