### ISSUE TITLE
[BUGS] Events page placeholders

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#530]
### Description

- If you take a look at the Events page you will see that we have placeholders enabled for desktops too.
- I want the placeholders only for mobile view.
- I want Labels to be available for the Desktops ! 
- Also can we center the `Create` button for the mobile and make it a bit larger too ? 

## Changes to be made : 

![image](https://user-images.githubusercontent.com/72851613/198675544-b92ec63c-4343-45c7-9505-c0b73eda2270.png)

![image](https://user-images.githubusercontent.com/72851613/198675950-7e240cef-e516-4052-ad1d-b78488024aa8.png)

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by devwithsubhrajit2002** [comment]
@IAmTamal  assign the task  to me. I will get it done.

**Comment by srijoy-paul** [comment]
Hey @IAmTamal I would love to work on this, and will try to complete asap.
Can you assign me this task?

**Comment by IAmTamal** [comment]
Go for it @devwithsubhrajit2002 

@srijoy-paul , we are trying to give everyone a fair chance !

**Comment by AbhiPatel10** [comment]
I think this issue is solved so we can close this issue.

**Comment by IAmTamal** [comment]
> I think this issue is solved so we can close this issue.

This issue was not created TBH
