### ISSUE TITLE
[FEATURE] Product detail page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#537]
### Description

- We would like to have a product detail page
- Whenever someone clicks on the product we would show them the product details page
- The data can be static for now

FIGMA DESIGN : https://www.figma.com/file/EzubF1gxtg4ScG6k7FgdEL/Shop-detailed-page---Milan?node-id=0%3A1

### Additional information

- Try making it similar as  the design provided

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by rohitroy-github** [comment]
@IAmTamal, I would like to give it a try. If it's okay, assign it to me.

**Comment by IAmTamal** [comment]
> @IAmTamal, I would like to give it a try. If it's okay, assign it to me.

Go ahead !

**Comment by rohitroy-github** [comment]
Hey @IAmTamal I made a PR with the new page designed. Sorry for the delay, I was busy with exam stuffs as you might already know.

**Comment by 0papi** [comment]
Please has this been worked on?
