### ISSUE TITLE
[FEATURE] Clubs card page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#538]
### Description

- We would like a clubs details card
- Whenever someone clicked on the clubs card, we should be redirected to a new page
- In that page we can have static data for now !

FIGMA DESIGN : https://www.figma.com/file/19FIHLVUm9PajijYFDzUvn/Club-Page?node-id=0%3A1

### Additional information

- Try and make it as similar as possible

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by codewithrabeeh** [comment]
By club card you mean this [below attached] right? @IAmTamal 
![image](https://user-images.githubusercontent.com/65481473/199957043-7d64b3f3-ffe1-4f8f-aeed-8b4d577f7ce7.png)

**Comment by IAmTamal** [comment]
All images are in the Figma file you can export those from there ! 

![image](https://user-images.githubusercontent.com/72851613/200127045-34a38667-4bde-4fa1-b4fa-8b75632110da.png)
