### ISSUE TITLE
UI/UX - React App Footer Refactor

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#54]
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠

**In the Footer i want a new button**
![image](https://user-images.githubusercontent.com/72851613/152851887-29d189da-d601-4704-9226-720f5263ef69.png)

**Code :**
> `font-family: Mulish;
font-style: normal;
font-weight: bold;` 

**I want it here ⤵**
![image](https://user-images.githubusercontent.com/72851613/152852006-8220cdaf-91c9-4705-864a-219e8484a674.png)

**And also i would like to move the RIGHT links a bit to the left 🔽**
![image](https://user-images.githubusercontent.com/72851613/152852966-f50d81f2-35fd-4044-88cd-41b74bff3746.png)

### MOBILE RESPONSIVENESS 📱

**I want these links to be invisible in Mobiles , i just want the REPORT button to be visible instead**
![image](https://user-images.githubusercontent.com/72851613/152853080-28f1ea44-3114-411e-8e0a-aa117afd367d.png)

  
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by soumali28** [comment]
I want to contribute to the issue under JWOC

**Comment by IAmTamal** [comment]
Go for it , 

Here's the design : [Figma Design](https://www.figma.com/file/sPVLhYppzhCzYYbqSmlebm/HomePage---Milan?node-id=0%3A1)

![image](https://user-images.githubusercontent.com/72851613/152918513-e22e5d74-ec44-4aab-84fe-80f540021146.png)

**You can go to this design , click on the button i made and look at the font family , colors etc i have used.**
