### ISSUE TITLE
[BUGS] Attend Event Button alignment in Events Card

### ISSUE THREAD

**Issue by codewithrabeeh** [IAmTamal/Milan#544]
### Description

In milaan.vercel.app/display/events page, the card button is aligned poorly. 

### Screenshots

![image](https://user-images.githubusercontent.com/65481473/199742376-82001e01-e983-4779-b495-2c56eaeb5bec.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Go ahead @codewithrabeeh  !
