### ISSUE TITLE
[BUGS] Products card looks different

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#550]
### Description

- Make sure the products card are looking the same as the design that was provided by the UI/UX team.
- Acess the figma file [here](https://www.figma.com/file/SueBucEpihH1vPaU3iOUn1/Milan-Shop?node-id=0%3A1)

## How it should look : 

![image](https://user-images.githubusercontent.com/72851613/197348035-13d4c4d1-ac2c-4764-9d38-fb2b6d375c72.png)

## How it looks : 

![image](https://user-images.githubusercontent.com/72851613/197348060-89bf9b6a-8928-45e6-9336-b975260406dd.png)

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by hariscs** [comment]
assign it to me

**Comment by Aadarsh805** [comment]
i'd like to work on this
question: is this how it's supposed to look
![image](https://user-images.githubusercontent.com/95094057/205510658-1c13c24a-1208-45bb-9397-e76f120593cb.png)

**Comment by IAmTamal** [comment]
> assign it to me

Go for it !
