### ISSUE TITLE
[BUGS] Home page buttons are not working

### ISSUE THREAD

**Issue by codewithrabeeh** [IAmTamal/Milan#554]
### Description

Home page sign up buttons and explore the shop button are not working.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by AbhiPatel10** [comment]
Navbar Signup Button is also Not Working so please also check that out.
