### ISSUE TITLE
[BUGS] Navbar is Not Responsive

### ISSUE THREAD

**Issue by AbhiPatel10** [IAmTamal/Milan#555]
### Description

Navbar is Note Responsive in the between 992px to 1000px

### Screenshots

![image](https://user-images.githubusercontent.com/76242769/208165980-d0640684-7f2a-4aa1-afcd-02f11aa2cf83.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Go ahead !
