### ISSUE TITLE
[BUGS] Shows two navbar in Shop Page

### ISSUE THREAD

**Issue by AbhiPatel10** [IAmTamal/Milan#556]
### Description

Bug -- Shows two navbar in Shop Page

Solution -- There must be only one navigation bar.

### Screenshots

![image](https://user-images.githubusercontent.com/76242769/208166745-35d95872-7697-4ea9-b01f-fbff4f2bb85c.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by AbhiPatel10** [comment]
Also same for the Registration Page

**Comment by IAmTamal** [comment]
> Also same for the Registration Page

Some page has duplicate navbar, you can remove the duplicate navbar that are coded inside the files.

**Comment by AbhiPatel10** [comment]
Okay
