### ISSUE TITLE
[BUGS] Add Footer in All Pages

### ISSUE THREAD

**Issue by AbhiPatel10** [IAmTamal/Milan#558]
### Description

Footer is Only available in just Home page. We need to add Footer in all page

We have to just Remove That Footer Component From the Home page and add that Component in App.jsx page. this will automatically add footer in All page just like Navbar.

@IAmTamal  Please add Good First issue label and let the new Contributors can work on it.

### Screenshots

![image](https://user-images.githubusercontent.com/76242769/208258047-26568ecf-ed22-49f4-8aa5-eb7d860a4e01.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by imvedanshmehra** [comment]
Hi @AbhiPatel10, this seems a legit issue, not sure if it is a bug though. I can look into it.

**Comment by AbhiPatel10** [comment]
Yes it's not bug, it's my mistake to add into bug label...

@imvedanshmehra please go ahead.
