### ISSUE TITLE
[BUGS] Exclamation Mark misplaced

### ISSUE THREAD

**Issue by priyanshi-git** [IAmTamal/Milan#564]
### Description

In the "Events" page, the 'Events Happening Now !' heading has it's exclamation mark in the next line, which makes it look odd.

### Screenshots

![image](https://user-images.githubusercontent.com/82112540/209363892-47898a6c-5f76-4cdd-acb5-f072105aed03.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by imvedanshmehra** [comment]
Is it happening for all screen sizes or for any specific size?

**Comment by IAmTamal** [comment]
Hmm maybe we can change the width of the whole thing. I don't recommend removing the `!` completely

**Comment by Sambalicious** [comment]
It should work fine if we reduce the font-size a little

**Comment by IAmTamal** [comment]
Sounds good !

**Comment by Sambalicious** [comment]
if @priyanshi-git doesn't mind, I can take it up.

**Comment by AbhiPatel10** [comment]
@Sambalicious Go for it.
