### ISSUE TITLE
[BUGS] Auth page layout consistency

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#566]
### Description

- Consistency across all the auth pages.
- I want the design to be consistent across all the authentication pages (font. font size, img)
- Follow the design of the [User login page](https://milaan.vercel.app/user/login).
- Make sure it's responsive across all devices

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/210153104-c5de3131-f292-4277-bfe3-1837c9537651.png)

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by Sambalicious** [comment]
is there a figma design link for this?

**Comment by IAmTamal** [comment]
Unfortunately there isn't - you can copy fonts, size, color, font family from the codes for `user/login`

**Comment by pathakkar01** [comment]
Hi @IAmTamal can you please assign this issue, Would like to work on it ?

**Comment by IAmTamal** [comment]
Go ahead !

**Comment by pathakkar01** [comment]
Thanks @IAmTamal, Will work on this and get back you ASAP.

**Comment by pathakkar01** [comment]
Hey @IAmTamal, As much as I know react, index.html file should be in public folder, In this repository it is base folder, so while running npm Start it gives the below error (first screenshot). please correct if I am doing any thing wrong, And one more thing Package.json file is not contain the npm start script, So for now I have added that manually (2nd screenshot), so can you tell me, is there any other way to run the react app? as I am fairing new to react? 

![image](https://user-images.githubusercontent.com/65023862/211197396-b27c7e6a-5cdd-4b56-b19e-11bc2dc5f958.png)

![image](https://user-images.githubusercontent.com/65023862/211197332-4779f7e6-3e62-49b7-bc34-20ca3c830086.png)
