### ISSUE TITLE
[BUGS] Removing extra labels from the issue templates

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#567]
### Description

- Remove the `hacktoberfest` labels from the issue templates
- Make sure it is removed for all the types of issues.

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by AbhiPatel10** [comment]
I want to work on this. can you please explain how can i do this ?

**Comment by adityasharma7** [comment]
@AbhiPatel10 

You could find the issue template here:
https://github.com/IAmTamal/Milan/tree/main/.github/ISSUE_TEMPLATE

Navigate to all the files individually, remove `hacktoberfest` label from it
https://github.com/IAmTamal/Milan/blob/main/.github/ISSUE_TEMPLATE/bug.yml

**Comment by AbhiPatel10** [comment]
First ever I Check .github file 😅, Thank You @adityasharma7 bhai I got to learn new thing today 🚀, 

I have made PR #573 Please check and let me know if need any changes.

**Comment by adityasharma7** [comment]
Glad to know that!!
Keep learning 🚀
