### ISSUE TITLE
[FEATURE] Create a wrapper component for Helmet for reduce code duplication

### ISSUE THREAD

**Issue by Sambalicious** [IAmTamal/Milan#570]
### Description

I notice a lot of code duplication, especially when using the Helmet component from react-helmet-async. So I was thinking I can create a wrapper reusable and easily extensible component that solves this issue while maintaining DRY principles.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Yeah sure, this sounds like a real good feature !
Go ahead if you want to work on it !
