### ISSUE TITLE
[FEATURE] I want to add the text selection color property

### ISSUE THREAD

**Issue by mohammadshaad** [IAmTamal/Milan#571]
### Description

I want to add the color on selection of text property to the website. Basically, the text background will get the same color as that of the theme of the website. Kindly assign me this issue so that I can start working on it.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Hi there @mohammadshaad , can you perhaps elaborate what your issue actually is ? 
Like i donot understand it at all. 

Please consider : 
 - bigger desc
 - Screenshots/screen recorded
