### ISSUE TITLE
[FEATURE] Footer

### ISSUE THREAD

**Issue by rohinish404** [IAmTamal/Milan#576]
### Description

how about adding a footer to the website with the application name and the same links that are in the navbar.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by rohinish404** [comment]
i can work on this if it gets approved:)

**Comment by rohinish404** [comment]
Yeah, so i was thinking maybe we can add logo and the 4 links that are in the navbar to the footer. Also there is no link to the github of the project so we can also add that in the footer along with other links(instagram,twitter,etc.). What do you think about this?

**Comment by rohinish404** [comment]
There's already a designed footer in the repo. What things do you want to change in this?
<img width="1435" alt="Screenshot 2023-01-26 at 11 34 00 PM" src="https://user-images.githubusercontent.com/92542124/214914009-533cfd8b-b77a-4951-9f8a-358189eff32b.png">

**Comment by IAmTamal** [comment]
@rohinish404 Let the report button stay as it is
- The left side can be minimised ,to `We are an Opensource product, feel free to contribute` and then add the Gh link
- At the end, center we can add something like (replace with Milan) : 

![image](https://user-images.githubusercontent.com/72851613/215270146-b2791d8c-9dd1-468c-a7bf-f65f337d7326.png)

**Comment by rohinish404** [comment]
okay..so i made few changes. How's it's looking?
<img width="1435" alt="Screenshot 2023-01-29 at 12 48 20 AM" src="https://user-images.githubusercontent.com/92542124/215286831-6cf80d54-7738-45b9-ab48-9792a54eb532.png">

**Comment by rohinish404** [comment]
How about centering the join us column so that it appears directly above the links? 
And should i make the background white?

**Comment by IAmTamal** [comment]
> How about centering the join us column so that it appears directly above the links? And should i make the background white?

Yep the centering is needed, make a PR too, we can review that way easily ! 
Also i think the dark BG is good so that people knows that this is a footer !

**Comment by rohinish404** [comment]
Yeah sure!! I'll make a pr after centering that portion:)
