### ISSUE TITLE
[OTHER] : Issue Template fixes

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#578]
The `additional information` section in the issues makes no sense, and TBH no one uses it ever
![image](https://user-images.githubusercontent.com/72851613/215270338-12d2783a-cd99-4eda-b55b-9f92ee7f65e8.png)

Can this be removed from all the issue templates ?

**Comment by haszankauna** [comment]
Please I'll like to be assigned this issue.

**Comment by IAmTamal** [comment]
Go ahead @haszankauna !
