### ISSUE TITLE
[BUGS] Mobile view for navbar

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#583]
### Description

- We need some spacing for the navbar in mobile view
- Make sure the font is properly sized and visible too
- It must be centered

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/216163170-5ab0e67f-4a61-4ea3-8ded-9c24479f084b.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by haszankauna** [comment]
Hello @IAmTamal can you please explain the issue further. I'll also like to work on this

**Comment by Cypher-aman** [comment]
Is that what you want? If so, please assign this issue to me. I would surely like to fix it.
![Screen Shot 2023-02-04 at 01 53 54](https://user-images.githubusercontent.com/71575102/216704531-cc80f02c-082c-4a96-b4e8-823f89768651.png)

**Comment by Cypher-aman** [comment]
Is that what you want? If so, please assign this issue to me. I would surely like to fix it.
![rsz_1rsz_screen_shot_2023-02-04_at_015354](https://user-images.githubusercontent.com/71575102/216705394-053eeef8-ad4e-4b40-9a6d-50e886c9b3e5.png)

**Comment by IAmTamal** [comment]
@haszankauna The navbar looks bad when in mobile view, you can try out for yourself.
Increase the vertical gaps. 

Also we might need to fix this weird behaviour, where the navbar would push down the content when not scrolled down.

https://user-images.githubusercontent.com/72851613/217580771-f9b51b6a-a6d1-420f-abfb-4ba834f08606.mp4

**Comment by rakesh-venkata** [comment]
Hello @IAmTamal  ,Assign the task to me.I can fix it.
