### ISSUE TITLE
[BUGS] Register Button Turns White While Focusing

### ISSUE THREAD

**Issue by codewithrabeeh** [IAmTamal/Milan#584]
### Description

On the user registration page, the register button's bg color turns white while focusing.

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/65481473/216215324-715996ec-c4b6-4920-b9d1-d1106ae05153.gif)

### Additional information

I saw the class name of the register button is `login-btn` is it by mistake? when I give it `register-btn` its background color turns red to blue. Which is it's original color? for reference see line **261** in `src/pages/user/UserRegister.jsx`

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Great spot @codewithrabeeh  That sure is an acessibility issue. When you would hover over the button it would have a minimal whitish effect. Can we fix this for focus ? 

Also when we are focusing on the input fields they turn out to have a blue color box shadow, can we make it the same color as our theme  `#e26959`

![image](https://user-images.githubusercontent.com/72851613/216526568-984615c5-9d2e-49f5-94a0-7923081d5eca.png)
