### ISSUE TITLE
[BUGS] "Sign Up" button still shows after user signs In.

### ISSUE THREAD

**Issue by temidayo-falomo** [IAmTamal/Milan#587]
### Description

I would like to work on the issue i described in the Title, where the button to sign up is still shown after user signs-up.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Go ahead @temidayo-falomo , from the next time please do add a screenshot despite of how simple the issue might be. Hope you understand.

Also, maybe we can do this once user is logged in.
![image](https://user-images.githubusercontent.com/72851613/216524977-369618d2-dd5e-41ff-85be-693bbe901c1c.png)

**Comment by temidayo-falomo** [comment]
Yeahh, got it! Thanks✅
