### ISSUE TITLE
[BUGS] Home page responsiveness 

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#589]
### Description

- The home page is responsive for mobile view but the other screens are not flexible yet
- Apply proper stylings such that the page looks good in all device sizes
- Make sure to write proper CSS, with appropriate classnames

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/216545211-6cc76df0-e351-4ea8-b49f-a601dbfbc0c8.png)

![image](https://user-images.githubusercontent.com/72851613/216545295-d26038bd-7242-4b11-a095-f7b8b674c646.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by KrishJ4856** [comment]
Hey Tamal, I had a question...
In mobile screens, the heading text, description text and image are appearing in multiple rows and under one column
But In case of screen sizes like Ipad, It's appearing in the form of one row and two columns...
According to you, is it better to place them as one column, multiple rows in Ipad screens or the other way?

# Images
### Milan Desktop:
![image](https://user-images.githubusercontent.com/114345816/216657059-55dcf9ef-f352-49c3-b035-3b1bfa903593.png)

### Milan Ipad:
![image](https://user-images.githubusercontent.com/114345816/216657244-ddaaf8c9-5ab5-474d-8795-91b94ba67408.png)

### Milan Iphone:
![image](https://user-images.githubusercontent.com/114345816/216657575-2a9468c7-a933-472e-bb64-2bb4947c41f0.png)

**Comment by IAmTamal** [comment]
See here's the thing, for tablets and stuffs we can keep it the same way as it is for mobiles : 
![image](https://user-images.githubusercontent.com/72851613/216750652-013e912d-3ea2-4cf0-b1bb-fcd359d77d15.png)

The text can come up while the image goes down

**Comment by KrishJ4856** [comment]
Hey Tamal, 
I just made a PR fixing the issue
Please take time out to review it and let me know what you think about it!
