### ISSUE TITLE
[FEATURE] Upgrading the look of shops page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#593]
### Description

- Reduce the gap between the `PRODUCTS` and the `<hr/>`, and also change it's color to `#e26959`
- Make the products card more attractive, i am not telling to copy, highly recommend coming up with own design. Color theme must be same as used by our site.
- Design a product details page

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/217571466-1af76e7d-3fe9-45a5-bd6c-c100942d5c8d.png)

## Products card

Compare Current one :
![image](https://user-images.githubusercontent.com/72851613/217574724-ff772c6d-187f-40e6-9016-837b117a22e5.png)

with this (found on internet):
![image](https://user-images.githubusercontent.com/72851613/217574660-061d89cd-f27f-4cd5-8e3e-f6d942b873c8.png)
 

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by strikertushar19** [comment]
I would like to solve this issue.

**Comment by IAmTamal** [comment]
@strikertushar19 Any updates on the issue ? 
Do reply withing 48 hours, else i'll be putting it out for someonene else !

**Comment by deepoa** [comment]
Hi I would like to solve this issue and can provide with the good attractive card design to this

**Comment by IAmTamal** [comment]
Hi, i'm working on this issue as of now, I'll definetly connect with you when i need any help !
