### ISSUE TITLE
[FEATURE] Upgrading the look of detailed club page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#594]
### Description

- Add the `tagline` instead of adress in the clubs card
- Make the detailed clubs page more attractive, try using your FE skills and giving this page the best look you can think of !
- Make the detailed club page mobile responsive as well (for all devices)

### Screenshots

https://user-images.githubusercontent.com/72851613/217578497-4e0bdcaa-b1b8-456a-961e-99dca35712aa.mp4

![image](https://user-images.githubusercontent.com/72851613/217579504-cd9a4f60-00cb-4c03-adfe-4e4028e7bcb4.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by Satyam005** [comment]
Hello Tamal, I would like to take this up. 
Also if you have any design in mind let me know

**Comment by IAmTamal** [comment]
Hi @Satyam005 , currently i really do not have anything in mind, what i am looking for is `clean` , `minimal` design to be created for the detailed page.  You can come up with something, make a PR and we can work on it !

**Comment by Satyam005** [comment]
Hi, @IAmTamal attaching the screens for the club details page-
Mobile view - 
![image](https://user-images.githubusercontent.com/48182148/218328480-7025a649-5cd3-4cd9-afce-ad68e4bb285a.png)

Tab View -
![image](https://user-images.githubusercontent.com/48182148/218328530-4e1b566a-6531-4927-ad41-fb987be918e7.png)

Desktop View - 
![image](https://user-images.githubusercontent.com/48182148/218328588-aeff554f-d215-46e4-9908-41a75a050557.png)

Let me know your views

**Comment by IAmTamal** [comment]
Looks good ! 
You can make a PR and we can talk changes there
