### ISSUE TITLE
[FEATURE] Adding the close icon when navbar is down in mobile view.

### ISSUE THREAD

**Issue by rohinish404** [IAmTamal/Milan#596]
### Description

How about changing the nav button to close button when a user opens the navbar in the mobile view.

### Screenshots

<img width="531" alt="Screenshot 2023-02-09 at 11 35 10 PM" src="https://user-images.githubusercontent.com/92542124/217899957-d4f0c59a-40f6-4b50-b314-75ac4b70115c.png">

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by victorchrollo14** [comment]
Hi, I would like to add the close icon.

**Comment by Vijeth56** [comment]
Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
@rohinish404 Do you want to work on it ?

**Comment by rohinish404** [comment]
@IAmTamal i think a pr has already been made regarding this #597

**Comment by rohinish404** [comment]
> > @IAmTamal i think a pr has already been made regarding this #597
> 
> That has been closed - if you want to work, you can work on it.

Yeah sure!! Will make a pr regarding this soon!

**Comment by IAmTamal** [comment]
> Hey I would like to have a look into this issue , is it open or been resolved?

You can go ahead !

**Comment by IAmTamal** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.

**Comment by raghav1030** [comment]
heyy i have made some changes to the code.. Please review it and Tell if any correction is to be done?

ps : Sorry for being late as I didn't see that the issue was assigned to me.
