### ISSUE TITLE
[BUGS] Improper format in signup page of footer on inspect

### ISSUE THREAD

**Issue by nishaaannnt** [IAmTamal/Milan#599]
### Description

The footer in the signup page has improper positioning and causes issues while inspecting the website.

### Screenshots

![Screenshot (60)](https://user-images.githubusercontent.com/100792085/223202457-72b7613e-35e9-4309-816e-bbcff6299fca.png)
![Screenshot (59)](https://user-images.githubusercontent.com/100792085/223202535-1fb4633b-0c2e-4c1b-ab17-f28d86b3cd27.png)

### 🥦 Browser

Brave

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Thankyou so much for raising the issue - i'll go through the PR asap !
