### ISSUE TITLE
[FEATURE] Adding an Opengraph image

### ISSUE THREAD

**Issue by Nakamcode** [IAmTamal/Milan#601]
### Description

An Open Graph image is an image that is associated with a webpage and is used when the webpage is shared on social media platforms like Facebook, Twitter, LinkedIn, etc. Open Graph images are also called social sharing images or social media images.

An open graph image increases the click-through rate of a website link when share across social media.

### Screenshots

![Screenshot 2023-03-11 at 14-39-53 OpenGraph - Preview Social Media Share and Generate Metatags](https://user-images.githubusercontent.com/89482825/224490796-0e1cb9e8-5101-46e8-98c6-781f9aed5351.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Oh wow, this is an intresting topic. Great eye @Nakamcode ! 
Assigning this to you.

**Comment by Nakamcode** [comment]
### Here is the Open graph image. please optimized the image and use the site below to get the metadata;

[opengraph.xyz/](opengraph.xyz/)


![Milan](https://user-images.githubusercontent.com/89482825/225614424-37384050-c441-448b-9f3b-35d32533a65d.png)

**Comment by IAmTamal** [comment]
I think you can add it in the code maybe ?

**Comment by Nakamcode** [comment]
I don't have the resource to add it to the code

**Comment by IAmTamal** [comment]
Alright, thanks for your contributions !
