### ISSUE TITLE
[BUGS] Club detailed page responsiveness

### ISSUE THREAD

**Issue by ayushmangarg2003** [IAmTamal/Milan#605]
### Description

Club details page is not responsive for small screen and a few changes in "/styles/ClubDetails.css" can fix that and I would like to do that.

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/105537793/225835941-1c3f6a0a-ce54-4b94-b49e-34644be6b5f7.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Hi @ayushmangarg2003  , someone is already working on this on #598  , i would recommend to put this issue on standy, if they are not responding anymore, i'll assign you to #594  !

**Comment by ayushmangarg2003** [comment]
Okay Tamal, Sounds good. Till then I can find some new issues and contribute to them 😀

**Comment by IAmTamal** [comment]
@ayushmangarg2003 , that PR has been merged. Some improvements has been made for sure.

Using your own UI, Frontend skills you can make any kind of improvement, on top of the one that has already been made. You can fix bugs you find too.

Assigning this to you.

**Comment by ayushmangarg2003** [comment]
I have made some changes in the design and opened a pull request. 
I have also find a new issue the price in shop page is not in the card (screenshot below). I have seen no one has raised this issue. So should I open a new issue for that and close this one. or can continue working on this one in this itself.

![Screenshot (3)](https://user-images.githubusercontent.com/105537793/229109136-a29549a9-b372-47cb-93eb-5c6098b2b931.png)
