### ISSUE TITLE
[FEATURE] Improving SEO, meta-tags

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#609]
### Description

- Currently (as you can see in the screenshot below) we don't have any proper title, description or even images.
- Make an OG image `1200px X 630px` using any tools like Canva, Figma, add meta tags for the same.
- Must be clean and minimal looking, use our theme of  `#e26959` as a background.

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/226530285-b8fcffda-63d0-41d0-8960-ab56c25c448e.png)

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by Yash636261** [comment]
where is this exactly located in website ?

**Comment by IAmTamal** [comment]
> where is this exactly located in website ?

Meta tags are always located in `index.html` by default, else you can always search through the code. If not found, might be a good reason to go ahead and add them !

**Comment by shreyashchandra** [comment]
@IAmTamal I would like to work on this please assign this to me.

**Comment by IAmTamal** [comment]
> @IAmTamal I would like to work on this please assign this to me.

Sure, go ahead !

**Comment by Ipshita02** [comment]
I have experience in using canva if you're open to it, I would love to collaborate with you on this issue.
@IAmTamal  @shreyashchandra

**Comment by shreyashchandra** [comment]
> I have experience in using canva if you're open to it, I would love to collaborate with you on this issue. @IAmTamal @shreyashchandra

That would be great this would help!!! @IAmTamal  could you assign this to both of us?

**Comment by IAmTamal** [comment]
Sure, @Ipshita02 @shreyashchandra  ! 

When making a design, make sure to not write too much on it, and most importantly, use `#e26959` color - which would match our theme too !

**Comment by Ipshita02** [comment]
Hy, Tamal I have created two different preview designs. Which one is looking better? And please suggest any changes if needed
 @IAmTamal @shreyashchandra 
![Add a heading (2)](https://user-images.githubusercontent.com/72136711/229846017-46ac91fc-9967-4a92-9c19-100064470a4c.png)

![Add a heading (1)](https://user-images.githubusercontent.com/72136711/229846198-36191298-0030-4ecc-9e5a-28859b954b06.png)

**Comment by shreyashchandra** [comment]
> Hy, Tamal I have created two different preview designs. Which one is looking better? And please suggest any changes if needed @IAmTamal @shreyashchandra ![Add a heading (2)](https://user-images.githubusercontent.com/72136711/229846017-46ac91fc-9967-4a92-9c19-100064470a4c.png)
> 
> ![Add a heading (1)](https://user-images.githubusercontent.com/72136711/229846198-36191298-0030-4ecc-9e5a-28859b954b06.png)

@Ipshita02  I think the second one will look better, but @IAmTamal  its your call

**Comment by IAmTamal** [comment]
@shreyashchandra  , Generally we don't put alot of texts in OG images. 
They are "preview" images that gets loaded when you share a link. 

So it would be better to have something clean ! 

## Examples : 

![image](https://user-images.githubusercontent.com/72851613/230056283-4fe543cf-2455-4770-8d12-4ccb06d7d2c5.png)

![image](https://user-images.githubusercontent.com/72851613/230056412-3433af57-f941-44fa-972b-40fb379f468c.png)

**Comment by shreyashchandra** [comment]
> @shreyashchandra , Generally we don't put alot of texts in OG images. They are "preview" images that gets loaded when you share a link.
> 
> So it would be better to have something clean !
> 
> ## Examples :
> ![image](https://user-images.githubusercontent.com/72851613/230056283-4fe543cf-2455-4770-8d12-4ccb06d7d2c5.png)
> 
> ![image](https://user-images.githubusercontent.com/72851613/230056412-3433af57-f941-44fa-972b-40fb379f468c.png)

Ok @IAmTamal we will make the necessary changes!

**Comment by Ipshita02** [comment]
> @shreyashchandra , Generally we don't put alot of texts in OG images. They are "preview" images that gets loaded when you share a link.
> 
> So it would be better to have something clean !
> 
> ## Examples :
> ![image](https://user-images.githubusercontent.com/72851613/230056283-4fe543cf-2455-4770-8d12-4ccb06d7d2c5.png)
> 
> ![image](https://user-images.githubusercontent.com/72851613/230056412-3433af57-f941-44fa-972b-40fb379f468c.png)

okk @IAmTamal We'll make the changes

**Comment by shreyashchandra** [comment]
@IAmTamal, @Ipshita02  is this ok!
![MILAN](https://user-images.githubusercontent.com/78721024/235336567-6fdacb38-f494-4cef-85b4-99d0a32040ae.png)

**Comment by IAmTamal** [comment]
Looks good 🔥 

Can you add this to the code, or would you prefer to just mail me?

**Comment by Ipshita02** [comment]
I can definitely add that to the code, you don't have to worry @IAmTamal 

> Looks good 🔥
> 
> Can you add this to the code, or would you prefer to just mail me?

**Comment by IAmTamal** [comment]
Awesome !

**Comment by Lucif3r-in** [comment]
@IAmTamal @Ipshita02 Are you still working on it? Do you need any help?

**Comment by akash19coder** [comment]
Is this issue still alive?

**Comment by IAmTamal** [comment]
### Notice 🚩
I am **closing** this Issue because the contributor is inactive. This will be worked upon by someone else.

Thanks,
Tamal.
