### ISSUE TITLE
[FEATURE] Improving Modal

### ISSUE THREAD

**Issue by vatsalsinghkv** [IAmTamal/Milan#612]
### Description

Currently we are using ReportModal in the `Footer.jsx`, which makes the footer component hard to read and manageable.

It's better to have one separate component for for modal as `Modal.jsx`, which will have that cross button and round corners with white background and that black background (overlay) in the background, the content can be passed through children prop. That way we can separate the modal's logic and design. Thus we can have reusable modal with custom content in it. 

It'll also increase readability of `Footer.jsx` and would make code more manageable

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by IAmTamal** [comment]
Amazing concept, assigining to you !

**Comment by vatsalsinghkv** [comment]
@IAmTamal I am facing some problems in using css styles from `Modal.css`, as its styles are getting applied on the whole project not on just `Modal.jsx`. So would it be okay if I use css modules instead like `Modal.module.css` so it's style only get applied to `Modal.jsx`?

[More on CSS Modules](https://github.com/css-modules/css-modules)

**Comment by IAmTamal** [comment]
Umm i don't understand the concept - if you have different classnames this shouldn't happen.

**Comment by vatsalsinghkv** [comment]
@IAmTamal I have also found some grammatical errors in the project and some .gitignore errors like it's not ignoring the `/dist` dir that produced by running `npm run build`, should I fix them in this issue itself? I should create new issues? (they're small issue)

**Comment by IAmTamal** [comment]
Intresting, i've never tried pushing `/dist` in the first place lol. My bad. 

I think you can make a separate issue for all the other changes. That way we can track the changes that happens over time !
