### ISSUE TITLE
[FEATURE] : Adding a detailed single products page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#613]
### Description

- Now we have an integrated shop page at `/shop`
- All we need to do is make a single product page which can be at `/shop/:id` 
- We can show the picture in the left, and the details to th right.
- Feel free to add anything more you like 🔥

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by DevShobhit** [comment]
@IAmTamal, I would like to work on this

**Comment by IAmTamal** [comment]
Go ahead @DevShobhit .

We expect a **clean and minimal** design. Assigining this to you/

**Comment by DevShobhit** [comment]
![image](https://user-images.githubusercontent.com/74463904/230714646-be5668ac-f016-4fdd-90f5-068fd9137c8e.png)

@IAmTamal  Does it seems fine?

**Comment by IAmTamal** [comment]
Oh wow this looks amazing, you can go ahead you can make a PR !
