### ISSUE TITLE
[BUG]  Contact page fixes

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#616]
### Description

In the footer contact link not working. showing 404 error.a 

### Screenshots

https://user-images.githubusercontent.com/88102392/229873090-bef3982a-d522-4bea-b76f-561be400b75a.mp4

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Oh wow, i haven't noticed it. 
Assigining this to you !

**Comment by priyankarpal** [comment]
hi @IAmTamal should I add your social profile links or GitHub discussion link?
