### ISSUE TITLE
[BUG] Typos and gitignore issues

### ISSUE THREAD

**Issue by vatsalsinghkv** [IAmTamal/Milan#617]
### Description

I have found some typo mistakes in the project and some .gitignore errors like it's not ignoring the /dist dir that produced by running npm run build (they're small issue)

### Screenshots

After running build command it creates unnecessary unstaged changes
<img width="341" alt="Screenshot 2023-04-05 at 4 39 14 PM" src="https://user-images.githubusercontent.com/68834718/230063552-17ee7b5f-dab8-403f-92b0-a3548cfe0950.png">

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great ! 

You can make a PR 🔥
