### ISSUE TITLE
[BUG] Sign Up problem

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#618]
### Description

When I tried to create a new account it was showing me an error. 

### Screenshots

https://user-images.githubusercontent.com/88102392/230079938-e971cddb-3f5b-43ba-9efa-05041aedaf18.mp4

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by SteveSayantan** [comment]
I would like to fix this issue if I am assigned to.

**Comment by IAmTamal** [comment]
> I would like to fix this issue if I am assigned to.

Sure, do fix it !
I'm also looking at the bug
