### ISSUE TITLE
👨‍💻 Feature - React app Club Register Component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#62]
## I want to have a Club's Register component for the react app
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠

**If you look at the registration page for the USER , it looks like this ⤵**

![image](https://user-images.githubusercontent.com/72851613/153323270-3fbb43fb-a6cf-4063-b09c-7f04369198d1.png)

**I want to have this same page for the CLUBS to register**
**🧵 Data --> Club Name , Club Email , Password , Adress , Pincode**

**Here are the files `ClubRegister.jsx` and `ClubRegister.css` ⤵**

![image](https://user-images.githubusercontent.com/72851613/153323430-070804b0-c445-4e81-8c29-0ec389bac8e8.png)

![image](https://user-images.githubusercontent.com/72851613/153323573-d2e944a4-eb0f-4a85-9368-b246a81d6b72.png)

### To-Do 🗒

- You can copy the code from **`UserRegister.jsx`**
- In **`ClubRegister.jsx** you can have this image --> [Signup Image](https://www.figma.com/file/yOe7lJo8hDXkOqhw9rjziw/Assets-%3ECLubs?node-id=0%3A1)
- Make sure the styles, colors, fonts of  **`ClubRegister.jsx`** is similar to **`UserRegister.jsx`**  except for the image
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
Assigned to you , @KushalGhosh9899
