### ISSUE TITLE
[BUG]: Product cards overflowing

### ISSUE THREAD

**Issue by SteveSayantan** [IAmTamal/Milan#620]
### Description

The product cards are looking horrible with overflowing content. After some tweaks, it looks like this:

Before: 
![currentShop](https://user-images.githubusercontent.com/92118155/230459031-b0ece46b-b6b9-4bd9-aa9d-c26e04a170f5.JPG)

After:
![modifiedShop](https://user-images.githubusercontent.com/92118155/230459079-c03fdd37-f32f-4a0e-af42-f3e130664b05.JPG)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Good catch, my guess is it has something to do with the `max-height` property. 
Also donot please remove the `[BUG]` word from the issue title itself ! 

Assigning the issue to you.

**Comment by SteveSayantan** [comment]
When trying to commit the changes, getting this error from eslint
![errorMilan](https://user-images.githubusercontent.com/92118155/230704671-867205ba-6125-4d30-9267-4939601a955f.JPG)

I have no idea how to fix it, need some help 😢

**Comment by IAmTamal** [comment]
> When trying to commit the changes, getting this error from eslint . I didn't touch any of those eslint files. ![errorMilan](https://user-images.githubusercontent.com/92118155/230704671-867205ba-6125-4d30-9267-4939601a955f.JPG)
> 
> I have no idea how to fix it, need some help cry

Intresting, 

- Paste the full error log here 
- Also try `git add .` first and then commit.

**Comment by SteveSayantan** [comment]
> > When trying to commit the changes, getting this error from eslint . I didn't touch any of those eslint files. ![errorMilan](https://user-images.githubusercontent.com/92118155/230704671-867205ba-6125-4d30-9267-4939601a955f.JPG)
> > I have no idea how to fix it, need some help cry
> 
> Intresting,
> 
> * Paste the full error log here
> * Also try `git add .` first and then commit.

`git add .` did not work. Here's the entire error log
[error.txt](https://github.com/IAmTamal/Milan/files/11185012/error.txt)

**Comment by IAmTamal** [comment]
Intresting, i  have never seen these errors before, in your forked copy just delete the `package-lock.json` and also the `node_modules`

If nothing works, delete the local code, re-fork and clone it :D

**Comment by SteveSayantan** [comment]
Neither of those worked, still throwing this error 
``` 
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...     
[STARTED] package.json — 2 files
[STARTED] src/**/*.{js,jsx} — 1 file
[STARTED] src/**/*.html — 0 files
[STARTED] src/**/*.{json,css,scss,md} — 0 files 
[SKIPPED] src/**/*.html — no files
[SKIPPED] src/**/*.{json,css,scss,md} — no files
[STARTED] eslint . --fix
[FAILED] eslint . --fix [FAILED]
[FAILED] eslint . --fix [FAILED]
[FAILED] eslint . --fix [FAILED]
[STARTED] Applying modifications from tasks... 
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[SUCCESS] Cleaning up temporary files...

✖ eslint . --fix:
Error: E:\Milan_ORG\.eslintrc.json:
        Environment key "es2021" is unknown

    at E:\Milan_ORG\node_modules\eslint\lib\config\config-validator.js:158:19
    at Array.forEach (<anonymous>)
    at validateEnvironment (E:\Milan_ORG\node_modules\eslint\lib\config\config-validator.js:154:30)    at Object.validate (E:\Milan_ORG\node_modules\eslint\lib\config\config-validator.js:263:5)     
    at loadFromDisk (E:\Milan_ORG\node_modules\eslint\lib\config\config-file.js:521:19)
    at Object.load (E:\Milan_ORG\node_modules\eslint\lib\config\config-file.js:564:20)
    at Config.getLocalConfigHierarchy (E:\Milan_ORG\node_modules\eslint\lib\config.js:240:44)      
    at Config.getConfigHierarchy (E:\Milan_ORG\node_modules\eslint\lib\config.js:192:43)
    at Config.getConfigVector (E:\Milan_ORG\node_modules\eslint\lib\config.js:299:21)
    at Config.getConfig (E:\Milan_ORG\node_modules\eslint\lib\config.js:342:29)
husky - pre-commit hook exited with code 1 (error) 
```

**Comment by IAmTamal** [comment]
Instead of making commits `Testing2` make commits in this manner `fix: fixed navbar glitch` or `feat: navbar popup added` and so on.

**Comment by SteveSayantan** [comment]
> Instead of making commits `Testing2` make commits in this manner `fix: fixed navbar glitch` or `feat: navbar popup added` and so on.

That was done to generate the error log, however, the error occurs for any type of commit message 😢

**Comment by DevShobhit** [comment]
@SteveSayantan try adding `eslint` with latest version manually in `devdependencies` of `package.json` and then run `npm  install`. For verification whether it worked or not you can run `npm run lint` and it should work fine if the issue is resolved.

**Comment by IAmTamal** [comment]
I am as to more curious why the issue occurs for just one particular user, whereas the other contributors are working just fine.

**Comment by SteveSayantan** [comment]
> @SteveSayantan try adding `eslint` with latest version manually in `devdependencies` of `package.json` and then run `npm install`. For verification whether it worked or not you can run `npm run lint` and it should work fine if the issue is resolved.

Thanks for the help, it worked like magic :)
