### ISSUE TITLE
[BUG] Changes to the looks of user register page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#625]
### Description

- Remove all the icons from the page
- In place of `Enter your name` we can have 2 different labels
- `First name` and `last name` can be there.
- Change `Join us at Milan !` to `Register as an User`

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/231801060-ea070dd2-e9a0-4775-989d-1cb2d8e8a9a8.png)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by Deva-1903** [comment]
I am willing to work on this issue @IAmTamal

**Comment by Anericokakai** [comment]
I'm willing to work on this issue @IAmTamal

**Comment by Deva-1903** [comment]
Don't work on the issue unless you are getting assigned to it. @pravinargade18

**Comment by pravinargade18** [comment]
> Don't work on the issue unless you are getting assigned to it. @pravinargade18

Sorry @IAmTamal. I'll keep it in mind from now on. Thanks!

**Comment by IAmTamal** [comment]
So @Deva-1903 are you willing to work on it, or should I proceed with the PR  #629 ? 

If you are willing to contribute, I'll close the PR.

**Comment by Anericokakai** [comment]
Im willing to work on it here 🙋‍♂️

**Comment by Deva-1903** [comment]
> So @Deva-1903 are you willing to work on it, or should I proceed with the PR #629 ?
> 
> If you are willing to contribute, I'll close the PR.

Assuming you'll assign it to me, I finished and opened a PR.
