### ISSUE TITLE
[BUG] Header alignment for Events page

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#626]
### Description

- The `Events happening now` and `!` are in 2 different lines for the desktop which looks disoriented
- The goal is to make sure it looks good, we can try putting `Events happening` and `now !` in 2 different lines for desktop view.
- For mobile, it is looking good, so we don't need to change that.

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/231801863-9f32b539-d3b9-4b54-a6e1-3a06ecee9f4e.png)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Awesome, do make a PR. We'll review it together 🔥

**Comment by PierreNV** [comment]
I run into an error with eslint when I try to commit: Environment key "es2021" is unknown.

It requires an update of eslint and its plugin which is going to modify package.json...

**Comment by nc1337** [comment]
Is it fine if a work on this issue??
