### ISSUE TITLE
[BUG] Fixing the looks of buttons

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#627]
### Description

- The `explore the shop` button turns yellow on hover, which it shouldn't be doing.
- The `REGISTER` and `LOGIN` buttons are in Caps, and must be reverted.
- The `REGISTER` and `LOGIN` buttons have a whitish glow on hover, which is to be removed.

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/231803000-e35aabb0-2df7-4bd1-b667-39cd70627092.png)

![image](https://user-images.githubusercontent.com/72851613/231828004-c1baf316-78d9-4625-bd3a-b1e6d53d06b8.png)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by k-deepak04** [comment]
i would like to fix these issues

**Comment by Unknownempire** [comment]
I would like to work on this issue and will create a PR shortly

**Comment by Unknownempire** [comment]
@IAmTamal Kindly review the PR and ping back to get more info

**Comment by IAmTamal** [comment]
Great work both of you. Since @k-deepak04 said that they are `unable` to push, I'll proceed with #628
