### ISSUE TITLE
👨‍💻 Feature - Donate Banner react-app

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#63]
## I want to have a Donate banner for my react-app
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**In the homepage between the HOMECARDS and FOOTER i want to add a banner ⤵**

![image](https://user-images.githubusercontent.com/72851613/153324542-3422c5eb-b08b-4591-a91e-936b752e4843.png)

**This is how the Banner is going to look like ⤵**

![image](https://user-images.githubusercontent.com/72851613/153324822-f51fe295-2bdf-461e-83a7-a620716a5768.png)

**You can acess the Design for MOBILE and DESKTOP here --> [Design](https://www.figma.com/file/eiGkzK9UkdCpKmrvsmyILt/Donate-Banner--Milan?node-id=0%3A1)**

### To-Do 📒

- You need to make a new file **`DonateBanner.jsx`** here ⤵
![image](https://user-images.githubusercontent.com/72851613/153325070-92222432-9524-4b6f-b127-9834434b9a08.png)

- You can make the **`DonateBanner.css`** here ⤵
![image](https://user-images.githubusercontent.com/72851613/153325235-e72460a8-8354-41d6-af4f-0667d32b7b10.png)

- You need to follow the **NOTICE** and other **GUIDELINES**

- I will instruct you more in **DISCORD**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I would like to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
> I would like to work on this issue under JWOC.

Assigned to you , **after done/ or any doubts** tag me in `#milan`
