### ISSUE TITLE
[DOCS] Add live link of Milan in docs

### ISSUE THREAD

**Issue by Deva-1903** [IAmTamal/Milan#632]
### Description

Adding a live link to the Milan app in GitHub documentation can be a helpful way to allow easy access to the app for anyone who wants to use it. By providing a direct link, users can quickly navigate to the app and begin using it without having to search for it manually. This can help streamline the user experience and encourage more people to try the app.

Including a live link to the Milan app in GitHub documentation can help increase its visibility and accessibility. This can be especially useful for developers who are looking to collaborate on the project or for users who are interested in testing the app. Overall, adding a live link is a simple but effective way to enhance the user experience and increase engagement with the Milan app.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi there @Deva-1903 , i don't see the reason as to why someone might go ahead and add live link to the documentation as it's already there. 

Plus would highly recommend not to write long descriptions with ChatGPT. Anyways, thanks !
