### ISSUE TITLE
fix: add proper image size

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#634]
### What would you like to share?

- We need to add proper image size to improve SEO

![image](https://user-images.githubusercontent.com/88102392/232233847-b5f0259f-9ee1-49c4-9356-56618ffc10fb.png)

images
- https://milaan.vercel.app/assets/MilanLanding1.2ee0ffc1.png
- https://milaan.vercel.app/assets/LandingMobile.e03cab94.png

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (blank for no)

**Comment by vikaskumar2703** [comment]
i can resolve this issue assign it to me

**Comment by IAmTamal** [comment]
> i can resolve this issue assign it to me

I think, @priyankarpal  is already working on it. Since they have selected the checkbox which says so.

**Comment by priyankarpal** [comment]
@IAmTamal please assign @vikaskumar2703. My exam is going on so I can't do it right now.

**Comment by IAmTamal** [comment]
> @IAmTamal please assign @vikaskumar2703. My exam is going on so I can't do it right now.

Sure, assigning to @vikaskumar2703  !
