### ISSUE TITLE
fix: image not found

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#636]
### Description

We need to replace the image. This image does not exist

### Screenshots

![image](https://user-images.githubusercontent.com/88102392/232234083-8279c759-ea14-4339-9914-0023ec9c3892.png)

![image](https://user-images.githubusercontent.com/88102392/232234100-45e866e0-bb16-4074-9c67-71abed53b3a9.png)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by k-deepak04** [comment]
i would like to work on this issue.
can you please give the image that i should replace or put where there it is showing not found.?

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
