### ISSUE TITLE
👨‍💻 Feature - About us component

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#64]
## I want to have a  About page for my react-app
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**I want to have an ABOUT US page for the react app**

![image](https://user-images.githubusercontent.com/72851613/153325638-978756b5-3f4d-41bf-9342-f9cb7bdfe747.png)

**This is how the Page is going to look like ⤵**

![image](https://user-images.githubusercontent.com/72851613/153325723-428c52dd-b734-4b7a-a673-6fbad1e7c260.png)

**You can acess the Design for MOBILE and DESKTOP here --> [Design](https://www.figma.com/file/kRElsknSsscNBoSGvulFPF/About-Us---Milan)**

### To-Do 📒

- You need to make a new file **`AboutUs.jsx`** here ⤵

![image](https://user-images.githubusercontent.com/72851613/153325866-50f0de5a-36f5-4ef9-9964-ea21f6d2739b.png)

- You can make the **`AboutUs.css`** here ⤵

![image](https://user-images.githubusercontent.com/72851613/153325908-cec2e724-cf6d-4a6e-908b-9e3a5b26ebdd.png)

- You need to follow the **NOTICE** and other **GUIDELINES**

- I will instruct you more in **DISCORD**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by IAmTamal** [comment]
> I would like to take up this issue under JWOC.

Assigned to you , **after done/ or any doubts** tag me in `#milan`

**Comment by tusharjain365** [comment]
I want to work on this issue under JWOC, if anyone not working on it.

**Comment by Aniket-508** [comment]
@IAmTamal Please assign me this issue. One person cannot work on 2 issues simultaneously since the current assignee has already one issue assigned to him.

**Comment by mridul4101** [comment]
> @IAmTamal Please assign me this issue. One person cannot work on 2 issues simultaneously since the current assignee has already one issue assigned to him.

One person can work on 2 issues simultaneously at max. See the guidelines please😅.

**Comment by IAmTamal** [comment]
> @IAmTamal Please assign me this issue. One person cannot work on 2 issues simultaneously since the current assignee has already one issue assigned to him.

@Aniket-508  , one person **CAN** work on  **MAX 2** issues at the same time. 
So , it's perfectly alright.

**Comment by Aniket-508** [comment]
@IAmTamal Still can you assign me this if @mridul4101 doesn't have a problem because he is already ranking 4.

**Comment by mridul4101** [comment]
> @IAmTamal Still can you assign me this if @mridul4101 doesn't have a problem because he is already ranking 4.

I would like to work for these 2 😊.

**Comment by IAmTamal** [comment]
> @IAmTamal Still can you assign me this if @mridul4101 doesn't have a problem because he is already ranking 4.

Sorry , i can't break the rules.
