### ISSUE TITLE
[BUG] On switching tabs from navigation, the new tab opens from same point instead of being on top of page

### ISSUE THREAD

**Issue by guptaanshik1** [IAmTamal/Milan#640]
### Description

Scrolling down on the home page
<img width="1340" alt="Screenshot 2023-04-17 at 12 04 44 AM" src="https://user-images.githubusercontent.com/61491962/232334946-ca90a0d0-e98e-4d86-8228-0566d84689ff.png">

Changing tab to shop from navigation.
![Uploading Screenshot 2023-04-17 at 12.05.00 AM.png…]()

The tab opens from bottom but ideally every tab should open from top.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @guptaanshik1 , always put the screenshots inside the field `Screenshots` . Anyways, a great spot. The `events` page seems to scroll up however the other 2 does not.

**Comment by IAmTamal** [comment]
Hi @guptaanshik1 , any updates? 
I'd like the issue to be solved within the next 2days since it is really not that big & needs like 5-6 lines of code.

**Comment by guptaanshik1** [comment]
Hi @IAmTamal sure will handover the PR to you soon

**Comment by guptaanshik1** [comment]
Hi @IAmTamal I have raised the PR, you can go ahead with the process or let me know if there are any open points
