### ISSUE TITLE
ci: add dependabot gh action

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#641]
### Description

We are using some gh actions & npm dependencies in this project. Usually, we can upgrade all gh actions & dependencies manually but if we add this gh action it will create PR if there are any updates needed. We don't need to worry about it. Just we have to review it & merge it. 

### Screenshots

![image](https://user-images.githubusercontent.com/88102392/234668552-5dab8eff-6b2c-4757-abfd-60dd1fff78c4.png)

### 🥦 Browser

Other

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Suppose Depandabot suggests updating versions, what if the version then instantly breaks production? 

I'm not sure TBH, can you help me out ?

**Comment by priyankarpal** [comment]
> Suppose Depandabot suggests updating versions, what if the version then instantly breaks production?
> 
> I'm not sure TBH, can you help me out ?

If Depandabot suggests updating a dependency to a new version and the update causes production to break immediately then you can rollback to the previous version
