### ISSUE TITLE
chore(dep): migrate to pnpm 

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#642]
### Description

pnpm is a package manager for Node.js applications that provides some advantages over npm and yarn.

## Why to pnpm?
1. It has a faster installation
2. Reduced disk space usage
3. Less network usage etc.

## What do we need to do?
- We need to delete `package-lock.json` file & `node_modules` folder then we need to use `pnpm i` to install dependencies & to run project use `pnpm dev`(for this project).

- We need to fix all documentation & gh actions

### 🥦 Browser

Other

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by priyankarpal** [comment]
> This seems like a lot of changes - for now, I am willing to keep it on hold, because of a lot of existing tasks (especially my semester exams) - once done, we can work on this soon.

ok, no worries.  I tested it in my local system for only the front end. I checked that in the `server` folder there is a `package.json` file so think we also need to migrate it too.

**Comment by IAmTamal** [comment]
> > This seems like a lot of changes - for now, I am willing to keep it on hold, because of a lot of existing tasks (especially my semester exams) - once done, we can work on this soon.
> 
> ok, no worries. I tested it in my local system for only the front end. I checked that in the `server` folder there is a `package.json` file so think we also need to migrate it too.

Yes, instead of two different repos, we kept it one single place, was not so good idea, but it works fine !
