### ISSUE TITLE
[BUG] Color Consistency across buttons

### ISSUE THREAD

**Issue by jayk-gupta** [IAmTamal/Milan#644]
### Description

Some of the buttons have a different background color change on hover.
For example the "explore the shop" button has a yellow color on hover.
There should be consistency across them I feel.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @jayk-gupta , this is already being worked on in #628, for now, I will put it on hold - if the PR author does not respond, I will assign you this.

**Comment by vatsalsinghkv** [comment]
I would recommend having a separate component for the button with customisable text (children as props) so we can have a consistent style like hover, focus and text-transform styles

**Comment by vatsalsinghkv** [comment]
if there's an issue with it we can do this in a new issue like refactoring the code by having a separate button component

**Comment by vatsalsinghkv** [comment]
@IAmTamal  is someone working on this issue?

**Comment by IAmTamal** [comment]
> @IAmTamal is someone working on this issue?

Currently no one is, if you want to work on this I can assign it to you, else I'll be working on it myself. Because this needs to be done quickly !

**Comment by vatsalsinghkv** [comment]
@IAmTamal yea, I'd like to work on this, it wouldn't take much time, I can create one customisable `Button` component, with some predefined style variants like: solid and outlined etc

**Comment by IAmTamal** [comment]
> @IAmTamal yea, I'd like to work on this, it wouldn't take much time, I can create one customisable `Button` component, with some predefined style variants like: solid and outlined etc

Great, 

The idea is to make a button component of 2 different types one can be solid, and the other outlined. The color that we are using for the buttons is `#e26959`, we can still use the same color for a border. 

We also need consistency across different buttons. 

Instead of a bluish gradient we can use our standard color here too
![image](https://github.com/IAmTamal/Milan/assets/72851613/5c411380-c730-482f-83b4-20ec3ca9df37)

**Comment by vatsalsinghkv** [comment]
@IAmTamal in solid buttons what should happen when we hover and focus over these buttons?

**Comment by IAmTamal** [comment]
> @IAmTamal in solid buttons what should happen when we hover and focus over these buttons?

Some can have hover effect which makes them turn from solid to outline.
