### ISSUE TITLE
[FEATURE] Improving the landing page

### ISSUE THREAD

**Issue by Deveesh-Shetty** [IAmTamal/Milan#647]
### Description

The landing page looks too simple now
## If anyone has a cool idea to improve it will be great for the first impression of the website.

My idea may be changing the color of important text and using some decoration for the user to focus mainly on that.
### Screenshots

![730d16d6-651d-4466-b037-6328776cd180](https://user-images.githubusercontent.com/89470104/234918364-91e97aef-9ae1-42fb-8f64-84bec31fc41a.jpeg)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great issue, but until we come up with a design, I suggest we can Open a discussion, in the [Discussions](https://github.com/IAmTamal/Milan/discussions) tab.

The idea was to create a minimal, and simple, clean Landing.

For now, I am closing it, don't forget to Open a Discussion, we can work on it then 🔥

**Comment by Deveesh-Shetty** [comment]
Yeah....sounds good!
