### ISSUE TITLE
🗄 Backend - Make User schema

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#65]
## I want to make a User schema to save their data on register to Mongo Db
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## TO DO 🛠
  
**In our mongo database , we currently have a sample collections ⤵**

![image](https://user-images.githubusercontent.com/72851613/153326490-32549a98-64f9-4c37-892a-8f4120685cc4.png)

**I want to make a collection users where the data are stored when the user registers**
**I want to have the following fields ⤵**

- **first name { type: String , required: true }**
- **lastname { type: String , required: true }**
- **email { type: String , required: true }**
- **password  { type: String , required: true }**
- **adress { type: String , required: true }**
- **pincode { type: Number, required: true }**

 **Make a new file `UserSchema.js` here ⤵**

![image](https://user-images.githubusercontent.com/72851613/153327743-9a9dc2dd-daf6-4a7a-88f9-f5c13657166e.png)

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by yeshwanth235** [comment]
Assign it to me pls

**Comment by IAmTamal** [comment]
> Assign it to me pls

Assigned to you , after done/ or any doubts tag me in `#milan`
