### ISSUE TITLE
[BUG] Page Overflow in small screeens.

### ISSUE THREAD

**Issue by Deveesh-Shetty** [IAmTamal/Milan#651]
### Description

In mobile devices, there is a page overflow on the front page it's shown in the screenshot below.

- The issue I guess is because of the container in the next section which has image animations that moves from the negative X direction to its original position.

### Screenshots

![image](https://user-images.githubusercontent.com/89470104/235158826-1e949534-17a5-4e3a-aaae-e0afc49755e7.png)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great issue, the solution would be to stop the `aos` animations for mobile.

**Comment by munnokd** [comment]
Hey @IAmTamal Can you assign this issue to me?

**Comment by munnokd** [comment]
Thank you @IAmTamal  for assign this issue to me.

**Comment by IAmTamal** [comment]
> Thank you @IAmTamal for assign this issue to me.

Do make a PR once done !

**Comment by IAmTamal** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.

**Comment by IAmTamal** [comment]
> Hey @IAmTamal Sorry for being late because in the previous 2 weeks was gone in my exam so I was not able to make these changes. But I will do this issue this weekend.

Cool !

**Comment by Sreejit-Sengupto** [comment]
I have one more solution to it. In the App component replace the empty angular tags with a div with class name of say "app" and then in it's CSS file add overflow - x: hidden;
