### ISSUE TITLE
[DOCS] Typo in contribution.md

### ISSUE THREAD

**Issue by Shalini469717** [IAmTamal/Milan#653]
### Description

It should be 'by' instead of 'my'.

### Screenshots

![image](https://user-images.githubusercontent.com/99305545/235323794-1b5a17ed-859c-4933-96d7-ba13ab7a0b70.png)

### 🥦 Browser

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great spot, assigning to you.
