### ISSUE TITLE
[DOCS] Link to setups are not working

### ISSUE THREAD

**Issue by tejaskh3** [IAmTamal/Milan#660]
### Description

The links of setting up backend, frontend, and docker files are not working. As of now they are written globally there might be some error in URl.

### Screenshots

<img width="576" alt="i1" src="https://user-images.githubusercontent.com/98630752/236431828-e456d432-bf0b-48e4-bc76-11d87be93b8a.png">

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tejaskh3** [comment]
Hi, Team Milan I am new to beginner in open source community. I have a good foundations over Reactjs and nodejs. I would like to work on this issue

**Comment by tejaskh3** [comment]
>Thankyou @IAmTamal for assigning me this, this is first time when I am gonna contribute for such a big project. I am really thankful to you. 
>And I'll not raise the PR again, sorry for that I didn't know about.

**Comment by IAmTamal** [comment]
Cool also don't use the `>` symbol when writing. That symbol is used to signify notes.

The input 

```md

> **Note**
> This is a note

> **Warning**
> This is a warning

```
becomes

> **Note**
> This is a note

> **Warning**
> This is a warning
