### ISSUE TITLE
[BUG] Failing cypress tests 🧪

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [IAmTamal/Milan#667]
### What would you like to share?

There is a Cypress test failing due to the new feature of the signup popup. This should be fixed on priority so pipeline that the pipeline gets cleared.

![Screenshot 2023-05-12 at 2 27 14 PM](https://github.com/IAmTamal/Milan/assets/88369802/4eb75ad3-0952-4c0e-b738-c2bf123bd37d)
![Screenshot 2023-05-12 at 2 29 22 PM](https://github.com/IAmTamal/Milan/assets/88369802/02ed07b9-bf81-4441-b7c5-6c7c5d6927dc)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi, @IAmTamal! I am working on this.

**Comment by IAmTamal** [comment]
Hi @Syed-Ali-Abbas-Zaidi , you could have opened the issue under the `bug` category. Anyways, I'll review & merge the PR asap, thanks !
