### ISSUE TITLE
[FEATURE] Adding sign in button to homepage

### ISSUE THREAD

**Issue by shobhitexe** [IAmTamal/Milan#699]
### Description

Hey, as seen in below SS there is no sign in button in homepage 
only there are two signup buttons 
its hard for users to first navigate to signup an then do sign in 
its better if we keep a sign in button there 

### Screenshots

![image](https://github.com/IAmTamal/Milan/assets/29349136/66f63e72-1c37-4aa4-a79c-7f20a741a78c)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by i-AmanRawat** [comment]
Can I work on this.

**Comment by IAmTamal** [comment]
Hi @shobhitexe , i think in that case we can work on refactoring the navbar a little bit ? 

How about we move this to the middle , and in the corner we can have the signing button beside signup ? 
![image](https://github.com/IAmTamal/Milan/assets/72851613/c16a0044-7ccf-428a-b04e-7aeeca42aa2a)

**Comment by shobhitexe** [comment]
> Hi @shobhitexe , i think in that case we can work on refactoring the navbar a little bit ?
> 
> How about we move this to the middle , and in the corner we can have the signing button beside signup ? ![image](https://user-images.githubusercontent.com/72851613/239997427-c16a0044-7ccf-428a-b04e-7aeeca42aa2a.png)

Yup good idea 👍 this will give it a good look 
Plz assign this to me I would love to work on it
