### ISSUE TITLE
Replacing the Sign Up button on Navbar with Sign In

### ISSUE THREAD

**Issue by kailashchoudhary11** [IAmTamal/Milan#703]
### What would you like to share?

The Sign In button will be used more by the users as compared to Sign Up. In order to improve user Experience we can replace the sign up button on navbar with the sign in button.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Keshav-0907** [comment]
Can I work on this issue ?

**Comment by IAmTamal** [comment]
This is already been worked in #699 
I will be closing this, to reduce notifications.
