### ISSUE TITLE
[FEATURE] Adding Dark Theme

### ISSUE THREAD

**Issue by PatilHarshh** [IAmTamal/Milan#705]
### Description

it seems website is too bright , need to put dark toggle mode to increase its user experience 

### Screenshots

![Screenshot (55)](https://github.com/IAmTamal/Milan/assets/120102234/62328745-f51f-4bfc-a347-299b22716d29)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by PatilHarshh** [comment]
@IAmTamal  sure i will try

**Comment by IAmTamal** [comment]
@PatilHarshh Now when i see the issues, someone actually made a similar one before - so please wait, and let them complete & you can fix more bugs related to the dark mode. I will close it for now !
![image](https://github.com/IAmTamal/Milan/assets/72851613/4ff9bf72-86e3-42cf-a3c6-672d1657e558)
