### ISSUE TITLE
[OTHER] OnHover on social links on footer is not aligned well

### ISSUE THREAD

**Issue by Tejasp2003** [IAmTamal/Milan#706]
### What would you like to share?

![image](https://github.com/IAmTamal/Milan/assets/75526320/d5663869-72d8-414d-a3be-3bf10c492835)
It should be like, on hover the twitter icon should be in the center. Moreover colors of all icons should be same.

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
This can be a good fix !
You can go ahead and make a PR whenever done 🚀
