### ISSUE TITLE
[OTHER] In mobile view, signup button should have margin top

### ISSUE THREAD

**Issue by Tejasp2003** [IAmTamal/Milan#707]
### What would you like to share?

![image](https://github.com/IAmTamal/Milan/assets/75526320/a05cd521-cfc3-4218-8598-9c72bc07746a)
the shop menu item and signup button have no margin. 

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
This has been fixed when we merged #740  - so closing this for now.
Thanks for spotting the bug ⚡

**Comment by IAmTamal** [comment]
This has been fixed when we merged #740  - so closing this for now.
Thanks for spotting the bug ⚡
