### ISSUE TITLE
To edit Title

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [IAmTamal/Milan#71]
## I want to edit the title and add a logo too
 
---
![Screenshot (58)](https://user-images.githubusercontent.com/73253354/153454809-7db2015a-d868-4dc6-a05a-e31708a7e883.png)

 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
The title needs to be edited and there should be a logo too.
<content>
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by IAmTamal** [comment]
go for it

**Comment by pruthvirajjadhav1** [comment]
Please check the #74 PR
