### ISSUE TITLE
[FEATURE] improve the design of the "Register as an user" form

### ISSUE THREAD

**Issue by rishuraj1** [IAmTamal/Milan#715]
### Description

We might want to improve the the design of the form that is available for user to register. 

Currently it is plain, I want to implement some designs as shown in fig.2 below.
It will match the overall theme and coloring of the page as shown in fig 2.
Also, we would want user to fill form without any hassle so this form can be minimised to the screen height, so that user does not have to scroll and fill the rest part.

I would really like to contribute to this project. Kindly assign me to this task under GSSoC '23. Thank You!

### Screenshots

fig.1:  (before changes)

![Screenshot (95)](https://github.com/IAmTamal/Milan/assets/47839626/05069f8e-223e-4af0-b039-fbaca4bbcd14)

fig2: (proposed idea)

![Screenshot (96)](https://github.com/IAmTamal/Milan/assets/47839626/a40588fb-ff9a-4eb3-99e1-6a02f0b68ef1)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Tushar98644** [comment]
@rishuraj1 @IAmTamal I would like to take this up under Gssoc'23

**Comment by IAmTamal** [comment]
Hi @rishuraj1 , i am not currently wanting to revamp the style of the page because what currently we have is quite minimal and user-friendly. Adding such a color contrastive background is out of standards. Closing this issue for now, thanks for your thoughts.
