### ISSUE TITLE
[FEATURE] password visibility toggle in signup as an user

### ISSUE THREAD

**Issue by SINJINI-G** [IAmTamal/Milan#716]
### Description

Toggle the visibility of the password in user signup page on button click.

## After addition

![image](https://github.com/IAmTamal/Milan/assets/98143022/0451a607-44ef-4773-b6df-2199f74de224)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by SINJINI-G** [comment]
Can you assign me this project for gssoc?

**Comment by LaxmanSingh07** [comment]
Hello Milan, I kindly request you to consider assigning this project to me. I am eager to contribute my knowledge and contribute to the success of this project.

**Comment by IAmTamal** [comment]
Hey @SINJINI-G , great issue !
Would you like this to be assigned under GSSOC'23 ?

**Comment by SINJINI-G** [comment]
> Hey @SINJINI-G , great issue ! Would you like this to be assigned under GSSOC'23 ?

Yes!! Thanks a lot for the opportunity!!
