### ISSUE TITLE
[DOCS] add readme badges

### ISSUE THREAD

**Issue by S-ishita** [IAmTamal/Milan#719]
### Description

I want to add readme badges.Please assign this issue to me 

### Screenshots

![badges](https://github.com/IAmTamal/Milan/assets/104543751/d727195a-4245-4bc9-a674-b27f6bd526a9)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Sounds cool -  we can add the `Opensource`, and after that maybe just these 3 but all in one line : 
![image](https://github.com/IAmTamal/Milan/assets/72851613/8ca79779-0cc7-45c8-96a8-dc2f5ed4569c)
