### ISSUE TITLE
[FEATURE] Add signup/signin with the google authentication

### ISSUE THREAD

**Issue by An525ish** [IAmTamal/Milan#720]
### Description

- want to add google signup/signin facilities  which will increase overall user experience

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Please donot raise duplicate issues, someone already raised this in #711 
Closing this.
