### ISSUE TITLE
Want to add bottom up button to website

### ISSUE THREAD

**Issue by LadityaGogoi** [IAmTamal/Milan#723]
### I Want to add bottom up button to website such that user can go to the top of the website without scrolling (Just Clicking is required).

**It will users a better impression for the site.**

**bottom up button will appear when user cover web scrolling of 100vh**

**please assign this issue to me, under GSSOC2023**

### Screenshots

![16](https://github.com/IAmTamal/Milan/assets/108052802/d5f02353-4618-4cd3-a42a-d5524c0a0fb3)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @Lobi29 , you just checked this : 

![image](https://github.com/IAmTamal/Milan/assets/72851613/968e49b8-acb9-4558-9318-60da3d751172)


But in #696 , this is already been worked on.
Please CHECK PROPERLY always.

Thanks.
