### ISSUE TITLE
adding an API to add Products into database

### ISSUE THREAD

**Issue by Nitish-hack** [IAmTamal/Milan#728]
### Description

products are being displayed statically , to make it dynamic  an API to add products into database is needed so that we can fetch all products from the db and display it dynamically 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Yaay !
You can start working on it, looking forward to the PR.

Make sure you DONOT change the PR TEMPLATE.

**Comment by Nitish-hack** [comment]
yeah sure, thanks alot

**Comment by Nitish-hack** [comment]
@KGoutham7214 yeah sure , drop your's , i'll connect

**Comment by KGoutham7214** [comment]
> 

twitter - @Goutham_Kundena

**Comment by Nitish-hack** [comment]
i am not on twitter , lets connect on linkedin
profile: [Nitish](https://www.linkedin.com/in/nitish9999/)
