### ISSUE TITLE
LogIn Button on NavBar

### ISSUE THREAD

**Issue by venom-10** [IAmTamal/Milan#741]
### What would you like to share?

We don't have any login button in NavBar. I want to add a Login button with the same focus on the right side of the signUp button.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by sakshimaluskar2** [comment]
I am GSSoC Contributor. I want add Login Button on Navbar. Please Assign me this issue.

**Comment by venom-10** [comment]
Actually I will be working on that.

**Comment by shobhitexe** [comment]
hey already a PR #740 created for this

**Comment by IAmTamal** [comment]
Closing this issue since it is already been worked upon. Please do not raise duplicates.
Thanks @shobhitexe for mentioning.
