### ISSUE TITLE
[FEATURE] adding a .env.example file

### ISSUE THREAD

**Issue by kailashchoudhary11** [IAmTamal/Milan#743]
### What would you like to share?

We can add a `.env.example` file to let others know what the `.env` file should look like and what variables it contains.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great idea, I think the reference can be taken from here : 
``` env
<!-- WE USE RAZORPAY DETAILS (TEST ACCOUNT) -->
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=

<!-- YOU CAN PUT YOUR OWN MONGODB CREDENTIALS HERE -->
MONGO_URI=
PORT=""

<!-- YOU CAN PUT YOUR OWN SECRET RANDOM STRING HERE -->
JWT_SECRET=
```
