### ISSUE TITLE
🗄 Backend - User Registration

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#76]
## I want to store the user details once they register
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## TO DO 🛠
 
![image](https://user-images.githubusercontent.com/72851613/153698730-6e09b64f-e6ea-4682-9d7d-14ca256febb9.png)

![image](https://user-images.githubusercontent.com/72851613/153698085-a78b2b6a-7548-43d4-88fd-edbdcefb0792.png)

**I want to save the following information to the DB once the use gives it**
**Define the registration route as ➡ `router.post("/register", async (req, res)`**
**No need to connect the frontend with the backend now.**

- `firstname`
- `lastname`
- `email`
- `password`
- `address`
- `pincode`

**EXTRA ⤵**

**If the USER already exists , `res.json({ exists: true });`**
**Else get the info from `req.body`**
**Encrypt the password with the help of BCRYPT JS (already installed)**
**The secret key for BCRYPT = `thisismysecret123` , i will change it later**

**Once stored successfully , `res.json({ sucess: true });`**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by yeshwanth235** [comment]
Assign it to me pls under jwoc.

**Comment by IAmTamal** [comment]
Go for it , once done/issues tag me in `#milan`
