### ISSUE TITLE
🗄 Backend - Display all clubs

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#78]
## I want to display all clubs from the database
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## TO DO 🛠
 
![image](https://user-images.githubusercontent.com/72851613/153699098-de424347-e812-4f4e-8ccd-3aa6f455bb90.png)

![image](https://user-images.githubusercontent.com/72851613/153699114-7f0730fb-b4d9-4af5-b713-c490f778c853.png)

**Define the  route as ➡ `router.get("/allclubs", async (req, res))`**
**No need to connect the frontend with the backend now.**

**You can `res.json(allclubs);` to return all the data**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by harshit-070** [comment]
I would like to take up this issue under JWOC.

**Comment by IAmTamal** [comment]
go for it @harshit-070
