### ISSUE TITLE
Creating Registration Form

### ISSUE THREAD

**Issue by riiyaaa** [IAmTamal/Milan#8]
I would like to add a registration form, which will be displayed when the user clicks on the "Register" button.

**Comment by ShrutiKapure** [comment]
I want to work on this issue under **JWOC**.

**Comment by RustamTomer** [comment]
I want to work on this issue

**Comment by IAmTamal** [comment]
> I would like to add a registration form, which will be displayed when the user clicks on the "Register" button.

assigning to @riiyaaa 
Go ahead. 
Make sure the page is **responsive**.
The Register page must have proper details. The **UI** should be nice.

**Comment by riiyaaa** [comment]
> > I would like to add a registration form, which will be displayed when the user clicks on the "Register" button.
> 
> assigning to @riiyaaa Go ahead. Make sure the page is **responsive**. The Register page must have proper details. The **UI** should be nice.

I have added the following:
1) Username
2) Email address
3) Password
4) Confirm Password
5) Gender selector
Should I add phone number and DOB too?

**Comment by IAmTamal** [comment]
Add First Name , Last Name 
And just having the phone number should be fine !!

**Comment by riiyaaa** [comment]
I am on it!
