### ISSUE TITLE
🎨 UI/UX - Report button

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#87]
## I want to fix the position of the report button
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
![image](https://user-images.githubusercontent.com/72851613/153735242-9c923a8b-7496-4a12-bcfc-68826cc6bfe2.png)

**As you can see for mobile view the REPORT BUTTON is on the right side i want it in the center**
**You can use Conditional rendering, CSS to fix the button's position in the footer for MOBILES**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

Go for it !!  , @KushalGhosh9899
