### ISSUE TITLE
Make a Navbar !!

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#9]
### I want a Navbar , preferably bootstrap navbar.

**I want items such as : Home , Events, Clubs , User icon on the navbar.
Make sure to check it's responsiveness., font styles.**

**Comment by Mainakroy050** [comment]
I want to work on this issue under JWOC

**Comment by maneet057** [comment]
Please assign this one to me. I will make the navbar

**Comment by harshit4021** [comment]
"I want to work on this issue under JWOC"

**Comment by aditi-gosain** [comment]
I want to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC

Assigned to @Mainakroy050

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC.
