### ISSUE TITLE
🗄 Backend - Clubs Login

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#90]
## I want to login the clubs
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## TO DO 🛠
 
![image](https://user-images.githubusercontent.com/72851613/153698806-a93d73fb-3ee8-4389-ac49-e7d3bbf10f05.png)

**I want to login the CLUB with `email` and `password`**
**Define the loginroute as ➡ `router.post("/login", async (req, res)`**
**No need to connect the frontend with the backend now.**

**POINTS ⤵**

**If `email` and `password` is correct , make a signed JWT token store it as `authtoken`**
**`HELLOSECRET123` is the secret key for authtokens**

**After that you can : `res.json({ sucess: true, authtoken });`**
**If inputted credentials are wrong : `res.json({ sucess: false });`**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I want to work on this issue under JWOC.

**Comment by IAmTamal** [comment]
> I want to work on this issue under JWOC.

Go for it , tag me in `#milan` after done/doubts.
