### ISSUE TITLE
🗄 Backend - User Login

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#91]
## I want to login the users
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## TO DO 🛠
 
![image](https://user-images.githubusercontent.com/72851613/154052300-f4b17f39-5f78-45ee-8d92-9915b236d60a.png)

**I want to login the CLUB with `email` and `password`**
**Define the loginroute as ➡ `router.post("/login", async (req, res)`**
**No need to connect the frontend with the backend now.**

**POINTS ⤵**

**If `email` and `password` is correct , make a signed JWT token store it as `authtoken`**
**`HELLOSECRET123` is the secret key for authtokens**

**After that you can : `res.json({ sucess: true, authtoken });`**
**If inputted credentials are wrong : `res.json({ sucess: false });`**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by yeshwanth235** [comment]
Assign it to me under jwoc pls.

**Comment by IAmTamal** [comment]
Go for it , tag me in `#milan` after done/doubts.
