### ISSUE TITLE
👩‍💻 Feature - Events Banner

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#92]
## I want to have an Events Banner for the react app
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## Files⤵

![image](https://user-images.githubusercontent.com/72851613/154053275-dec89027-5b52-42bb-9faf-dd2f1b9fd5f8.png)

![image](https://user-images.githubusercontent.com/72851613/154053308-e8b87bc3-b1af-4d9b-851a-90d9c9d4399f.png)

**Make sure they are responsive for mobile and Desktop**
**Make sure the fonts are same as that of FIGMA FILE**
**You can use GOOGLE FONTS to get those fonts**

---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC

**Comment by IAmTamal** [comment]
> I want to take this up under JWOC

Go for it , tag me in `#milan` after done/doubts.
