### ISSUE TITLE
🎨 UI/UX - Contact page fix

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#93]
## I want to add missing things to the contact page of the react-app.
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
![image](https://user-images.githubusercontent.com/72851613/154054479-2669a197-a45d-4c2b-bc21-314b579c8137.png)

**As you can see there is no NAVBAR here , i want the navbar to be added**
**I also want a RETURN button to be added in the bottom**
**The return button returns us to home page**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by mridul4101** [comment]
I want to work for this issue under JWOC .

**Comment by IAmTamal** [comment]
> I want to work for this issue under JWOC .

Go for it , tag me in `#milan` after done/doubts.
