### ISSUE TITLE
🎨 UI/UX - About Page Fix

### ISSUE THREAD

**Issue by IAmTamal** [IAmTamal/Milan#94]
## I want to fix the fonts, stylings for the about page.
 
---
 
#### I have read the **[Setup guidelines](https://github.com/IAmTamal/Milan/blob/main/rules/Setup.md)** 🔐
 
 ---

## Notice ⛔
Please make sure in the `.css` files you are making/using , the styles should be applied to **Unique Class names** 

If there are **images** in your `.jsx` files  give them unique classnames like **registrationImage , clubLoginImage**, then in the `css` files make sure the styles are applied to those unique classnames. Else things are getting messed up.

---

## FIXES 🛠
  
**Take a look at this design : [Figma Design](https://www.figma.com/file/kRElsknSsscNBoSGvulFPF/About-Us---Milan?node-id=0%3A1)**

**The React App's fonts looks different from the design ⤵**
![image](https://user-images.githubusercontent.com/72851613/154055468-e0e5b335-7c05-4cb0-98d0-82bc5b9a35b4.png)

**I want you to fix it so that the font stylings are similar to whatever it is in the design.**
  
---
  
## Completed / Doubts ?  🚀
  
Once you are done with the code , please tag me in `#milan` with the **Screenshot** of whatever you made so that we can review that there together.
If you have any **doubts, queries** please tag me in `#milan` so that we can discuss the issue there together.
Please **Donot DM.**

**Comment by Srijita-Mandal** [comment]
Can I work on this issue under JWOC?

**Comment by IAmTamal** [comment]
> Can I work on this issue under JWOC?

go for it , after done/doubts tag me in `#milan`
